/**
 * Unit 2 — Note translations (213 entries)
 * Arabic-speaker specific pedagogy embedded
 */
module.exports = {
  // ── City places (Lesson 1-3) ──
  "Feminine noun. Plural: die Straßen.": "اسم مؤنث (die). الجمع: die Straßen.",
  "Masculine noun. Plural: die Plätze.": "اسم مذكر (der). الجمع: die Plätze.",
  "Feminine noun. Plural: die Brücken.": "اسم مؤنث (die). الجمع: die Brücken.",
  "Feminine noun. Plural: die Kirchen.": "اسم مؤنث (die). الجمع: die Kirchen.",
  "Neuter noun. Compound: Rat (council) + Haus (house).": "اسم محايد (das). مركب: Rat (مجلس) + Haus (بيت). مثل الإضافة بالعربية.",
  "Direction word. No gender (adverb).": "كلمة اتجاه. لا جنس نحوي (ظرف).",
  "Direction word. Compound: gerade (straight) + aus (out).": "كلمة اتجاه مركبة: gerade (مستقيم) + aus (خارج).",
  "Question word for direction/destination.": "كلمة استفهام للاتجاه/الوجهة.",
  "Feminine noun. Plural: die Städte (note the umlaut!).\\nOne of the most common German nouns. Used in many compounds.":
    "اسم مؤنث. الجمع: die Städte (لاحظ النقطتين!). من أكثر الأسماء الألمانية شيوعًا. تُستخدم في مركبات كثيرة.",
  "Feminine noun. Marked with a red A symbol.": "اسم مؤنث. تُعلّم برمز A الأحمر.",
  "Feminine noun. Plural: die Ecken.\\nUsed in directions: um die Ecke = around the corner.":
    "اسم مؤنث. الجمع: die Ecken. تُستخدم في الاتجاهات: um die Ecke = عند الزاوية.",
  "Neuter noun. Plural: die Hotels.\\nSame word internationally. German pronunciation: ho-TEL.":
    "اسم محايد. الجمع: die Hotels. نفس الكلمة دوليًا. النطق الألماني: ho-TEL.",
  "Feminine noun. No common plural in this sense.\\nAlso means mail or post in general.":
    "اسم مؤنث. لا جمع شائع بهذا المعنى. تعني أيضًا البريد عمومًا.",
  "Feminine noun. No plural (collective noun).\\nCall 110 in Germany for the police.":
    "اسم مؤنث. لا جمع (اسم جماعي). اتصل ١١٠ في ألمانيا للشرطة.",
  "Feminine noun. Also means 'the bench'!": "اسم مؤنث. تعني أيضًا 'المقعد الطويل'!",
  "Feminine noun. From Greek 'bibliotheke.'": "اسم مؤنث. من اليونانية bibliotheke. مثل مكتبة بالعربية من نفس الأصل.",
  "Feminine noun. The -ei ending is ALWAYS feminine.": "اسم مؤنث. نهاية ei- دائمًا مؤنثة. قاعدة مهمة!",
  "Neuter noun. das Café = the place, der Kaffee = the drink.": "اسم محايد. das Café = المكان، der Kaffee = المشروب. انتبه للفرق!",
  "Neuter noun. More formal than 'Laden.'": "اسم محايد. أكثر رسمية من Laden.",
  "Feminine noun. Compound: Innen (inner) + Stadt (city).": "اسم مؤنث مركب: Innen (داخلي) + Stadt (مدينة). مثل الإضافة: 'داخل المدينة'.",
  "Neuter noun. From Greek 'kinema' (movement).": "اسم محايد. من اليونانية kinema (حركة). مثل سينما بالعربية.",
  "Masculine noun. Plural: die Märkte.": "اسم مذكر (der). الجمع: die Märkte.",
  "Masculine noun. More casual than Geschäft.": "اسم مذكر. أقل رسمية من Geschäft. مثل 'دكان' مقابل 'محل' بالعربية.",
  "Neuter noun. Pronounced res-toh-RAHNG.": "اسم محايد. تُنطق: res-toh-RAHNG.",
  "Neuter noun. Also means 'lock'!": "اسم محايد. تعني أيضًا 'قفل'!",
  "Neuter noun. Short for Automobil.": "اسم محايد. اختصار Automobil.",
  "Feminine noun. U = Untergrund (underground).": "اسم مؤنث. U = Untergrund (تحت الأرض).",
  "Feminine noun. S = Schnell (fast) or Stadt (city).": "اسم مؤنث. S = Schnell (سريع) أو Stadt (مدينة).",
  "Neuter noun. Compound: Fahr (drive) + Rad (wheel).": "اسم محايد مركب: Fahr (قيادة) + Rad (عجلة). مثل الإضافة: 'عجلة القيادة'.",
  "Masculine noun. Compound: Stadt (city) + Plan (plan).": "اسم مذكر مركب: Stadt (مدينة) + Plan (خطة). خطة المدينة = خريطة المدينة.",
  "Masculine noun. Ein (in) + Gang (walk).": "اسم مذكر. Ein (داخل) + Gang (ممر). المدخل = 'ممشى الدخول'.",
  "Feminine noun. Halte (stop) + Stelle (place).": "اسم مؤنث. Halte (وقف) + Stelle (مكان). الموقف = 'مكان الوقوف'.",
  "Feminine noun. From Kreuz (cross). The -ung ending = always die.": "اسم مؤنث. من Kreuz (صليب/تقاطع). نهاية ung- = دائمًا die.",
  "Feminine -ung noun. From verbinden (to connect).": "اسم مؤنث بنهاية ung-. من verbinden (يربط).",

  // ── Modal verbs ──
  "Modal verb. Ich kann, du kannst, er kann, wir können.": "فعل مشروط. Ich kann، du kannst، er kann، wir können. الأفعال المشروطة لها تصريف خاص.",
  "Modal verb. Ich muss, du musst, er muss, wir müssen.": "فعل مشروط. Ich muss، du musst، er muss، wir müssen.",
  "Modal verb. Ich darf, du darfst, er darf, wir dürfen.": "فعل مشروط. Ich darf، du darfst، er darf، wir dürfen.",
  "Polite form. Ich möchte, du möchtest, er möchte.": "صيغة مهذبة. Ich möchte، du möchtest، er möchte.",
  "Untranslatable particle. Contradicts a negative statement.": "حرف لا يُترجم. ينفي النفي. مثل 'بلى' بالعربية تمامًا!",
  "Makes requests sound friendlier and less demanding.": "تجعل الطلبات تبدو ألطف وأقل إلحاحًا.",

  // ── Prepositions ──
  "Preposition. Ich fahre nach Berlin. = I go to Berlin.": "حرف جر. Ich fahre nach Berlin = أذهب إلى برلين.",
  "Preposition. Ich gehe zu meinem Freund. = I go to my friend.": "حرف جر. Ich gehe zu meinem Freund = أذهب إلى صديقي.",
  "Preposition. Neben dem Hotel. = Next to the hotel.": "حرف جر. Neben dem Hotel = بجانب الفندق.",

  // ── Adjectives ──
  "Adjective. Opposite: klein. 'Groß' also means 'great' or 'grand.'": "صفة. العكس: klein. تعني أيضًا 'عظيم' أو 'فخم'.",
  "Adjective. Opposite: groß. Also used for 'little' or 'minor.'": "صفة. العكس: groß. تُستخدم أيضًا بمعنى 'قليل' أو 'ثانوي'.",
  "Adjective. Opposite: kurz. Used for length, distance, and time.": "صفة. العكس: kurz. تُستخدم للطول والمسافة والوقت.",
  "Adjective. Opposite: lang. Used for length and also time.": "صفة. العكس: lang. تُستخدم للطول وأيضًا الوقت.",
  "Feminine noun. From the verb 'fragen' (to ask).": "اسم مؤنث. من الفعل fragen (يسأل).",
  "Neuter noun. Masculine noun in some dialects.": "اسم محايد. مذكر في بعض اللهجات.",
  "Neuter noun. From Latin 'exemplum.'": "اسم محايد. من اللاتينية exemplum.",
  "Adjective. Opposite: langsam. Same word family as English 'fast.'": "صفة. العكس: langsam. من نفس عائلة الكلمات مثل الإنجليزية fast.",
  "Adjective. Opposite: schnell. Used for speed and pace.": "صفة. العكس: schnell. تُستخدم للسرعة والإيقاع.",
  "Separable verb prefix an-. Ich fange an, du fängst an.": "فعل بسابقة منفصلة an-. Ich fange an، du fängst an.",
  "Separable verb prefix auf-. Ich höre auf, du hörst auf.": "فعل بسابقة منفصلة auf-. Ich höre auf، du hörst auf.",

  // ── Everyday verbs ──
  "Regular verb. Ich bestelle, du bestellst.": "فعل منتظم. Ich bestelle، du bestellst.",
  "Regular verb. Ich bezahle, du bezahlst.": "فعل منتظم. Ich bezahle، du bezahlst.",
  "Regular verb. Ich koche, du kochst.": "فعل منتظم. Ich koche، du kochst.",
  "Adjective/past participle. Ist dieser Platz besetzt?": "صفة/اسم مفعول. ?Ist dieser Platz besetzt (هل هذا المقعد مشغول؟)",
  "Adjective/past participle. Das Geschäft ist geschlossen.": "صفة/اسم مفعول. Das Geschäft ist geschlossen (المحل مغلق).",
  "Adjective. Opposite: richtig. 'Der falsche Zug' = the wrong train.": "صفة. العكس: richtig. Der falsche Zug = القطار الخطأ.",
  "Adjective. Opposite: falsch. 'Die richtige Antwort' = the correct answer.": "صفة. العكس: falsch. Die richtige Antwort = الإجابة الصحيحة.",
  "Adjective. Can mean unfamiliar, foreign, or strange depending on context.": "صفة. يمكن أن تعني غير مألوف أو أجنبي أو غريب حسب السياق.",
  "Adjective. Also used for 'famous' in a positive sense.": "صفة. تُستخدم أيضًا بمعنى 'مشهور' بشكل إيجابي.",
  "Adjective. 'Alles klar!' = All clear! / Everything okay!": "صفة. '!Alles klar' = كل شيء واضح! / كل شيء تمام!",
  "Adjective. 'Gleich' has two meanings: 'same' AND 'right away.'": "صفة. gleich لها معنيان: 'نفسه' و'فورًا'.",
  "Irregular positional verb. Ich sitze, du sitzt.": "فعل وضعي شاذ. Ich sitze، du sitzt.",
  "Irregular positional verb. Ich liege, du liegst.": "فعل وضعي شاذ. Ich liege، du liegst.",

  // ── Transport verbs ──
  "Irregular verb. Stem change a>ä: du fährst, er fährt.": "فعل شاذ. تغير الجذع a>ä: du fährst، er fährt.",
  "Irregular verb. Stem change au>äu: du läufst, er läuft.": "فعل شاذ. تغير الجذع au>äu: du läufst، er läuft.",
  "Separable verb. Ich steige ein, du steigst ein.": "فعل منفصل. Ich steige ein، du steigst ein. السابقة تذهب لنهاية الجملة.",
  "Separable verb. Ich steige aus, du steigst aus.": "فعل منفصل. Ich steige aus، du steigst aus.",
  "Separable verb. Ich steige um, du steigst um.": "فعل منفصل. Ich steige um، du steigst um.",
  "Neuter noun. Spaß machen = to be fun. 'Das macht Spaß!'": "اسم محايد. Spaß machen = يكون ممتعًا. '!Das macht Spaß'",
  "Neuter noun. 'Ein Stück Kuchen' = a piece of cake.": "اسم محايد. Ein Stück Kuchen = قطعة كعك.",
  "Regular verb. Ich bekomme = I get/receive. NOT 'I become'!": "فعل منتظم. Ich bekomme = أحصل/أستلم. ليس 'أصبح'! صديق زائف مع الإنجليزية.",
  "Masculine noun. Plural: die Flüsse.": "اسم مذكر. الجمع: die Flüsse.",
  "Feminine noun. No plural.": "اسم مؤنث. لا جمع.",
  "Masculine noun. Plural: die Seen.": "اسم مذكر. الجمع: die Seen.",

  // ── Travel verbs ──
  "Separable verb: ab + fahren. Der Zug fährt ab.": "فعل منفصل: ab + fahren. Der Zug fährt ab (القطار يغادر).",
  "Regular verb. Ich komme an, du kommst an.": "فعل منفصل. Ich komme an، du kommst an.",
  "Regular verb. Ich besuche, du besuchst.": "فعل منتظم. Ich besuche، du besuchst.",
  "Irregular verb. Ich fliege, du fliegst.": "فعل شاذ. Ich fliege، du fliegst.",
  "Regular verb with dative. Mir gefällt Berlin = I like Berlin (lit: Berlin pleases me).": "فعل مع المجرور. Mir gefällt Berlin = أحب برلين (حرفيًا: برلين تسرني). مثل 'يعجبني' بالعربية!",
  "Regular verb. Ich schließe, du schließt.": "فعل منتظم. Ich schließe، du schließt.",
  "Adverb. 'Leider nein' = unfortunately no.": "ظرف. Leider nein = للأسف لا.",
  "Conjunction. 'Nicht A, sondern B' = Not A, but rather B.": "أداة ربط. Nicht A, sondern B = ليس A بل B.",
  "Feminine noun. From Latin 'idea.'": "اسم مؤنث. من اللاتينية idea. مثل 'فكرة' بالعربية.",
  "Feminine noun. Also used in 'die Hauptsache' = the main thing.": "اسم مؤنث. تُستخدم أيضًا في die Hauptsache = الشيء الرئيسي.",

  // ── Time adverbs ──
  "Adverb. 'Bald' means soon, not bold!": "ظرف. bald تعني قريبًا وليس 'جريء'!",
  "Adverb. 'Dann gehen wir!' = Then let's go!": "ظرف. '!Dann gehen wir' = إذن هيا نذهب!",
  "Adverb. 'Ich esse immer im Café' = I always eat at the café.": "ظرف. Ich esse immer im Café = أنا دائمًا آكل في المقهى.",
  "Adverb. 'Jetzt oder nie!' = Now or never!": "ظرف. '!Jetzt oder nie' = الآن أو أبدًا!",
  "Adverb. 'Nie' is the opposite of 'immer.'": "ظرف. nie عكس immer (دائمًا).",
  "Adverb. 'Ist er noch da?' = Is he still there?": "ظرف. '?Ist er noch da' = هل لا يزال هنا؟",
  "Adverb. 'Nur ein Kaffee, bitte.' = Only one coffee, please.": "ظرف. Nur ein Kaffee, bitte = فقط قهوة واحدة من فضلك.",
  "Adverb. 'Ich gehe oft ins Kino.' = I often go to the cinema.": "ظرف. Ich gehe oft ins Kino = أذهب غالبًا إلى السينما.",
  "Adverb. 'Ich habe schon gegessen.' = I have already eaten.": "ظرف. Ich habe schon gegessen = أكلت بالفعل.",
  "Adverb. 'Komm sofort!' = Come immediately!": "ظرف. '!Komm sofort' = تعال فورًا!",
  "Adverb. Can also mean 'possibly' in some contexts.": "ظرف. يمكن أن تعني أيضًا 'ممكن' في بعض السياقات.",
  "Adverb. 'Komm wieder!' = Come again/back!": "ظرف. '!Komm wieder' = عُد مجددًا!",

  // ── Prepositions (detailed) ──
  "Preposition. Takes dative (location) or accusative (direction).\\nAn der Wand = on the wall (location).\\nAn die Wand = onto the wall (direction).":
    "حرف جر. يأخذ المجرور (مكان) أو المنصوب (اتجاه). An der Wand = على الحائط (مكان). An die Wand = على الحائط (اتجاه). مثل الإعراب بالعربية!",
  "Preposition. Takes dative (location) or accusative (direction).\\nAuf dem Tisch = on the table (location).\\nAuf den Tisch = onto the table (direction).":
    "حرف جر. يأخذ المجرور (مكان) أو المنصوب (اتجاه). Auf dem Tisch = على الطاولة (مكان). Auf den Tisch = على الطاولة (اتجاه).",
  "Preposition. Always takes the accusative case.": "حرف جر. يأخذ دائمًا حالة النصب (Akkusativ). الألمانية لديها ٤ حالات إعراب مثل العربية!",
  "Preposition. Takes accusative. Also used for approximate times.": "حرف جر. يأخذ المنصوب. يُستخدم أيضًا للأوقات التقريبية.",
  "Preposition. Takes dative (location) or accusative (direction).": "حرف جر. يأخذ المجرور (مكان) أو المنصوب (اتجاه).",
  "Preposition. Takes dative (location) or accusative (direction).\\nVor dem Haus = in front of the house.": "حرف جر. يأخذ المجرور (مكان) أو المنصوب (اتجاه). Vor dem Haus = أمام المنزل.",
  "Preposition. Takes dative. Ab morgen = from tomorrow.": "حرف جر. يأخذ المجرور. Ab morgen = من الغد.",
  "Adjective. Wide, broad, extensive.": "صفة. واسع، عريض.",

  // ── Places (Lesson 11-12) ──
  "Masculine noun. Same as in Unit 1. Gleis = platform/track.": "اسم مذكر. نفسه من الوحدة ١. Gleis = رصيف/مسار.",
  "Masculine noun. Same as in Unit 1.": "اسم مذكر. نفسه من الوحدة ١.",
  "Neuter noun. From Latin 'negotium.'": "اسم محايد. من اللاتينية negotium.",
  "Feminine noun. Halte (stop) + Stelle (place). Same as in Unit 2 Lesson 3.": "اسم مؤنث. Halte (وقف) + Stelle (مكان). نفسه من الوحدة ٢ الدرس ٣.",
  "Masculine noun. A German word borrowed internationally!": "اسم مذكر. كلمة ألمانية استُعيرت دوليًا! حتى بالعربية نقول روضة أطفال.",
  "Masculine noun. Same word in many languages.": "اسم مذكر. نفس الكلمة في لغات كثيرة.",
  "Masculine noun. Informal, everyday word for a shop.": "اسم مذكر. كلمة غير رسمية يومية للمحل.",
  "Neuter noun. Used for pubs AND restaurants.": "اسم محايد. تُستخدم للحانات والمطاعم.",
  "Masculine noun. Can mean 'place' or 'town.'": "اسم مذكر. يمكن أن تعني 'مكان' أو 'بلدة'.",
  "Neuter noun. Smaller than a Stadt.": "اسم محايد. أصغر من Stadt.",
  "Masculine noun. 'Ein Platz' = a seat or a square.": "اسم مذكر. Ein Platz = مقعد أو ساحة.",
  "Feminine noun. Compound: Arzt (doctor) + Praxis (practice).": "اسم مؤنث مركب: Arzt (طبيب) + Praxis (ممارسة).",
  "Neuter noun. Compound: Schwimm (swim) + Bad (bath).": "اسم محايد مركب: Schwimm (سباحة) + Bad (حمام). مثل الإضافة: 'حمام السباحة'.",
  "Feminine noun. One of the longest German words learners encounter!": "اسم مؤنث. من أطول الكلمات الألمانية التي يصادفها المتعلمون!",
  "Feminine noun. Die Mitte der Stadt = the center of the city.": "اسم مؤنث. Die Mitte der Stadt = وسط المدينة.",
  "Feminine noun. Also used as an exclamation: 'Achtung!'": "اسم مؤنث. تُستخدم أيضًا كتعجب: '!Achtung'",
  "Feminine noun. Same word internationally.": "اسم مؤنث. نفس الكلمة دوليًا.",

  // ── Transport & directions ──
  "Feminine noun. Compound: Ver (connection) + Bindung (bond).": "اسم مؤنث مركب: Ver (اتصال) + Bindung (رابطة).",
  "Feminine noun. Compound: Auto (car) + Bahn (track).": "اسم مؤنث مركب: Auto (سيارة) + Bahn (مسار). 'مسار السيارات'.",
  "Feminine noun. Same as Bahn. Die Deutsche Bahn = German Railway.": "اسم مؤنث. نفس Bahn. Die Deutsche Bahn = السكة الحديدية الألمانية.",
  "Masculine noun. Compound: Fahr (drive) + er (doer). The -er suffix = doer.": "اسم مذكر مركب: Fahr (قيادة) + er (فاعل). لاحقة er- = الفاعل.",
  "Neuter noun. Same as Gleis. Track/platform at station.": "اسم محايد. نفس Gleis. مسار/رصيف في المحطة.",
  "Masculine noun. Compound: Last (load) + Kraft (power) + Wagen (vehicle).": "اسم مذكر مركب: Last (حمل) + Kraft (قوة) + Wagen (مركبة). 'مركبة قوة الحمل'!",
  "Feminine noun. S = Schnell (fast) or Stadt (city). S-Bahn.": "اسم مؤنث. S = Schnell (سريع) أو Stadt (مدينة). S-Bahn.",
  "Feminine noun. From English 'tram.' Also: die Straßenbahn.": "اسم مؤنث. من الإنجليزية tram. أيضًا: die Straßenbahn.",
  "Masculine noun. No plural needed.": "اسم مذكر. لا حاجة للجمع.",
  "Contraction of an + dem. Common in everyday speech.": "اختصار an + dem. شائع في الكلام اليومي.",
  "Contraction of in + das. Very common in spoken German.": "اختصار in + das. شائع جدًا في الألمانية المنطوقة.",
  "Adjective. Opposite: niedrig (low). Also means 'tall' for people.": "صفة. العكس: niedrig (منخفض). تعني أيضًا 'طويل' للأشخاص.",
  "Adjective. Opposite: nah (near). 'Weit weg' = far away.": "صفة. العكس: nah (قريب). Weit weg = بعيد جدًا.",
  "Adverb. 'So ist das!' = That's how it is!": "ظرف. '!So ist das' = هكذا الأمر!",
  "Pronoun/determiner. 'Alle Menschen' = all people.": "ضمير/محدد. Alle Menschen = كل الناس.",
  "Adverb. 'Daneben' = next to it. 'Nebenbei' = by the way.": "ظرف. daneben = بجانبه. nebenbei = بالمناسبة.",
  "Adverb. Opposite: unten. 'Nach oben' = upwards.": "ظرف. العكس: unten. Nach oben = إلى الأعلى.",
  "Adverb. Opposite: oben. 'Nach unten' = downwards.": "ظرف. العكس: oben. Nach unten = إلى الأسفل.",
  "Adverb. Opposite: vorne. 'Hinten im Bus' = at the back of the bus.": "ظرف. العكس: vorne. Hinten im Bus = في مؤخرة الحافلة.",
  "Adverb. Opposite: drinnen (inside). 'Draußen ist es kalt' = outside it is cold.": "ظرف. العكس: drinnen (داخل). Draußen ist es kalt = الجو بارد في الخارج.",
  "Adverb. Points to a distant location. 'Dort drüben' = over there.": "ظرف. يشير إلى مكان بعيد. Dort drüben = هناك.",
  "Adverb. 'Geh zurück!' = Go back!": "ظرف. '!Geh zurück' = ارجع!",

  // ── Movement verbs ──
  "Separable verb. Prefix ab-. Der Zug fährt um 8 ab.": "فعل منفصل. سابقة ab-. Der Zug fährt um 8 ab (القطار يغادر الساعة ٨).",
  "Separable verb. Prefix ab-. Ich hole dich ab.": "فعل منفصل. سابقة ab-. Ich hole dich ab (سآخذك). فعل شائع جدًا!",
  "Regular verb with inseparable prefix be-. Wir besichtigen Berlin.": "فعل منتظم بسابقة غير منفصلة be-. Wir besichtigen Berlin (نتجول في برلين).",
  "Irregular verb. Er hält, du hältst. Stem change a>ä.": "فعل شاذ. Er hält، du hältst. تغير الجذع a>ä.",
  "Irregular positional verb. Ich stehe, du stehst.": "فعل وضعي شاذ. Ich stehe، du stehst.",
  "Regular verb. Ich suche, du suchst. 'Ich suche den Bahnhof.'": "فعل منتظم. Ich suche، du suchst. Ich suche den Bahnhof = أبحث عن المحطة.",
  "Regular verb. 'Wir wandern im Wald' = We hike in the forest.": "فعل منتظم. Wir wandern im Wald = نتنزه في الغابة.",
  "Irregular verb. Ich bleibe, du bleibst. Past: ich blieb.": "فعل شاذ. Ich bleibe، du bleibst. الماضي: ich blieb.",
  "Regular verb. 'Wie lange dauert das?' = How long does it take?": "فعل منتظم. '?Wie lange dauert das' = كم يستغرق هذا؟",
  "Regular verb. Ich leihe, du leihst. Can mean both lend and borrow!": "فعل منتظم. Ich leihe، du leihst. يعني 'يُقرض' و'يستعير' معًا!",
  "Separable verb. Prefix mit-. 'Kommst du mit?' = Are you coming along?": "فعل منفصل. سابقة mit-. '?Kommst du mit' = هل ستأتي معنا؟",
  "Regular verb. Ich zeige, du zeigst. 'Zeig mir den Weg!'": "فعل منتظم. Ich zeige، du zeigst. '!Zeig mir den Weg' = أرني الطريق!",
  "Separable verb. Prefix mit-. 'Nimm mich mit!' = Take me along!": "فعل منفصل. سابقة mit-. '!Nimm mich mit' = خذني معك!",
  "Separable verb. Prefix weiter-. 'Fahr weiter!' = Keep driving!": "فعل منفصل. سابقة weiter-. '!Fahr weiter' = واصل القيادة!",
  "Separable verb. Prefix um-. 'Wo muss ich umsteigen?'": "فعل منفصل. سابقة um-. '?Wo muss ich umsteigen' = أين يجب أن أحوّل؟",
  "Verb phrase. 'Der Laden hat geöffnet' = The shop is open.": "عبارة فعلية. Der Laden hat geöffnet = المحل مفتوح.",
  "Colloquial adverb. 'Ich war gerade da' = I was just there.": "ظرف عامي. Ich war gerade da = كنت هناك للتو.",

  // ── Tourist vocabulary ──
  "Masculine noun. 'Der Blick auf Berlin' = The view of Berlin.": "اسم مذكر. Der Blick auf Berlin = المنظر على برلين.",
  "Feminine noun. 'Ich brauche Hilfe!' = I need help!": "اسم مؤنث. '!Ich brauche Hilfe' = أحتاج مساعدة!",
  "Feminine noun. 'Eine Durchsage am Bahnhof' = an announcement at the station.": "اسم مؤنث. Eine Durchsage am Bahnhof = إعلان في المحطة.",
  "Feminine noun. Same word internationally. Die Auskunft = the information desk.": "اسم مؤنث. نفس الكلمة دوليًا. Die Auskunft = مكتب الاستعلامات.",
  "Feminine noun. Through (durch) + saying (sage). A through-saying = announcement.": "اسم مؤنث. durch (عبر) + Sage (قول). 'قول عبر' = إعلان.",
  "Neuter noun. 'Das Schild lesen' = to read the sign.": "اسم محايد. Das Schild lesen = قراءة اللافتة.",
  "Feminine noun. 'Vorsicht, Stufe!' = Caution, step!": "اسم مؤنث. '!Vorsicht, Stufe' = حذار، درجة!",
  "Neuter noun. 'Ans Meer fahren' = to go to the sea.": "اسم محايد. Ans Meer fahren = الذهاب إلى البحر. هل تحن للبحر؟",
  "Masculine noun. 'Einen Ausflug machen' = to make a day trip.": "اسم مذكر. Einen Ausflug machen = القيام برحلة نهارية.",
  "Neuter noun. 'Ein Foto machen' = to take a photo.": "اسم محايد. Ein Foto machen = التقاط صورة.",
  "Feminine noun. With a guide: Stadtführung. Self-guided: Rundgang.": "اسم مؤنث. مع مرشد: Stadtführung. بدون مرشد: Rundgang.",
  "Feminine noun. Can mean map, ticket, OR card. Context decides.": "اسم مؤنث. يمكن أن تعني خريطة أو تذكرة أو بطاقة. السياق يحدد.",
  "Masculine noun. From French 'prospectus.'": "اسم مذكر. من الفرنسية prospectus.",
  "Neuter noun. Reise (travel) + Büro (office).": "اسم محايد مركب. Reise (سفر) + Büro (مكتب). مثل الإضافة: 'مكتب السفر'.",
  "Masculine noun. Can be a book OR a person who guides tourists.": "اسم مذكر. يمكن أن يكون كتابًا أو شخصًا يرشد السياح.",
  "Pronoun/adjective. 'Ein anderes Mal' = another time.": "ضمير/صفة. Ein anderes Mal = مرة أخرى.",
  "Pronoun. 'Ich habe alles!' = I have everything!": "ضمير. '!Ich habe alles' = لدي كل شيء!",
  "Masculine noun. 'Freier Eintritt' = free admission.": "اسم مذكر. Freier Eintritt = دخول مجاني.",
};
