/**
 * Unit 2 — All src field translations (209 entries)
 * Word/phrase translations + story narration
 */
module.exports = {
  // ── Story narration ──
  "Brandenburg Gate. Pink sky. Verumius stands with a city map. The map is upside down. He turns it. Now everything is even more confusing.":
    "بوابة براندنبورغ. سماء وردية. يقف فيروميوس بخريطة مدينة. الخريطة مقلوبة. يقلبها. الآن كل شيء أكثر إرباكًا.",
  "Okay. I have a city map. I have two eyes. I just need one street. How hard can it be?":
    "حسنًا. لدي خريطة مدينة. لدي عينان. أحتاج شارعًا واحدًا فقط. كم يمكن أن يكون صعبًا؟",
  "Verumius goes left. Then right. Then left again. Then he is standing at the Brandenburg Gate again. He has walked a perfect circle.":
    "يذهب فيروميوس يسارًا. ثم يمينًا. ثم يسارًا مجددًا. ثم يجد نفسه واقفًا عند بوابة براندنبورغ مرة أخرى. لقد مشى دائرة كاملة.",
  "Straight ahead. Always straight ahead. This street has to lead somewhere.":
    "مباشرة للأمام. دائمًا للأمام. هذا الشارع يجب أن يؤدي إلى مكان ما.",
  "Berlin has everything: pharmacies, bakeries, cafes. You just need to know what things are called. Verumius does not know yet.":
    "برلين فيها كل شيء: صيدليات، مخابز، مقاهي. تحتاج فقط أن تعرف ماذا تُسمى الأشياء. فيروميوس لا يعرف بعد.",
  "The city, the street, the bridge, the church. Everything has a gender. Even the city map. The city map that leads me in circles.":
    "المدينة، الشارع، الجسر، الكنيسة. كل شيء له جنس نحوي. حتى خريطة المدينة. الخريطة التي تقودني في دوائر.",
  "No signal. No internet. Just a tourist with a city map and a little courage. Time to ask real people.":
    "لا إشارة. لا إنترنت. مجرد سائح بخريطة مدينة وقليل من الشجاعة. حان وقت سؤال أناس حقيقيين.",
  "Excuse me, can you help me? I would like to get to the station. A woman points left. A man points right. Verumius stands in the middle.":
    "عذرًا، هل يمكنك مساعدتي؟ أريد الوصول إلى المحطة. امرأة تشير يسارًا. رجل يشير يمينًا. فيروميوس يقف في الوسط.",
  "Verumius stands at an intersection. The light is red. He waits. And waits. Then he crosses. MISTAKE! An elderly woman calls out: 'You must NOT do that! The light is RED!'":
    "يقف فيروميوس عند تقاطع. الإشارة حمراء. ينتظر. وينتظر. ثم يعبر. خطأ! امرأة مسنة تنادي: 'لا يجوز فعل ذلك! الإشارة حمراء!'",
  "The woman is right. You must not cross on red. I understand. In Germany, you wait. Even when no car is coming. Even at night. Always.":
    "المرأة محقة. لا يجوز العبور على الأحمر. أفهم. في ألمانيا تنتظر. حتى عندما لا تأتي سيارة. حتى في الليل. دائمًا.",
  "Verumius can now ask, listen, and understand. Slowly. But he understands. That is the first step.":
    "فيروميوس يستطيع الآن أن يسأل ويستمع ويفهم. ببطء. لكنه يفهم. هذه هي الخطوة الأولى.",
  "The man. The woman. The child. Three little words. One massive problem. Welcome to the article monster.":
    "الرجل. المرأة. الطفل. ثلاث كلمات صغيرة. مشكلة ضخمة. مرحبًا بك في وحش أدوات التعريف.",
  "Der, die, das. Small but important. Slowly I see the patterns. The bakery, the intersection, the direction. Everything with -ei and -ung is die. Thank you, patterns.":
    "Der، die، das. صغيرة لكنها مهمة. ببطء أرى الأنماط. المخبز، التقاطع، الاتجاه. كل شيء بـ ei- و ung- هو die. شكرًا أيتها الأنماط.",
  "Day two. Verumius walks through Berlin. Every shop, every sign, every corner is a lesson. Today he learns what the city does.":
    "اليوم الثاني. يمشي فيروميوس عبر برلين. كل محل وكل لافتة وكل زاوية درس. اليوم يتعلم ماذا تفعل المدينة.",
  "Eat, buy, work, cook. The city is not foreign. It is familiar. Everything clear? Yes. Everything clear.":
    "يأكل، يشتري، يعمل، يطبخ. المدينة ليست غريبة. هي مألوفة. كل شيء واضح؟ نعم. كل شيء واضح.",
  "One hour. Verumius has been walking for an hour. The map says: Bürgeramt, 500 meters. Reality says: Döner stand, 5 meters. It smells fantastic.":
    "ساعة واحدة. فيروميوس يمشي منذ ساعة. الخريطة تقول: مكتب المواطنين ٥٠٠ متر. الواقع يقول: كشك دونر ٥ أمتار. الرائحة رائعة.",
  "Verumius stands at the Döner stand by the Spree. The sun is shining. The seller asks: 'With everything?' Verumius does not understand and says: 'Yes, yes!' He gets a massive Döner.":
    "يقف فيروميوس عند كشك الدونر بجانب نهر شبريه. الشمس مشرقة. البائع يسأل: 'بكل الإضافات؟' فيروميوس لا يفهم ويقول: 'نعم، نعم!' يحصل على دونر ضخم.",
  "I do not understand a word. But the Döner is good. Very good. The seller laughs and says: 'With everything' means with everything. Thank you, Döner man.":
    "لا أفهم كلمة. لكن الدونر لذيذ. لذيذ جدًا. البائع يضحك ويقول: 'بكل الإضافات' تعني بكل الإضافات. شكرًا يا رجل الدونر.",
  "A young man stands in line. Headphones, guitar on his back. He nods at Verumius. Verumius nods back. Not a word. Just Döner solidarity.":
    "شاب يقف في الطابور. سماعات وغيتار على ظهره. يومئ لفيروميوس. فيروميوس يومئ بالمثل. ولا كلمة. مجرد تضامن دونر.",
  "The Bürgeramt can wait. This Döner cannot. Sometimes the detour is the destination.":
    "مكتب المواطنين يمكنه الانتظار. هذا الدونر لا يمكنه. أحيانًا المنعطف هو الوجهة.",
  "Two days in Berlin. The city map is ruined. The shoes are tired. But the head is full of words. Time to show what Verumius can do.":
    "يومان في برلين. الخريطة تالفة. الحذاء متعب. لكن الرأس مليء بالكلمات. حان الوقت لإظهار ما يستطيع فيروميوس فعله.",
  "Tiergarten. Evening. The sun goes down. Verumius sits on a bench by the Spree and thinks.":
    "تيرغارتن. مساءً. الشمس تغرب. يجلس فيروميوس على مقعد بجانب نهر شبريه ويفكر.",
  "Sunset on the Spree. Verumius sits on a bench. Döner remains, a useless city map, and a smile. Not the Bürgeramt, but the best Döner in Berlin found.":
    "غروب على نهر شبريه. فيروميوس يجلس على مقعد. بقايا دونر وخريطة مدينة عديمة الفائدة وابتسامة. ليس مكتب المواطنين، لكن أفضل دونر في برلين وُجد.",
  "One day in Berlin: the wrong map, the red traffic light, the best Döner. Verumius says: 'Tomorrow I will try again. I like Berlin.'":
    "يوم واحد في برلين: الخريطة الخاطئة، إشارة المرور الحمراء، أفضل دونر. فيروميوس يقول: 'غدًا سأحاول مجددًا. أحب برلين.'",
  "Verumius walks home. Tomorrow: the Bürgeramt. German bureaucracy awaits. Forms, queue numbers, and the word 'Formular' will haunt him. But tonight: Good night, Berlin.":
    "يمشي فيروميوس إلى البيت. غدًا: مكتب المواطنين. البيروقراطية الألمانية في الانتظار. استمارات وأرقام انتظار وكلمة Formular ستطارده. لكن الليلة: تصبح على خير يا برلين.",
  "Now. Soon. Already. Still. Small words, but without them German sounds like a machine. With them it sounds like music.":
    "الآن. قريبًا. بالفعل. لا يزال. كلمات صغيرة لكن بدونها الألمانية تبدو كآلة. معها تبدو كموسيقى.",
  "The bakery, the bus stop, the exit. Every place has a name. And every name has a gender. Of course.":
    "المخبز، موقف الحافلة، المخرج. كل مكان له اسم. وكل اسم له جنس نحوي. بالطبع.",
  "The main station. Five floors, 300,000 travelers per day. Verumius stands in the middle. The S-Bahn goes north. The U-Bahn goes south. He just needs to know: where to?":
    "المحطة المركزية. خمسة طوابق و٣٠٠ ألف مسافر يوميًا. فيروميوس يقف في الوسط. القطار السريع يذهب شمالًا. المترو يذهب جنوبًا. يحتاج فقط أن يعرف: إلى أين؟",
  "Coming and going. Searching and finding. Getting on and getting off. Berlin is a verb. You just have to join in.":
    "قدوم وذهاب. بحث وإيجاد. صعود ونزول. برلين فعل. عليك فقط المشاركة.",
  "Verumius stands at the TV Tower. The view over Berlin. He sees the streets, the bridges, the churches. He knows their names. All of them. This is no longer a foreign place.":
    "يقف فيروميوس عند برج التلفزيون. المنظر على برلين. يرى الشوارع والجسور والكنائس. يعرف أسماءها. كلها. لم يعد هذا مكانًا غريبًا.",

  // ── Word/phrase translations ──
  "the square, plaza": "الساحة / الميدان",
  "the bridge": "الجسر",
  "the church": "الكنيسة",
  "the city hall": "مبنى البلدية",
  "the city / town": "المدينة",
  "the pharmacy": "الصيدلية",
  "the corner": "الزاوية",
  "the post office": "مكتب البريد",
  "the police": "الشرطة",
  "the bank": "البنك",
  "the library": "المكتبة",
  "the bakery": "المخبز",
  "the cafe": "المقهى",
  "the shop, store, business": "المحل / المتجر",
  "the city center": "وسط المدينة",
  "the cinema": "السينما",
  "the market": "السوق",
  "the shop (casual)": "الدكان",
  "the castle, palace": "القلعة / القصر",
  "the subway": "المترو",
  "the city train": "قطار المدينة",
  "the bicycle": "الدراجة",
  "the city map": "خريطة المدينة",
  "the entrance": "المدخل",
  "the bus/tram stop": "موقف الحافلة / الترام",
  "the intersection": "التقاطع",
  "the connection": "الاتصال / الوصلة",
  "can, to be able to": "يستطيع / يقدر",
  "must, to have to": "يجب",
  "may, to be allowed to": "يجوز / مسموح",
  "would like": "يود / يريد",
  "yes! (contradicting a negative), indeed": "بلى! (لنفي النفي)، بالفعل",
  "just, once (softener)": "فقط / مرة (للتلطيف)",
  "to (cities/countries), after": "إلى (مدن/بلدان)، بعد",
  "to (specific places/people)": "إلى (أماكن/أشخاص محددين)",
  "next to, beside": "بجانب",
  "to show, to point": "يُظهر / يشير",
  "big, tall, great": "كبير / طويل / عظيم",
  "small, little": "صغير / قليل",
  "long": "طويل",
  "short (length or time)": "قصير (طول أو وقت)",
  "the question": "السؤال",
  "the problem": "المشكلة",
  "the example": "المثال",
  "fast, quick": "سريع",
  "slow": "بطيء",
  "to start, to begin": "يبدأ",
  "to stop, to quit": "يتوقف / يُنهي",
  "to order": "يطلب",
  "to pay": "يدفع",
  "to cook": "يطبخ",
  "occupied, taken": "مشغول / محجوز",
  "closed": "مغلق",
  "wrong, false": "خاطئ / خطأ",
  "right, correct": "صحيح / صواب",
  "foreign, strange, unfamiliar": "غريب / أجنبي / غير مألوف",
  "well-known, famous": "مشهور / معروف",
  "clear, obvious": "واضح",
  "same, equal; right away": "نفسه / متساوٍ؛ فورًا",
  "to sit (state)": "يجلس (حالة)",
  "to lie, to be located": "يقع / يرقد",
  "to drive, to go by vehicle": "يقود / يذهب بمركبة",
  "to walk, to run": "يمشي / يركض",
  "to get in, to board": "يصعد / يركب",
  "to get out, to exit": "ينزل / يخرج",
  "to transfer, to change trains": "يُحوّل / يغير القطار",
  "fun": "متعة / مرح",
  "piece, item": "قطعة / عنصر",
  "to get, to receive": "يحصل على / يستلم",
  "the river": "النهر",
  "the sun": "الشمس",
  "the lake": "البحيرة",
  "to depart (vehicle)": "يغادر (مركبة)",
  "to arrive": "يصل",
  "to visit": "يزور",
  "to fly": "يطير",
  "to please, to like": "يعجب / يحب",
  "to close": "يغلق",
  "unfortunately": "للأسف",
  "but rather (after negation)": "بل / وإنما (بعد النفي)",
  "the idea": "الفكرة",
  "the thing, matter": "الشيء / الأمر",
  "soon": "قريبًا",
  "then": "ثم / حينها",
  "always": "دائمًا",
  "now": "الآن",
  "never": "أبدًا",
  "still, yet": "لا يزال / بعد",
  "only": "فقط",
  "often": "غالبًا / كثيرًا",
  "already": "بالفعل / سبق أن",
  "immediately": "فورًا / حالًا",
  "perhaps, maybe": "ربما / لعل",
  "again": "مجددًا / مرة أخرى",
  "on, at (a surface or location)": "على / عند (سطح أو مكان)",
  "on, upon, on top of": "على / فوق",
  "through": "عبر / خلال",
  "against, around (time)": "ضد / حوالي (وقت)",
  "over, about, across": "فوق / عن / عبر",
  "before, in front of": "قبل / أمام",
  "from (a point in time or place)": "من (نقطة زمنية أو مكانية)",
  "wide, broad": "واسع / عريض",
  "the platform": "الرصيف",
  "the exit": "المخرج",
  "the shop, the business": "المحل / العمل التجاري",
  "the stop, the station": "المحطة / الموقف",
  "the kindergarten": "روضة الأطفال",
  "the kiosk": "الكشك",
  "the shop, the store": "المحل / المتجر",
  "the restaurant, the pub": "المطعم / الحانة",
  "the place, the town": "المكان / البلدة",
  "the village": "القرية",
  "the square, the seat": "الساحة / المقعد",
  "the doctor's office": "عيادة الطبيب",
  "the swimming pool": "المسبح",
  "the sight, the attraction": "المعلم السياحي",
  "the middle, the center": "الوسط / المركز",
  "attention, caution": "انتباه / حذر",
  "the information": "المعلومات",
  "the connection (transit)": "الوصلة (نقل)",
  "the highway, the motorway": "الطريق السريع",
  "the railway, the train": "السكة الحديدية / القطار",
  "the driver": "السائق",
  "the track, the platform": "المسار / الرصيف",
  "the truck": "الشاحنة",
  "the city train, the commuter rail": "قطار المدينة / القطار المحلي",
  "the tram, the streetcar": "الترام",
  "the north": "الشمال",
  "the south": "الجنوب",
  "the east": "الشرق",
  "the west": "الغرب",
  "at the (contraction of an + dem)": "عند الـ (اختصار an + dem)",
  "into the (contraction of in + das)": "في الـ (اختصار in + das)",
  "high, tall": "عالٍ / مرتفع",
  "far, wide": "بعيد / واسع",
  "so, such, like this": "هكذا / مثل هذا",
  "all, every": "كل / جميع",
  "next to it, beside it": "بجانبه",
  "up, above, upstairs": "فوق / أعلى / في الطابق العلوي",
  "down, below, downstairs": "تحت / أسفل / في الطابق السفلي",
  "behind, at the back": "خلف / في الخلف",
  "outside": "في الخارج",
  "there (at a distance)": "هناك (على بُعد)",
  "back, backwards": "للخلف / رجوعًا",
  "to depart (by plane)": "يقلع (بالطائرة)",
  "to pick up (a person or thing)": "يأخذ / يلتقط (شخصًا أو شيئًا)",
  "to visit, to tour (a place)": "يزور / يتجول في (مكان)",
  "to hold, to stop": "يمسك / يتوقف",
  "to stand": "يقف",
  "to search, to look for": "يبحث عن",
  "to hike": "يتنزه / يمشي في الطبيعة",
  "to stay, to remain": "يبقى / يمكث",
  "to last, to take (time)": "يستغرق (وقتًا)",
  "to lend, to borrow": "يُقرض / يستعير",
  "to come along": "يأتي معه",
  "to show": "يُظهر / يُري",
  "to take along": "يأخذ معه",
  "to continue driving, to drive on": "يواصل القيادة",
  "to transfer, to change (trains/buses)": "يُحوّل / يغير (القطار/الحافلة)",
  "to be open": "يكون مفتوحًا",
  "just, right now (colloquial)": "للتو / حالًا (عامي)",
  "the view, the glance": "المنظر / النظرة",
  "the help": "المساعدة",
  "the announcement": "الإعلان",
  "the information, the information desk": "المعلومات / مكتب الاستعلامات",
  "the PA announcement": "إعلان مكبر الصوت",
  "the sign": "اللافتة",
  "the caution, the care": "الحذر / العناية",
  "the sea": "البحر",
  "the excursion, the day trip": "الرحلة النهارية",
  "the photo": "الصورة",
  "the guided tour": "الجولة المرشدة",
  "the map, the ticket, the card": "الخريطة / التذكرة / البطاقة",
  "the brochure, the flyer": "الكتيب / النشرة",
  "the travel agency": "وكالة السفر",
  "the travel guide (book or person)": "دليل السفر (كتاب أو شخص)",
  "other, different": "آخر / مختلف",
  "everything": "كل شيء",
  "the entry, the admission": "الدخول / القبول",
};
