/** Unit 04 Part 1 — Arabic translations (302 strings) */
module.exports = {
  "Verumius enters a German supermarket for the first time. Shopping carts need a coin. Cashiers don't bag. Cash is king. Survival starts now.": "فيروميوس يدخل سوبرماركت ألمانياً لأول مرة. عربات التسوق تحتاج عملة معدنية. الكاشير لا يعبّئ الأكياس. الدفع النقدي هو السائد. البقاء يبدأ الآن.",
  "Shopping vocabulary": "مفردات التسوق",
  "Money words and payment": "كلمات المال والدفع",
  "Navigate a German supermarket": "التنقل في سوبرماركت ألماني",
  "REWE. Red letters. Automatic doors. Verumius stands in front with an empty cloth bag. No, wait. Without a cloth bag. Without anything.": "REWE. حروف حمراء. أبواب آلية. فيروميوس يقف أمامها بكيس قماش فارغ. لا، انتظر. بدون كيس قماش. بدون أي شيء.",
  "The shopping carts. They are... together? With a chain? I pull. And pull. Nothing happens.": "عربات التسوق. هي... متصلة؟ بسلسلة؟ أسحب. وأسحب. لا شيء يحدث.",
  "An old woman walks past. She puts a coin in the slot. Click. Her cart is free. Verumius has no coin. He has a fifty-euro bill.": "امرأة مسنّة تمرّ. تضع عملة في الفتحة. طقّ. عربتها تتحرر. فيروميوس ليس لديه عملة. لديه ورقة خمسين يورو.",
  "What is this machine? Green lights. A hole for bottles. Maybe... a game? A machine? I have no bottle. I have nothing.": "ما هذا الجهاز؟ أضواء خضراء. فتحة للزجاجات. ربما... لعبة؟ آلة؟ ليس لديّ زجاجة. ليس لديّ شيء.",
  "to shop / go grocery shopping": "التسوق / شراء الحاجيات",
  "Separable: ich kaufe ein, du kaufst ein.": "فعل منفصل: ich kaufe ein, du kaufst ein.",
  "A: Where do you shop?\\nB: I shop at the supermarket.": "A: أين تتسوق؟\\nB: أتسوق في السوبرماركت.",
  "Germans plan grocery trips like military operations. List, bags, coins for the cart. No impulse buying. Hildi would approve.": "الألمان يخططون لرحلة التسوق كعملية عسكرية. قائمة، أكياس، عملات للعربة. لا شراء عشوائي. هيلدي سترضى عن ذلك.",
  "the customer (m/f)": "الزبون / الزبونة",
  "Masculine: der Kunde. Feminine: die Kundin.": "مذكر: der Kunde. مؤنث: die Kundin.",
  "A: Are you a customer here?\\nB: Yes, I am a customer.": "A: هل أنت زبون هنا؟\\nB: نعم، أنا زبون.",
  "German always has male + female forms for people: Kunde/Kundin, Verkäufer/Verkäuferin. The gendered forms are standard.": "في الألمانية دائماً صيغة مذكر ومؤنث للأشخاص: Kunde/Kundin، Verkäufer/Verkäuferin. الصيغتان مستخدمتان بشكل قياسي.",
  "the checkout / register": "الصندوق / الكاشير",
  "Feminine. Where you pay.": "مؤنث. المكان الذي تدفع فيه.",
  "A: Where is the checkout?\\nB: The checkout is back there.": "A: أين الصندوق؟\\nB: الصندوق هناك في الخلف.",
  "German cashiers sit down. They will NEVER bag your groceries. You bag. Fast. While the next customer's items are already on the belt.": "الكاشير الألماني يجلس أثناء العمل. لن يعبّئ مشترياتك أبداً. أنت تعبّئ. بسرعة. بينما أغراض الزبون التالي تنزلق على السير بالفعل.",
  "the salesperson": "البائع",
  "Masculine. Feminine: die Verkäuferin.": "مذكر. المؤنث: die Verkäuferin.",
  "A: The salesperson is nice.\\nB: Yes, he is helping me.": "A: البائع لطيف.\\nB: نعم، إنه يساعدني.",
  "Literally 'the seller.' German loves compound transparency. Ver+käufer from ver+kaufen.": "حرفياً \"البائع\". الألمانية تحب الشفافية في الكلمات المركبة. Ver+käufer من ver+kaufen.",
  "the price": "السعر",
  "Masculine. Plural: die Preise.": "مذكر. الجمع: die Preise.",
  "A: How is the price?\\nB: The price is good.": "A: كيف السعر؟\\nB: السعر جيد.",
  "'Preis' sounds like 'price' because it IS the same Germanic root. Preiswert = price-worthy = good value.": "كلمة Preis تشبه price الإنجليزية لأنهما من نفس الجذر الجرماني. Preiswert = تستحق ثمنها = سعر مناسب.",
  "Regular. Also: zahlen = to pay (in general).": "فعل منتظم. أيضاً: zahlen = يدفع (بشكل عام).",
  "A: I would like to pay.\\nB: Cash or card?": "A: أريد أن أدفع.\\nB: نقداً أم بالبطاقة؟",
  "'Bezahlen' = pay for something specific. 'Zahlen' = pay in general. Both work at the register. 'Zahlen, bitte!' = check, please!": "bezahlen = يدفع لشيء محدد. zahlen = يدفع بشكل عام. كلاهما يعملان عند الكاشير. عبارة !Zahlen, bitte = الحساب من فضلك!",
  "the money": "المال / النقود",
  "Neuter. Also: der Euro, der Cent.": "محايد. أيضاً: der Euro، der Cent.",
  "A: Do you have money?\\nB: Yes, I have twenty euros.": "A: هل معك نقود؟\\nB: نعم، معي عشرون يورو.",
  "Euro coins show different countries on the back. German euros have the Brandenburg Gate, an eagle, or an oak leaf. Collect them all!": "عملات اليورو تعرض دولاً مختلفة على ظهرها. اليورو الألماني يحمل بوابة براندنبورغ أو نسراً أو ورقة بلوط. اجمعها كلها!",
  "the credit card": "بطاقة الائتمان",
  "Feminine. Many German shops still don't accept them!": "مؤنث. كثير من المتاجر الألمانية لا تقبلها حتى الآن!",
  "A: Do you accept credit card?\\nB: No, cash only.": "A: هل تقبلون بطاقة الائتمان؟\\nB: لا، نقداً فقط.",
  "Many German shops STILL don't take cards. Cash is king. Always carry Bargeld. The Bäckerei, the Kiosk, the Döner stand: bar only.": "كثير من المتاجر الألمانية لا تقبل البطاقات حتى الآن. النقد هو الملك. احمل Bargeld دائماً. المخبز، الكشك، محل الدونر: نقداً فقط.",
  "Regular. Opposite: verkaufen (to sell).": "فعل منتظم. العكس: verkaufen (يبيع).",
  "A: I am buying bread.\\nB: Good, we need bread.": "A: أنا أشتري خبزاً.\\nB: جيد، نحتاج خبزاً.",
  "Kauf = buy. Ver+kauf = sell. The ver- prefix flips meaning. Like mieten/vermieten from Unit 3.": "Kauf = شراء. Ver+kauf = بيع. السابقة ver- تعكس المعنى. مثل mieten/vermieten من الوحدة 3.",
  "the offer / special deal": "العرض / التخفيض",
  "Neuter. Also: die Tasche (bag), der Schuh (shoe), die Jacke (jacket).": "محايد. أيضاً: die Tasche (حقيبة)، der Schuh (حذاء)، die Jacke (جاكيت).",
  "A: The offer is great!\\nB: Yes, very good!": "A: العرض ممتاز!\\nB: نعم، جيد جداً!",
  "'Sonderangebot' = special offer. Germans plan shopping around Angebote. The weekly flyer is sacred. Hildi has a filing system.": "Sonderangebot = عرض خاص. الألمان يخططون تسوقهم حول العروض الأسبوعية. نشرة العروض مقدّسة. هيلدي لديها نظام أرشفة لها.",
  "the bill / receipt": "الفاتورة / الإيصال",
  "Feminine. Also: der Automat (machine).": "مؤنث. أيضاً: der Automat (آلة).",
  "A: Can I have the bill?\\nB: Here you go.": "A: هل يمكنني الحصول على الفاتورة؟\\nB: تفضّل.",
  "'Automat' = any machine: Kaffeeautomat, Parkscheinautomat, Pfandautomat (bottle deposit machine). Germans automate everything.": "Automat = أي آلة: Kaffeeautomat (آلة قهوة)، Parkscheinautomat (آلة تذاكر الوقوف)، Pfandautomat (آلة إرجاع الزجاجات). الألمان يؤتمتون كل شيء.",
  "the clothing": "الملابس",
  "Feminine. Collective noun, always singular.": "مؤنث. اسم جمعي، دائماً مفرد في الألمانية.",
  "A: I need new clothes.\\nB: The clothing is good.": "A: أحتاج ملابس جديدة.\\nB: الملابس جيدة.",
  "Like Obst and Gemüse, Kleidung is always singular. For individual items: der Schuh (shoe), die Jacke (jacket), die Tasche (bag).": "مثل Obst وGemüse، كلمة Kleidung دائماً مفرد. للقطع المنفردة: der Schuh (حذاء)، die Jacke (جاكيت)، die Tasche (حقيبة).",
  "Verumius stands outside REWE.\\nHe needs a Euro coin for the Einkaufswagen (shopping cart).\\nHe has only a 50-Euro bill.\\nThe Pfandautomat blinks at him.\\n\\nPfand = bottle deposit. Germans return bottles to machines for money.\\nEvery bottle has a Pfand value (8-25 cents).\\nThe adventure begins.": "فيروميوس يقف خارج REWE.\\nيحتاج عملة يورو لعربة التسوق Einkaufswagen.\\nلديه فقط ورقة 50 يورو.\\nآلة الزجاجات Pfandautomat تومض أمامه.\\n\\nPfand = تأمين الزجاجة. الألمان يعيدون الزجاجات إلى الآلات مقابل المال.\\nكل زجاجة لها قيمة Pfand (8-25 سنت).\\nالمغامرة تبدأ.",
  "Many German shops only accept one form of payment. Not plastic.": "كثير من المتاجر الألمانية تقبل شكلاً واحداً فقط من الدفع. ليس البطاقة.",
  "A special deal or discount that makes something cheaper than usual.": "عرض خاص أو تخفيض يجعل الشيء أرخص من المعتاد.",
  "The offer is good! I am buying the jacket.": "العرض جيد! أنا أشتري الجاكيت.",
  "Translate each part of this compound noun separately.": "ترجم كل جزء من هذا الاسم المركب على حدة.",
  "Verumius grabs a basket. Like a tourist. No cart, no coin, no bag. But courage. That he has.": "فيروميوس يأخذ سلة. كسائح. لا عربة، لا عملة، لا كيس. لكن الشجاعة. هذه يملكها.",
  "The produce aisle. 22 food words and 10 drink words, each with its article. Germany has 3,200 bread varieties. UNESCO agrees.": "ممر الخضار والفواكه. 22 كلمة طعام و10 كلمات مشروبات، كل منها بأداة تعريفها. ألمانيا فيها 3,200 نوع خبز. اليونسكو يوافق.",
  "22 food words with gender": "22 كلمة طعام مع الجنس النحوي",
  "10 drink words with gender": "10 كلمات مشروبات مع الجنس النحوي",
  "Master der/die/das for food": "إتقان der/die/das للطعام",
  "The produce section. Colors like a painting. Verumius knows no word for any of it. Red things. Yellow things. Green things. Everything looks good.": "قسم الخضار والفواكه. ألوان كاللوحة. فيروميوس لا يعرف كلمة لأي منها. أشياء حمراء. أشياء صفراء. أشياء خضراء. كل شيء يبدو جيداً.",
  "the cheese": "الجبن",
  "Masculine noun. Plural: die Käsesorten.\\nGermany produces over 400 cheese varieties.": "اسم مذكر. الجمع: die Käsesorten.\\nألمانيا تنتج أكثر من 400 نوع جبن.",
  "A: Would you like cheese?\\nB: Yes, a piece of cheese, please!": "A: هل تريد جبناً؟\\nB: نعم، قطعة جبن من فضلك!",
  "the fruit (collective)": "الفاكهة (اسم جمعي)",
  "Neuter. ALWAYS singular. Never 'Obste.'": "محايد. دائماً مفرد. لا يُقال أبداً Obste.",
  "A: I like eating fruit.\\nB: Which fruit do you buy?": "A: أحب أكل الفاكهة.\\nB: أي فاكهة تشتري؟",
  "Obst is always singular in German. You never say 'Obste.' Same with Gemüse. German hates pluralizing categories.": "Obst دائماً مفرد في الألمانية. لا يُقال أبداً Obste. نفس الشيء مع Gemüse. الألمانية لا تجمع أسماء الفئات.",
  "the apple": "التفاحة",
  "Masculine. Plural: die Äpfel (umlaut!).": "مذكر. الجمع: die Äpfel (مع أوملاوت!).",
  "A: The apple is good.\\nB: I am buying three apples.": "A: التفاحة جيدة.\\nB: أشتري ثلاث تفاحات.",
  "Plural changes the vowel: Apfel to Äpfel. Umlaut magic! Same pattern: Vater to Väter, Bruder to Brüder.": "الجمع يغيّر حرف العلة: Apfel تصبح Äpfel. سحر الأوملاوت! نفس النمط: Vater تصبح Väter، Bruder تصبح Brüder.",
  "the banana": "الموزة",
  "Feminine. Also: die Birne (pear). Both start with B!": "مؤنث. أيضاً: die Birne (إجاصة). كلاهما يبدأ بحرف B!",
  "A: A banana, please.\\nB: And a pear?": "A: موزة من فضلك.\\nB: وإجاصة؟",
  "Both feminine, both fruit, both start with B. Life is easy sometimes.": "كلاهما مؤنث، كلاهما فاكهة، كلاهما يبدأ بحرف B. الحياة سهلة أحياناً.",
  "the tomato": "الطماطم",
  "Feminine. Also: die Kartoffel (potato).": "مؤنث. أيضاً: die Kartoffel (بطاطا).",
  "A: The tomatoes are fresh.\\nB: And the fruit?": "A: الطماطم طازجة.\\nB: والفاكهة؟",
  "'Kartoffel' originally meant 'truffle'! Germans renamed the potato after truffles when it arrived from the Americas.": "Kartoffel كانت تعني في الأصل \"كمأة\"! الألمان سمّوا البطاطا على اسم الكمأة عندما وصلت من الأمريكيتين.",
  "the vegetables (collective)": "الخضروات (اسم جمعي)",
  "Neuter. Always singular, like Obst.": "محايد. دائماً مفرد، مثل Obst.",
  "A: I need vegetables.\\nB: Vegetables are good.": "A: أحتاج خضروات.\\nB: الخضروات مفيدة.",
  "Like Obst, Gemüse is always singular. German hates pluralizing categories. Der Salat = lettuce/salad.": "مثل Obst، كلمة Gemüse دائماً مفرد. الألمانية لا تجمع أسماء الفئات. Der Salat = خس / سلطة.",
  "the cucumber": "الخيار",
  "Feminine: die Gurke. Plural: die Gurken.": "مؤنث: die Gurke. الجمع: die Gurken.",
  "A: Fresh cucumbers!\\nB: Two for one euro!\\nA: I'll take four, please.": "A: خيار طازج!\\nB: اثنتان بيورو واحد!\\nA: سآخذ أربع من فضلك.",
  "'Saure Gurke' (sour cucumber) = pickle. In Berlin, 'Spreewaldgurken' from the Spreewald region are legendary. They even have pickle festivals.": "Saure Gurke (خيار حامض) = مخلل. في برلين، Spreewaldgurken من منطقة شبريفالد أسطورية. لديهم حتى مهرجانات للمخللات.",
  "the onion": "البصل",
  "Feminine: die Zwiebel. Plural: die Zwiebeln.": "مؤنث: die Zwiebel. الجمع: die Zwiebeln.",
  "A: Do you need onions?\\nB: Yes, three onions please.": "A: هل تحتاج بصلاً؟\\nB: نعم، ثلاث بصلات من فضلك.",
  "'Zwiebelkuchen' (onion cake) is a savory autumn treat in Southern Germany, always paired with 'Federweißer' (young wine). A seasonal tradition.": "Zwiebelkuchen (فطيرة البصل) هي وجبة خريفية مالحة في جنوب ألمانيا، تُقدّم دائماً مع Federweißer (نبيذ فتيّ). تقليد موسمي.",
  "Two important category words:\\n\\nObst = fruit (das Obst, neuter, uncountable)\\nGemüse = vegetables (das Gemüse, neuter, uncountable)\\n\\nUse them when shopping:\\nIch suche das Obst. = I am looking for the fruit section.\\nHaben Sie frisches Gemüse? = Do you have fresh vegetables?\\n\\nNote: individual fruits use their own article (der Apfel, die Banane), but the category word Obst is always das.": "كلمتان مهمتان للفئات:\\n\\nObst = فاكهة (das Obst، محايد، لا يُجمع)\\nGemüse = خضروات (das Gemüse، محايد، لا يُجمع)\\n\\nاستخدمهما عند التسوق:\\nIch suche das Obst. = أبحث عن قسم الفواكه.\\nHaben Sie frisches Gemüse? = هل لديكم خضروات طازجة؟\\n\\nملاحظة: كل فاكهة منفردة لها أداتها الخاصة (der Apfel، die Banane)، لكن كلمة الفئة Obst دائماً das.",
  "the bread": "الخبز",
  "Neuter. Also: das Brötchen (bread roll).": "محايد. أيضاً: das Brötchen (خبز صغير / كعكة).",
  "A: I am buying bread.\\nB: And butter?": "A: أشتري خبزاً.\\nB: وزبدة؟",
  "the butter": "الزبدة",
  "Feminine. Also: das Ei (egg), das Salz (salt), das Öl (oil).": "مؤنث. أيضاً: das Ei (بيضة)، das Salz (ملح)، das Öl (زيت).",
  "A: Butter, please.\\nB: Here you go!": "A: زبدة من فضلك.\\nB: تفضّل!",
  "Ei to Eier is one of German's weird plurals. Salz and Öl are both neuter. Liquids and powders often are.": "Ei تصبح Eier وهي من جموع الألمانية الغريبة. Salz وÖl كلاهما محايد. السوائل والمساحيق غالباً محايدة.",
  "the meat": "اللحم",
  "Neuter. Also: der Fisch (fish), das Hähnchen (chicken).": "محايد. أيضاً: der Fisch (سمك)، das Hähnchen (دجاج).",
  "A: I am buying meat.\\nB: Meat is good.": "A: أشتري لحماً.\\nB: اللحم جيد.",
  "Hähnchen = little rooster (Hahn + chen). The diminutive -chen makes EVERYTHING neuter. Just like Mädchen.": "Hähnchen = ديك صغير (Hahn + chen). اللاحقة التصغيرية chen- تجعل كل شيء محايداً. تماماً مثل Mädchen (فتاة).",
  "the ham": "لحم الخنزير المقدّد",
  "Masculine. Also: der Kuchen (cake), der Reis (rice).": "مذكر. أيضاً: der Kuchen (كعكة)، der Reis (أرز).",
  "A: Two hundred grams of ham, please.\\nB: Here, exactly two hundred.": "A: مئتا غرام من الشينكن من فضلك.\\nB: تفضّل، بالضبط مئتان.",
  "Germans eat ham for breakfast. On bread. With butter. Every morning. The Brotzeit (bread-time) is sacred.": "الألمان يأكلون الشينكن على الفطور. على الخبز. مع الزبدة. كل صباح. وجبة Brotzeit (وقت الخبز) مقدّسة.",
  "the fries / chips": "البطاطا المقلية",
  "Always plural (die). Germans say 'Pommes' (POMM-ess).": "دائماً جمع (die). الألمان يقولون Pommes (تُنطق: بوم-ِس).",
  "A: Fries with mayo?\\nB: Yes, always!": "A: بطاطا مقلية مع مايونيز؟\\nB: نعم، دائماً!",
  "Germans say 'Pommes' (POMM-ess), never 'frites.' And yes, they put mayo on them. Ketchup is also common, but mayo is the default.": "الألمان يقولون Pommes (بوم-ِس)، وليس أبداً frites. ونعم، يضعون المايونيز عليها. الكاتشب شائع أيضاً، لكن المايونيز هو الأساس.",
  "the water": "الماء",
  "Neuter. Also: die Milch (milk), der Kaffee (coffee), der Tee (tea).": "محايد. أيضاً: die Milch (حليب)، der Kaffee (قهوة)، der Tee (شاي).",
  "A: Water or milk?\\nB: Coffee, please!": "A: ماء أم حليب؟\\nB: قهوة من فضلك!",
  "German water is almost always sparkling (mit Kohlensäure). Ask for 'stilles Wasser' if you want flat. This confuses every tourist.": "الماء في ألمانيا دائماً تقريباً غازي (mit Kohlensäure). اطلب stilles Wasser إذا أردت ماءً عادياً. هذا يربك كل سائح.",
  "the juice": "العصير",
  "Masculine. Also: das Bier (beer), der Wein (wine).": "مذكر. أيضاً: das Bier (بيرة)، der Wein (نبيذ).",
  "A: Juice, please!\\nB: Here, a juice.": "A: عصير من فضلك!\\nB: تفضّل، عصير.",
  "Germans can legally drink beer and wine at 16. Spirits at 18. Saft (juice) is for the youngsters.": "في ألمانيا يُسمح قانونياً بشرب البيرة والنبيذ من عمر 16. المشروبات الروحية من 18. العصير Saft للصغار.",
  "the drink / beverage": "المشروب",
  "Neuter. Also: die Flasche (bottle), das Glas (glass).": "محايد. أيضاً: die Flasche (زجاجة)، das Glas (كأس).",
  "A: A drink, please.\\nB: What would you like to drink?": "A: مشروب من فضلك.\\nB: ماذا تريد أن تشرب؟",
  "'Flasche' also means 'loser' in slang. Don't call someone a Flasche.": "Flasche تعني أيضاً \"فاشل\" في العامية. لا تنادِ أحداً بـ Flasche.",
  "the food / groceries": "المواد الغذائية",
  "Neuter. Literally: means-of-life.": "محايد. حرفياً: وسائل الحياة.",
  "A: The groceries are fresh.\\nB: Yes, very good.": "A: المواد الغذائية طازجة.\\nB: نعم، جيدة جداً.",
  "Leben (life) + Mittel (means) = means of life. German compound poetry at its finest.": "Leben (حياة) + Mittel (وسيلة) = وسائل الحياة. شعر الكلمات المركبة الألمانية في أجمل حالاته.",
  "A round red fruit from the produce section.": "فاكهة مستديرة حمراء من قسم الخضار والفواكه.",
  "Baked goods often take das in German.": "المخبوزات غالباً تأخذ das في الألمانية.",
  "Which one is a drink, not food?": "أيّها مشروب وليس طعاماً؟",
  "I like to drink coffee.": "أحب أن أشرب القهوة.",
  "Tomaten is plural. Plural verb form needed.": "Tomaten جمع. يحتاج صيغة الفعل الجمع.",
  "I put the yellow things in the basket. And the red ones. And... I don't know what that is, but it smells good.": "أضع الأشياء الصفراء في السلة. والحمراء. و... لا أعرف ما هذا، لكن رائحته طيبة.",
  "Numbers beyond 20, all the colors, and how to weigh produce. The deli counter awaits: you MUST know your Gramm from your Kilo.": "الأرقام فوق 20، كل الألوان، وكيف تزن المنتجات. طاولة اللحوم تنتظرك: يجب أن تعرف الفرق بين Gramm وKilo.",
  "Count to 1,000+": "العدّ حتى 1,000 وأكثر",
  "Name all basic colors": "تسمية كل الألوان الأساسية",
  "Weights and measurements": "الأوزان والمقاييس",
  "The bakery counter. Behind the glass: rolls, pretzels, cake. In front of the glass: six people. They wait. Verumius waits too. Ten minutes.": "طاولة المخبز. خلف الزجاج: كعكات، بريتزل، كيك. أمام الزجاج: ستة أشخاص. ينتظرون. فيروميوس ينتظر أيضاً. عشر دقائق.",
  "A woman behind him says: 'Do you have a number?' Verumius sees the red machine on the wall. TAKE A NUMBER. He did not take a number.": "امرأة خلفه تقول: \"هل لديك رقم؟\" فيروميوس يرى الآلة الحمراء على الحائط. خُذ رقماً. هو لم يأخذ رقماً.",
  "Number 47. The display says: 38. I had no number. Now I have one. But nine people are ahead of me.": "الرقم 47. الشاشة تقول: 38. لم يكن لديّ رقم. الآن لديّ واحد. لكن تسعة أشخاص قبلي.",
  "30 / 40 / 50": "30 / 40 / 50",
  "Tens: add -zig to the root. dreißig is the exception (not dreizig).": "العشرات: أضف zig- إلى الجذر. dreißig هي الاستثناء (وليس dreizig).",
  "A: Thirty euros?\\nB: No, forty!": "A: ثلاثون يورو؟\\nB: لا، أربعون!",
  "German flips digit order: 43 = 'dreiundvierzig' (three-and-forty). Brain breaker for English speakers. Get used to it!": "الألمانية تعكس ترتيب الأرقام: 43 = dreiundvierzig (ثلاثة وأربعون). هذا مألوف في العربية! فالعربية تقول أيضاً \"ثلاثة وأربعون\".",
  "60 / 70 / 80 / 90": "60 / 70 / 80 / 90",
  "Siebzig (not siebenzig). The 'en' gets eaten.": "siebzig (وليس siebenzig). حرفا en يُحذفان.",
  "A: Seventy or sixty?\\nB: Eighty!": "A: سبعون أم ستون؟\\nB: ثمانون!",
  "Siebzig drops the 'en': sieben to siebzig. Same thing happens with siebte (7th). German likes trimming.": "siebzig تحذف en: من sieben إلى siebzig. نفس الشيء يحدث مع siebte (السابع). الألمانية تحب الاختصار.",
  "100 / 1,000": "100 / 1,000",
  "'Ein' before them is optional: hundert = einhundert.": "كلمة ein قبلها اختيارية: hundert = einhundert.",
  "A: A hundred euros!\\nB: No, a thousand!": "A: مئة يورو!\\nB: لا، ألف!",
  "Both forms correct: hundert or einhundert, tausend or eintausend. Germans are flexible here.": "كلا الشكلين صحيح: hundert أو einhundert، tausend أو eintausend. الألمان مرنون هنا.",
  "German numbers above 20 are built units-first:\\n\\n21 = einundzwanzig (one and twenty)\\n22 = zweiundzwanzig (two and twenty)\\n35 = fünfunddreißig (five and thirty)\\n47 = siebenundvierzig (seven and forty)\\n\\nPattern: units + und + tens.\\nAll written as one word.": "الأرقام الألمانية فوق 20 تُبنى بالآحاد أولاً:\\n\\n21 = einundzwanzig (واحد وعشرون)\\n22 = zweiundzwanzig (اثنان وعشرون)\\n35 = fünfunddreißig (خمسة وثلاثون)\\n47 = siebenundvierzig (سبعة وأربعون)\\n\\nالنمط: آحاد + und + عشرات.\\nتُكتب ككلمة واحدة.",
  "Old English used the same structure: 'one and twenty' appears in Shakespeare and older texts. Most Germanic languages historically put the smaller number first. English switched to the modern 'twenty-one' order but German kept the old pattern. Dutch also says 'eenentwintig.' Once you get the rhythm, it becomes automatic.": "اللغة الإنجليزية القديمة استخدمت نفس الترتيب. معظم اللغات الجرمانية تاريخياً وضعت الرقم الأصغر أولاً. الإنجليزية تحولت إلى ترتيب twenty-one الحديث لكن الألمانية حافظت على النمط القديم. الهولندية أيضاً تقول eenentwintig. هذا الترتيب مألوف جداً في العربية، فنقول \"واحد وعشرون\" تماماً كالألمانية.",
  "the color": "اللون",
  "Feminine. Colors as adjectives are lowercase: rot, blau, grün.": "مؤنث. الألوان كصفات تُكتب بحرف صغير: rot، blau، grün.",
  "A: Which color?\\nB: Red!": "A: أي لون؟\\nB: أحمر!",
  "German color words don't capitalize unless they are nouns (das Rot). As adjectives: always lowercase.": "ألوان الألمانية لا تُكتب بحرف كبير إلا إذا كانت أسماء (das Rot). كصفات: دائماً بحرف صغير.",
  "red / blue / green / yellow": "أحمر / أزرق / أخضر / أصفر",
  "Basic colors. Used as adjectives (no ending when predicative).": "ألوان أساسية. تُستخدم كصفات (بدون نهاية عند استخدامها كخبر).",
  "A: The apple is red.\\nB: The banana is yellow.": "A: التفاحة حمراء.\\nB: الموزة صفراء.",
  "Rot, blau, grün, gelb: four primary colors every child learns first. 'Grün hinter den Ohren' (green behind the ears) = naive/inexperienced.": "rot، blau، grün، gelb: أربعة ألوان أساسية يتعلمها كل طفل أولاً. التعبير Grün hinter den Ohren (أخضر خلف الأذنين) = ساذج أو قليل الخبرة.",
  "black / white / brown / grey": "أسود / أبيض / بني / رمادي",
  "More colors. Schwarz and weiß are common in compound nouns.": "ألوان إضافية. schwarz وweiß شائعتان في الأسماء المركبة.",
  "A: Black or white?\\nB: Grey!": "A: أسود أم أبيض؟\\nB: رمادي!",
  "Schwarzbrot (black bread), Weißwurst (white sausage), Braunschweig (city name!). Colors build food compounds.": "Schwarzbrot (خبز أسود)، Weißwurst (نقانق بيضاء)، Braunschweig (اسم مدينة!). الألوان تبني كلمات مركبة للطعام.",
  "gram / kilogram": "غرام / كيلوغرام",
  "Both neuter. Stay singular with numbers: 500 Gramm, never Gramme.": "كلاهما محايد. يبقيان مفردين مع الأرقام: 500 Gramm، ولا يُقال أبداً Gramme.",
  "At the Fleischtheke (deli counter), you order by Gramm. '200 Gramm Schinken' is the magic phrase. Never say 'Gramme.'": "عند طاولة اللحوم Fleischtheke، تطلب بالغرام. عبارة 200 Gramm Schinken هي العبارة السحرية. لا تقل أبداً Gramme.",
  "the pound (500g in Germany!)": "الرطل (500 غرام في ألمانيا!)",
  "Neuter. German Pfund = 500g, NOT 454g like English pound!": "محايد. الرطل الألماني Pfund = 500 غرام، وليس 454 غرام مثل الباوند الإنجليزي!",
  "A: Half a pound of butter.\\nB: And a liter of milk?": "A: نصف رطل زبدة.\\nB: ولتر حليب؟",
  "Pfund = 500g in Germany. Not 454g like the English pound. Metric country! 'Ein halbes Pfund' = 250g.": "Pfund = 500 غرام في ألمانيا. وليس 454 غرام مثل الباوند الإنجليزي. بلد متري! عبارة ein halbes Pfund = 250 غرام.",
  "liter / meter": "لتر / متر",
  "Both masculine. Germany went metric in 1872.": "كلاهما مذكر. ألمانيا تحولت إلى النظام المتري عام 1872.",
  "A: A hundred centimeters is one meter.\\nB: And a thousand meters is one kilometer.": "A: مئة سنتيمتر تساوي متراً واحداً.\\nB: وألف متر تساوي كيلومتراً واحداً.",
  "number / size / weight": "رقم / مقاس / وزن",
  "Three essential measurement words.": "ثلاث كلمات قياس أساسية.",
  "A: Which number?\\nB: Number fifty.": "A: أي رقم؟\\nB: رقم خمسين.",
  "At the bakery counter you MUST take a number (Nummer ziehen). No number = no service. Germans queue by number, not by standing in line.": "عند طاولة المخبز يجب أن تأخذ رقماً (Nummer ziehen). بدون رقم = بدون خدمة. الألمان ينتظرون بالأرقام، لا بالوقوف في صف.",
  "half / quarter / approximately": "نصف / ربع / تقريباً",
  "'Halb' = half. 'Viertel' = quarter. 'Zirka' = about.": "halb = نصف. Viertel = ربع. zirka = تقريباً.",
  "A: About one hour.\\nB: A quarter is enough.": "A: حوالي ساعة.\\nB: ربع ساعة يكفي.",
  "'Viertel nach drei' = quarter past three. 'Halb vier' = half TO four (= 3:30!). This German clock trap catches everyone.": "Viertel nach drei = الثالثة والربع. halb vier = النصف إلى الأربعة (= 3:30!). فخ الساعة الألماني يصطاد الجميع.",
  "German says the ones digit first, then 'und', then tens.": "الألمانية تقول رقم الآحاد أولاً، ثم und، ثم العشرات.",
  "Break the compound number into its parts: hundreds first, then tens and ones.": "قسّم الرقم المركب إلى أجزائه: المئات أولاً، ثم العشرات والآحاد.",
  "Which unit measures weight for deli items?": "ما وحدة الوزن المستخدمة لطلب اللحوم والأجبان؟",
  "Two hundred grams of ham, please.": "مئتا غرام من الشينكن من فضلك.",
  "Zirka means approximately.": "zirka تعني تقريباً.",
  "You want 250g, which is half of a Pfund.": "تريد 250 غرام، وهي نصف Pfund.",
  "A half pound of butter, please.": "نصف رطل زبدة من فضلك.",
  "Think of a cloudy winter sky in Berlin.": "فكّر بسماء شتوية ملبّدة بالغيوم في برلين.",
  "the hour": "الساعة",
  "Feminine. Plural: die Stunden. Eine halbe Stunde = half an hour.": "مؤنث. الجمع: die Stunden. عبارة eine halbe Stunde = نصف ساعة.",
  "A: How long does it take?\\nB: About one hour.": "A: كم يستغرق الأمر؟\\nB: حوالي ساعة واحدة.",
  "Stunde comes from Old High German for a fixed point in time. Use Stunde for duration (one hour). Use Uhr for clock time: Es ist drei Uhr = It is three o'clock.": "Stunde تأتي من الألمانية العليا القديمة وتعني نقطة ثابتة في الزمن. استخدم Stunde للمدة (ساعة واحدة). استخدم Uhr لوقت الساعة: Es ist drei Uhr = الساعة الثالثة.",
  "The small coin denomination after Euro.": "العملة المعدنية الصغيرة بعد اليورو.",
  "The bread costs three euros fifty cents.": "الخبز يكلف ثلاثة يورو وخمسين سنتاً.",
  "The scale by the bananas. Verumius puts them on. A screen with a hundred pictures. He presses broccoli. The bananas now cost 0.49 euros per kilo. That is wrong. Very wrong.": "الميزان بجانب الموز. فيروميوس يضعه عليه. شاشة بمئة صورة. يضغط على البروكلي. الموز الآن يكلف 0.49 يورو للكيلو. هذا خطأ. خطأ كبير.",
  "The accusative case changes ONE article: der becomes den. That's it. One gender, one change. But it changes everything about how you shop.": "حالة النصب (Akkusativ) تغيّر أداة تعريف واحدة: der تصبح den. هذا كل شيء. جنس واحد، تغيير واحد. لكنه يغيّر كل شيء في طريقة تسوقك.",
  "Accusative case (den/einen)": "حالة النصب Akkusativ (den/einen)",
  "Negative article kein": "أداة النفي kein",
  "nicht vs kein distinction": "الفرق بين nicht وkein",
  "Aisle three. Milk, butter, cheese, yogurt. Everything has articles. Der Käse. Die Butter. Das Joghurt. Verumius thinks: Why does cheese have a gender?": "الممر الثالث. حليب، زبدة، جبن، لبن. كل شيء له أداة تعريف. Der Käse. Die Butter. Das Joghurt. فيروميوس يفكر: لماذا للجبن جنس نحوي؟",
  "expensive": "غالٍ",
  "Adjective. Opposite: billig (cheap). Better word: günstig (good value).": "صفة. العكس: billig (رخيص). كلمة أفضل: günstig (بسعر مناسب).",
  "A: That is expensive!\\nB: No, that is good value.": "A: هذا غالٍ!\\nB: لا، هذا بسعر مناسب.",
  "'Günstig' does not mean cheap. It means good value. Germans make this distinction seriously. Billig = cheap (negative). Günstig = well-priced (positive).": "günstig لا تعني رخيص. تعني بسعر مناسب. الألمان يأخذون هذا الفرق بجدية. billig = رخيص (سلبي). günstig = بسعر جيد (إيجابي).",
  "much / little / more": "كثير / قليل / أكثر",
  "Viel = much/many. Wenig = little/few. Mehr = more (comparative).": "viel = كثير. wenig = قليل. mehr = أكثر (صيغة التفضيل).",
  "A: I need more milk.\\nB: We don't have much.": "A: أحتاج مزيداً من الحليب.\\nB: ليس لدينا كثير.",
  "'Mehr' never declines. No endings, ever. 'Die meisten Leute' = most people. Meist is the superlative of viel.": "mehr لا تتصرف أبداً. لا نهايات، أبداً. عبارة die meisten Leute = معظم الناس. Meist هي صيغة التفضيل العليا لـ viel.",
  "The direct object case. What changes?\\n\\nder becomes den (masculine ONLY)\\nein becomes einen (masculine ONLY)\\ndie / das / eine / ein(neut) = NO CHANGE\\n\\nNominative: Der Apfel ist rot.\\nAccusative: Ich kaufe den Apfel.\\n\\nOnly masculine changes. Everything else stays the same.\\nThis is the easiest German case.": "حالة المفعول به المباشر. ماذا يتغير؟\\n\\nder تصبح den (المذكر فقط)\\nein تصبح einen (المذكر فقط)\\ndie / das / eine / ein (المحايد) = لا تغيير\\n\\nالرفع: Der Apfel ist rot.\\nالنصب: Ich kaufe den Apfel.\\n\\nالمذكر فقط يتغير. كل شيء آخر يبقى كما هو.\\nهذه أسهل حالة إعراب ألمانية.",
  "In Old High German, all three genders had distinct accusative forms. Over centuries, the feminine and neuter accusative forms merged with the nominative. Only the masculine kept its distinct accusative: the -en ending (den, einen).\\n\\nThis is actually helpful: you only need to learn ONE change. If the noun is masculine, add -en to the article. If not, nothing changes.": "في الألمانية العليا القديمة، كانت الأجناس الثلاثة تملك صيغ نصب مختلفة. عبر القرون، اندمجت صيغ النصب للمؤنث والمحايد مع صيغ الرفع. المذكر وحده احتفظ بصيغة نصب مميزة: النهاية en- (مثل den، einen).\\n\\nهذا مفيد فعلاً: تحتاج فقط لتعلم تغيير واحد. إذا كان الاسم مذكراً، أضف en- للأداة. إن لم يكن مذكراً، لا شيء يتغير.",
  "the / a (masculine accusative)": "أداة التعريف / التنكير (مذكر منصوب)",
  "Masculine accusative: der to den, ein to einen.": "المذكر المنصوب: der تصبح den، ein تصبح einen.",
  "A: I am buying the apple.\\nB: And I am taking a cake.": "A: أشتري التفاحة.\\nB: وأنا آخذ كعكة.",
  "Only ONE gender changes in accusative. Masculine gets an extra -en. Die and das? Lazy. No change.": "جنس واحد فقط يتغير في النصب. المذكر يحصل على en- إضافية. die وdas؟ كسولتان. لا تغيير.",
  "him, it (masculine accusative)": "إياه (ضمير المذكر المنصوب)",
  "Accusative form of er (he/it).\\nUse ihn when the masculine noun is the direct object.": "صيغة النصب لـ er (هو).\\nاستخدم ihn عندما يكون الاسم المذكر مفعولاً به مباشراً.",
  "A: Do you see the apple?\\nB: Yes, I am buying it!": "A: هل ترى التفاحة؟\\nB: نعم، أشتريها!",
  "Ihn replaces den + noun in the accusative. Der Apfel becomes er (subject) or ihn (object). This mirrors English he/him exactly.": "ihn تحلّ محل den + الاسم في النصب. Der Apfel يصبح er (فاعل) أو ihn (مفعول به). هذا يشبه تماماً he/him في الإنجليزية، أو هو/إياه في العربية.",
  "Fisch is masculine. Direct object = accusative case. What form?": "Fisch مذكر. المفعول به المباشر = حالة النصب. ما الصيغة؟",
  "Apfel is masculine. In accusative, ein becomes...": "Apfel مذكر. في حالة النصب، ein تصبح...",
  "I need an apple.": "أحتاج تفاحة.",
  "Banane is feminine. Feminine does NOT change in accusative.": "Banane مؤنث. المؤنث لا يتغير في حالة النصب.",
  "Brot is neuter. Neuter stays the same in accusative.": "Brot محايد. المحايد يبقى كما هو في حالة النصب.",
  "He buys the bread.": "هو يشتري الخبز.",
  "kein = 'not a' / 'no.' Declines like ein:\\n\\nNom: kein Apfel, keine Banane, kein Brot\\nAcc: keinen Apfel, keine Banane, kein Brot\\n\\nMasculine adds -en in accusative.\\nJust like ein becomes einen.": "kein = \"ليس\" / \"لا يوجد\". تُصرّف مثل ein:\\n\\nالرفع: kein Apfel، keine Banane، kein Brot\\nالنصب: keinen Apfel، keine Banane، kein Brot\\n\\nالمذكر يضيف en- في النصب.\\nتماماً كما ein تصبح einen.",
  "no / not a (negative article)": "لا / ليس (أداة النفي)",
  "Follows ein-pattern. keinen for masculine accusative.": "تتبع نمط ein. صيغة keinen للمذكر المنصوب.",
  "A: Do you have an apple?\\nB: No, I don't have an apple.": "A: هل لديك تفاحة؟\\nB: لا، ليس لديّ تفاحة.",
  "Kein is ein's evil twin. Same endings, opposite meaning. Master ein-endings, and kein is free.": "kein هي التوأم الشرير لـ ein. نفس النهايات، معنى معاكس. أتقن نهايات ein وستحصل على kein مجاناً.",
  "Geld is neuter. You are negating a noun. Which negator for neuter nouns?": "Geld محايد. أنت تنفي اسماً. ما أداة النفي للأسماء المحايدة؟",
  "Milch is feminine. What form does kein take with feminine nouns?": "Milch مؤنث. ما صيغة kein مع الأسماء المؤنثة؟",
  "We have no milk.": "ليس لدينا حليب.",
  "Schinken is masculine. Accusative masculine kein gets -en.": "Schinken مذكر. kein المذكر المنصوب تحصل على en-.",
  "When to use which?\\n\\nKEIN replaces ein/eine before nouns:\\n'Ich habe ein Auto' to 'Ich habe kein Auto'\\n\\nNICHT negates verbs, adjectives, adverbs:\\n'Ich kaufe nicht' / 'Das ist nicht teuer'\\n\\nNICHT goes before what it negates.\\nKEIN goes before the noun.": "متى تستخدم أيّهما؟\\n\\nKEIN تحلّ محل ein/eine قبل الأسماء:\\nIch habe ein Auto تصبح Ich habe kein Auto\\n\\nNICHT تنفي الأفعال والصفات والظروف:\\nIch kaufe nicht / Das ist nicht teuer\\n\\nNICHT تأتي قبل ما تنفيه.\\nKEIN تأتي قبل الاسم.",
  "Is the negated word a noun or an adjective/verb? The negator depends on this.": "هل الكلمة المنفية اسم أم صفة/فعل؟ أداة النفي تعتمد على ذلك.",
  "Negating a neuter noun. Which negative article?": "نفي اسم محايد. ما أداة النفي؟",
  "I am buying no meat.": "لا أشتري لحماً.",
  "First blank negates a neuter noun. Second blank negates the verb itself, not a noun.": "الفراغ الأول ينفي اسماً محايداً. الفراغ الثاني ينفي الفعل نفسه، وليس اسماً.",
  "I have no money and am not shopping.": "ليس لديّ مال ولا أتسوق.",
  "Eier is plural. What ending does the noun-negator need for plural?": "Eier جمع. ما النهاية التي تحتاجها أداة نفي الأسماء في الجمع؟",
  "Negating the adjective 'billig', not a noun.": "نفي الصفة billig، وليس اسماً.",
  "The tomatoes are not cheap.": "الطماطم ليست رخيصة.",
  "First: masculine noun accusative. Second: negating adjective.": "الأول: اسم مذكر منصوب. الثاني: نفي صفة.",
  "I am buying no fish. The fish is not affordable.": "لا أشتري سمكاً. السمك ليس بسعر مناسب.",
  "Kreditkarte is feminine. What ending does the noun-negator need?": "Kreditkarte مؤنث. ما النهاية التي تحتاجها أداة نفي الأسماء؟",
  "I need den Käse. Not der Käse. DEN Käse. Accusative. Yilmaz said that. I buy den Käse. I buy die Milch. I buy... das... Joghurt?": "أحتاج den Käse. ليس der Käse. بل DEN Käse. حالة النصب. يلماز قال ذلك. أشتري den Käse. أشتري die Milch. أشتري... das... Joghurt؟",
  "Five prepositions that ALWAYS take accusative. Plus demonstrative articles and the imperative. Grammar-heavy, but you already know the accusative.": "خمسة حروف جر تأخذ دائماً حالة النصب. بالإضافة إلى أدوات الإشارة وصيغة الأمر. كثافة نحوية عالية، لكنك تعرف النصب بالفعل.",
  "5 accusative prepositions (DOGFU)": "5 حروف جر مع النصب (DOGFU)",
  "Demonstrative articles: dieser/jeder": "أدوات الإشارة: dieser/jeder",
  "Basic imperative commands": "أوامر الأمر الأساسية",
  "I am looking for the flour. Without a plan, without a map. Against all logic: the flour is not with the baked goods. It is with the canned goods. Why?": "أبحث عن الطحين. بدون خطة، بدون خريطة. ضد كل منطق: الطحين ليس مع المخبوزات. إنه مع المعلبات. لماذا؟",
  "Preposition. Always takes accusative.": "حرف جر. يأخذ دائماً حالة النصب.",
  "A: Food without meat?\\nB: Yes, without meat, please.": "A: طعام بدون لحم؟\\nB: نعم، بدون لحم من فضلك.",
  "'Ohne mich!' = Count me out! Always takes accusative. Ohne einen Euro = without a euro.": "!Ohne mich = لا تعدّني! يأخذ دائماً حالة النصب. Ohne einen Euro = بدون يورو واحد.",
  "Irregular: ich bitte, du bittest. 'Bitten um' = ask for.": "غير منتظم: ich bitte، du bittest. التعبير bitten um = يطلب.",
  "A: I am asking for help.\\nB: Of course!": "A: أطلب المساعدة.\\nB: بالطبع!",
  "'Bitten um' always takes accusative. 'Bitte' (please) comes from this verb. The most polite word in German has aggressive grammar.": "bitten um يأخذ دائماً حالة النصب. كلمة Bitte (من فضلك) تأتي من هذا الفعل. أكثر كلمة مهذبة في الألمانية لها قواعد نحوية شرسة.",
  "A: Are you giving me the apple?\\nB: Yes, I am giving you the apple.": "A: هل تعطيني التفاحة؟\\nB: نعم، أعطيك التفاحة.",
  "'Geben' takes dative for the person and accusative for the thing. For now, focus on the accusative object: den Apfel, die Milch, das Brot.": "geben يأخذ حالة الجر (Dativ) للشخص وحالة النصب (Akkusativ) للشيء. الآن ركّز على المفعول به المنصوب: den Apfel، die Milch، das Brot.",
  "Five prepositions ALWAYS take accusative:\\n\\nDurch (through): durch den Laden\\nOhne (without): ohne einen Euro\\nGegen (against): gegen den Preis\\nFür (for): für die Familie\\nUm (around): um die Ecke\\n\\nMnemonic: DOGFU.\\nOnly masculine changes: den/einen.": "خمسة حروف جر تأخذ دائماً حالة النصب:\\n\\ndurch (عبر): durch den Laden\\nohne (بدون): ohne einen Euro\\ngegen (ضد): gegen den Preis\\nfür (لأجل): für die Familie\\num (حول): um die Ecke\\n\\nوسيلة تذكّر: DOGFU.\\nالمذكر فقط يتغير: den/einen.",
  "Kundin is feminine. Feminine doesn't change in accusative.": "Kundin مؤنث. المؤنث لا يتغير في حالة النصب.",
  "'Durch' always demands the same case. Apply it to a masculine noun.": "durch تتطلب دائماً نفس الحالة. طبّقها على اسم مذكر.",
  "I walk through the store.": "أمشي عبر المتجر.",
  "the milk": "الحليب",
  "A: Coffee with milk?\\nB: No, without milk, please.": "A: قهوة مع حليب؟\\nB: لا، بدون حليب من فضلك.",
  "Vollmilch (whole milk), fettarme Milch (low-fat), Magermilch (skim). The cap color at the supermarket tells you which type.": "Vollmilch (حليب كامل الدسم)، fettarme Milch (قليل الدسم)، Magermilch (منزوع الدسم). لون الغطاء في السوبرماركت يخبرك بالنوع.",
  "After ohne, no article needed when speaking generally about a substance.": "بعد ohne لا حاجة لأداة عند الحديث عموماً عن مادة.",
  "Verkäufer is masculine. Für always takes accusative.": "Verkäufer مذكر. für تأخذ دائماً حالة النصب.",
  "That is for the salesperson.": "هذا للبائع.",
  "dieser/jeder/welcher decline like der/die/das:\\n\\nMasc nom: dieser, jeder, welcher\\nMasc acc: diesen, jeden, welchen\\nFem: diese, jede, welche (no change nom/acc)\\nNeut: dieses, jedes, welches (no change nom/acc)\\nPlural: diese, alle, welche": "dieser/jeder/welcher تُصرّف مثل der/die/das:\\n\\nمذكر رفع: dieser، jeder، welcher\\nمذكر نصب: diesen، jeden، welchen\\nمؤنث: diese، jede، welche (لا تغيير رفع/نصب)\\nمحايد: dieses، jedes، welches (لا تغيير رفع/نصب)\\nجمع: diese، alle، welche",
  "Dieser (this/these) mirrors der/die/das endings exactly. The trick: replace der/die/das with dies- and keep the same ending.\\n\\nder Mantel becomes dieser Mantel\\ndie Hose becomes diese Hose\\ndas Hemd becomes dieses Hemd\\n\\nIn accusative, only masculine changes: dieser becomes diesen, just like der becomes den.\\n\\nThe same pattern applies to jeder (every) and welcher (which). Learn one set of endings, and you know all three.": "dieser (هذا/هذه) تعكس نهايات der/die/das بالضبط. الحيلة: استبدل der/die/das بـ dies- وأبقِ نفس النهاية.\\n\\nder Mantel تصبح dieser Mantel\\ndie Hose تصبح diese Hose\\ndas Hemd تصبح dieses Hemd\\n\\nفي النصب، المذكر فقط يتغير: dieser تصبح diesen، تماماً كما der تصبح den.\\n\\nنفس النمط ينطبق على jeder (كل) وwelcher (أي). تعلّم مجموعة نهايات واحدة وستعرف الثلاث.",
  "'Was für' + ein-word. The ein-part declines normally.": "تعبير was für + كلمة ein. جزء ein يُصرّف بشكل طبيعي.",
  "A: What kind of cake would you like?\\nB: A chocolate cake!": "A: أي نوع كعكة تريد؟\\nB: كعكة شوكولاتة!",
  "'Was für ein' = what kind of. Masculine acc: was für einen. Feminine: was für eine. Neuter: was für ein.": "was für ein = أي نوع. مذكر منصوب: was für einen. مؤنث: was für eine. محايد: was für ein.",
  "Apfel is masculine, direct object (accusative). Welch- + masc acc = -en.": "Apfel مذكر، مفعول به (منصوب). welch- + مذكر منصوب = نهاية en-.",
  "Flasche is feminine. It is the direct object here. Check the dieser-word endings chart for this combination.": "Flasche مؤنث. وهي المفعول به هنا. راجع جدول نهايات dieser لهذا التركيب.",
  "I am buying this bottle.": "أشتري هذه الزجاجة.",
  "Brot is neuter, nominative. Think about the dieser-word endings chart.": "Brot محايد، مرفوع. فكّر في جدول نهايات dieser.",
  "Kuchen is masculine, direct object (accusative). Masculine accusative ending?": "Kuchen مذكر، مفعول به (منصوب). ما نهاية المذكر المنصوب؟",
  "I will take this cake.": "سآخذ هذه الكعكة.",
  "Giving commands in German:\\n\\ndu-form: verb stem: Kauf! Nimm! Gib!\\nihr-form: same as ihr-present: Kauft! Nehmt!\\nSie-form: infinitive + Sie: Kaufen Sie! Nehmen Sie!\\n\\nSeparable verbs split: Kauf ein! Kaufen Sie ein!\\nSie-form is the polite one. Always use it with strangers.": "إعطاء الأوامر في الألمانية:\\n\\nصيغة du: جذع الفعل: !Kauf !Nimm !Gib\\nصيغة ihr: مثل المضارع مع ihr: !Kauft !Nehmt\\nصيغة Sie: المصدر + Sie: !Kaufen Sie !Nehmen Sie\\n\\nالأفعال المنفصلة تنقسم: !Kauf ein !Kaufen Sie ein\\nصيغة Sie هي المهذبة. استخدمها دائماً مع الغرباء.",
  "Polite imperative uses the Sie-form: infinitive + Sie.": "صيغة الأمر المهذبة تستخدم صيغة Sie: المصدر + Sie.",
  "Informal du-command. What is the imperative stem of nehmen?": "أمر غير رسمي بصيغة du. ما جذع الأمر لفعل nehmen؟",
  "Take the apple!": "خذ التفاحة!",
  "Polite command = infinitive + Sie.": "الأمر المهذب = المصدر + Sie.",
  "Polite imperative of the verb meaning 'to walk' + a directional prefix.": "صيغة أمر مهذبة للفعل بمعنى \"يمشي\" + سابقة اتجاهية.",
  "Go through the store!": "امشِ عبر المتجر!",
  "Kundin is feminine. Accusative feminine = no change.": "Kundin مؤنث. المؤنث المنصوب = لا تغيير.",
  "Euro is masculine. Ohne requires accusative. How does ein change for masc acc?": "Euro مذكر. ohne تتطلب حالة النصب. كيف تتغير ein في المذكر المنصوب؟",
  "Without a euro nothing works.": "بدون يورو لا شيء يعمل.",
  "Polite imperative. Kreditkarte is fem (die). Einkauf is masc acc (den).": "صيغة أمر مهذبة. Kreditkarte مؤنث (die). Einkauf مذكر منصوب (den).",
  "Take the credit card for the purchase!": "خذ بطاقة الائتمان للشراء!",
  "Brot is neuter. Accusative neuter ein = no change.": "Brot محايد. ein المحايد في حالة النصب = لا تغيير."
};
