/**
 * Unit 02 — Final sweep: all 257 remaining [AR] markers
 * Arabic translations (MSA, native-speaker quality)
 */
module.exports = {
// funFacts
"In old Germanic tradition, 'links' was considered the unlucky side. Left-handers were once forced to switch hands. The word is related to 'link' (sly/cunning).": "في التراث الجرماني القديم، كانت 'links' تُعتبر الجهة المشؤومة. كان يُجبر الأشخاص الذين يستخدمون اليد اليسرى على التبديل. الكلمة مرتبطة بـ 'link' (ماكر/خبيث).",
"German builds dozens of compounds from Stadt: Innenstadt (city center), Stadtplan (city map), Hauptstadt (capital city), Altstadt (old town), Stadtrat (city council). Learn Stadt and you unlock them all.": "الألمانية تبني عشرات المركبات من Stadt: Innenstadt (وسط المدينة)، Stadtplan (خريطة المدينة)، Hauptstadt (العاصمة)، Altstadt (المدينة القديمة)، Stadtrat (مجلس المدينة). تعلّم Stadt وستفتح بابها جميعًا.",
"Deutsche Post (German Post) was founded in 1490 as a royal mail service. The yellow color of German postboxes and Post offices dates back to the Prussian era.": "تأسس البريد الألماني (Deutsche Post) عام ١٤٩٠ كخدمة بريد ملكية. اللون الأصفر لصناديق البريد ومكاتبه يعود إلى العصر البروسي.",
"S-Bahn runs above ground through the city. Berlin's S-Bahn ring circles the center. Together with U-Bahn, it forms one of Europe's best transit networks.": "S-Bahn تسير فوق الأرض عبر المدينة. حلقة S-Bahn في برلين تدور حول المركز. مع U-Bahn تشكّلان واحدة من أفضل شبكات النقل في أوروبا.",
"One of German's most common irregular verbs. 'Auf Wiedersehen' literally means 'until seeing again.' The stem change e→ie applies in du and er/sie/es forms only.": "من أكثر الأفعال الشاذة شيوعًا في الألمانية. 'Auf Wiedersehen' تعني حرفيًا 'حتى نلتقي مجددًا'. تغيّر الجذع e→ie يسري في صيغتي du و er/sie/es فقط.",
"In Germany, crossing on a red light is genuinely frowned upon, especially if children are watching. You might get a lecture from a complete stranger. It is not law enforcement people fear. It is social judgment. Verumius learned this the hard way.": "في ألمانيا، عبور الشارع على الضوء الأحمر مستهجن فعلًا، خاصة إذا كان أطفال يراقبون. قد يوبخك شخص غريب تمامًا. ليس الخوف من الشرطة، بل من الحكم الاجتماعي. تعلّم Verumius هذا بالطريقة الصعبة.",
"Two meanings! Context tells you which.": "معنيان! السياق يحدد أيهما المقصود.",
"Regular verb. Spielplatz = playground.": "فعل منتظم. Spielplatz = ملعب أطفال.",
"Regular pattern. Fußball spielen = to play football.": "نمط منتظم. Fußball spielen = لعب كرة القدم.",
"State verb: already sitting. Setzen = to sit down (action).": "فعل حالة: جالس بالفعل. setzen = يجلس (فعل الحركة).",
"State verb. Legen = to lay/put (action).": "فعل حالة. legen = يضع/يمدّ (فعل الحركة).",
"Masculine noun. 'Das macht Spaß!' = That is fun!": "اسم مذكر. '!Das macht Spaß' = هذا ممتع!",
"FALSE FRIEND! Not 'to become'!": "صديق زائف! لا تعني 'يصبح'!",
"Masculine noun. Berlin's river: die Spree.": "اسم مذكر. نهر برلين: die Spree.",
"Feminine noun. 'Sonnenschein' = sunshine.": "اسم مؤنث. 'Sonnenschein' = أشعة الشمس.",
"Masculine noun. But die See = the sea!": "اسم مذكر. لكن die See = البحر!",
"Irregular. Past: flog.": "شاذ. الماضي: flog.",
"The thing you like is the SUBJECT. Dative construction.": "الشيء الذي يعجبك هو الفاعل. تركيب مع حالة الجر (Dativ).",
"Irregular. Past participle: geschlossen.": "شاذ. اسم المفعول: geschlossen.",
"Added after a verb to mean 'like doing.'": "يُضاف بعد الفعل بمعنى 'يحب فعل شيء'.",
"Adverb. Used constantly in German.": "ظرف. يُستخدم باستمرار في الألمانية.",
"Irregular past (trank), but regular present.": "ماضٍ شاذ (trank)، لكن المضارع منتظم.",
"Regular in present tense. Was trinken Sie? = What are you drinking?": "منتظم في المضارع. ?Was trinken Sie = ماذا تشرب؟",
"Regular verb. Ich brauche, du brauchst, er braucht.": "فعل منتظم. ich brauche, du brauchst, er braucht.",
"ONLY follows nicht/kein. Corrects a negative.": "تأتي فقط بعد nicht/kein. تصحّح النفي.",
"Feminine noun. From Greek via French.": "اسم مؤنث. من اليونانية عبر الفرنسية.",
"Feminine noun. More formal than 'Ding.'": "اسم مؤنث. أكثر رسمية من 'Ding'.",
"Colloquial form of 'gerade'. Very common in spoken German.": "صيغة عامية من 'gerade'. شائعة جدًا في الألمانية المحكية.",
"Masculine noun. Plural: die Blicke.": "اسم مذكر. الجمع: die Blicke.",
"Feminine noun. Plural: die Hilfen.": "اسم مؤنث. الجمع: die Hilfen.",
"Feminine noun. Plural: die Ansagen. An + Sage (saying).": "اسم مؤنث. الجمع: die Ansagen. تتكون من An + Sage (قول).",
"Feminine noun. Plural: die Auskünfte. Aus (out) + Kunft (coming).": "اسم مؤنث. الجمع: die Auskünfte. تتكون من Aus (خارج) + Kunft (قدوم).",
"Neuter noun. Plural: die Beispiele. Bei (by) + Spiel (play).": "اسم محايد. الجمع: die Beispiele. تتكون من Bei (عند) + Spiel (لعب).",
"Feminine noun. Plural: die Durchsagen. Durch (through) + Sage (saying).": "اسم مؤنث. الجمع: die Durchsagen. تتكون من Durch (عبر) + Sage (قول).",
"Neuter noun. Plural: die Schilder.": "اسم محايد. الجمع: die Schilder.",
"Feminine noun. No common plural. Vor (before) + Sicht (sight).": "اسم مؤنث. لا جمع شائع. تتكون من Vor (قبل) + Sicht (رؤية).",
"Neuter noun. Plural: die Meere.": "اسم محايد. الجمع: die Meere.",
"Masculine noun! Plural: die Seen. Not the same as 'die See' (the sea).": "اسم مذكر! الجمع: die Seen. ليست نفس 'die See' (البحر).",
"Masculine noun. Plural: die Ausflüge. Aus (out) + Flug (flight).": "اسم مذكر. الجمع: die Ausflüge. تتكون من Aus (خارج) + Flug (طيران).",
"Neuter noun. Plural: die Fotos.": "اسم محايد. الجمع: die Fotos.",
"Feminine noun. Plural: die Führungen. From führen (to lead).": "اسم مؤنث. الجمع: die Führungen. من führen (يقود).",
"Feminine noun. Plural: die Karten. Context determines meaning.": "اسم مؤنث. الجمع: die Karten. السياق يحدد المعنى.",
"Masculine noun. Plural: die Prospekte.": "اسم مذكر. الجمع: die Prospekte.",
"Neuter noun. Plural: die Reisebüros. Reise (travel) + Büro (office).": "اسم محايد. الجمع: die Reisebüros. تتكون من Reise (سفر) + Büro (مكتب).",
"Masculine noun. Plural: die Reiseführer. Reise (travel) + Führer (guide).": "اسم مذكر. الجمع: die Reiseführer. تتكون من Reise (سفر) + Führer (مرشد).",
"Pronoun/adjective. Changes form: der andere, die andere, das andere.": "ضمير/صفة. يتغير شكله: der andere، die andere، das andere.",
"Pronoun. The neuter form of 'all'. Alles klar? = All clear?": "ضمير. الصيغة المحايدة من 'all'. ?Alles klar = كل شيء واضح؟",
"Masculine noun. Ein (in) + Tritt (step). Admission fee: der Eintrittspreis.": "اسم مذكر. تتكون من Ein (دخول) + Tritt (خطوة). رسم الدخول: der Eintrittspreis.",

// notes (short)
"Irregular: ich fahre, du fährst, er fährt.": "شاذ: ich fahre, du fährst, er fährt.",
"Vowel change a to ä in du and er/sie/es forms. Common with all transport verbs.": "تغيّر حرف العلة a إلى ä في صيغتي du و er/sie/es. شائع مع جميع أفعال النقل.",
"Double change: e → i AND h → mm. One of German's most irregular common verbs.": "تغيّر مزدوج: e → i و h → mm. من أكثر الأفعال الشاذة الشائعة في الألمانية.",
"Irregular: ich laufe, du läufst, er läuft.": "شاذ: ich laufe, du läufst, er läuft.",
"au → äu in du/er forms. Northern Germany: walk. Southern Germany: run.": "au → äu في صيغتي du/er. شمال ألمانيا: يمشي. جنوب ألمانيا: يركض.",
"Separable: Steigen Sie ein!": "فعل منفصل: !Steigen Sie ein",
"Separable: Bitte aussteigen!": "فعل منفصل: !Bitte aussteigen",
"Separable: Sie müssen umsteigen.": "فعل منفصل: .Sie müssen umsteigen",
"Separable: Der Zug fährt um 10 Uhr ab.": "فعل منفصل: .Der Zug fährt um 10 Uhr ab",
"Separable: Wann kommen Sie an?": "فعل منفصل: ?Wann kommen Sie an",
"Inseparable prefix verb. Be- verbs never separate.": "فعل بسابقة غير منفصلة. أفعال Be- لا تنفصل أبدًا.",
"Adjective. Opposite: schmal (narrow).": "صفة. العكس: schmal (ضيّق).",
"Feminine noun. Plural: die Bäckereien.": "اسم مؤنث. الجمع: die Bäckereien.",
"Masculine noun. Plural: die Bahnsteige. Bahn (railway) + Steig (path).": "اسم مذكر. الجمع: die Bahnsteige. تتكون من Bahn (سكة حديدية) + Steig (ممر).",
"Masculine noun. Plural: die Ausgänge. Aus (out) + Gang (way).": "اسم مذكر. الجمع: die Ausgänge. تتكون من Aus (خارج) + Gang (ممر).",
"Masculine noun. Plural: die Eingänge. Ein (in) + Gang (way).": "اسم مذكر. الجمع: die Eingänge. تتكون من Ein (داخل) + Gang (ممر).",
"Neuter noun. Plural: die Geschäfte.": "اسم محايد. الجمع: die Geschäfte.",
"Feminine noun. Plural: die Haltestellen. Halte (hold/stop) + Stelle (place).": "اسم مؤنث. الجمع: die Haltestellen. تتكون من Halte (توقف) + Stelle (مكان).",
"Masculine noun. Plural: die Kindergärten. Kinder (children) + Garten (garden).": "اسم مذكر. الجمع: die Kindergärten. تتكون من Kinder (أطفال) + Garten (حديقة).",
"Masculine noun. Plural: die Kioske.": "اسم مذكر. الجمع: die Kioske.",
"Masculine noun. Plural: die Läden. More casual than Geschäft.": "اسم مذكر. الجمع: die Läden. أقل رسمية من Geschäft.",
"Neuter noun. Plural: die Lokale. A casual place to eat or drink.": "اسم محايد. الجمع: die Lokale. مكان غير رسمي للأكل أو الشرب.",
"Masculine noun. Plural: die Orte.": "اسم مذكر. الجمع: die Orte.",
"Feminine noun. Plural: die Praxen.": "اسم مؤنث. الجمع: die Praxen.",
"Neuter noun. Plural: die Schwimmbäder. Schwimmen (swim) + Bad (bath).": "اسم محايد. الجمع: die Schwimmbäder. تتكون من Schwimmen (سباحة) + Bad (حمّام).",
"Feminine noun. Plural: die Sehenswürdigkeiten. A famously long German word!": "اسم مؤنث. الجمع: die Sehenswürdigkeiten. من أطول الكلمات الألمانية شهرةً!",
"Feminine noun. No common plural form.": "اسم مؤنث. لا يوجد جمع شائع.",
"Feminine noun. Very common in announcements.": "اسم مؤنث. شائعة جدًا في الإعلانات.",
"Feminine noun. Plural: die Informationen. Also an information desk.": "اسم مؤنث. الجمع: die Informationen. تعني أيضًا مكتب الاستعلامات.",
"Masculine noun. Plural: die Anschlüsse. A connecting train or bus.": "اسم مذكر. الجمع: die Anschlüsse. قطار أو حافلة ربط.",
"Feminine noun. Plural: die Autobahnen. Auto (car) + Bahn (way).": "اسم مؤنث. الجمع: die Autobahnen. تتكون من Auto (سيارة) + Bahn (طريق).",
"Feminine noun. Plural: die Bahnen. Short for Eisenbahn (iron way).": "اسم مؤنث. الجمع: die Bahnen. اختصار لـ Eisenbahn (طريق الحديد).",
"Masculine noun. Plural: die Fahrer. From fahren (to drive).": "اسم مذكر. الجمع: die Fahrer. من fahren (يقود).",
"Neuter noun. Plural: die Fahrräder. Fahr (drive/ride) + Rad (wheel).": "اسم محايد. الجمع: die Fahrräder. تتكون من Fahr (قيادة) + Rad (عجلة).",
"Neuter noun. Plural: die Gleise. Used at train stations.": "اسم محايد. الجمع: die Gleise. تُستخدم في محطات القطار.",
"Masculine noun. Short for Lastkraftwagen (load-power-vehicle).": "اسم مذكر. اختصار لـ Lastkraftwagen (مركبة نقل ثقيلة).",
"Feminine noun. S stands for Schnell (fast) or Stadt (city).": "اسم مؤنث. S تعني Schnell (سريع) أو Stadt (مدينة).",
"Feminine noun. Plural: die Straßenbahnen. Straße (street) + Bahn (way).": "اسم مؤنث. الجمع: die Straßenbahnen. تتكون من Straße (شارع) + Bahn (طريق).",
"Masculine noun. No plural. Direction word.": "اسم مذكر. لا جمع. كلمة اتجاه.",
"Preposition+article contraction. Used for locations and days.": "اختصار حرف جر + أداة تعريف. يُستخدم للأماكن والأيام.",
"Preposition+article contraction. Used with neuter nouns for direction.": "اختصار حرف جر + أداة تعريف. يُستخدم مع الأسماء المحايدة للاتجاه.",
"Adjective/adverb. Describes height or elevation.": "صفة/ظرف. تصف الارتفاع أو العلو.",
"Adjective/adverb. Used for distance. Opposite: nah (near).": "صفة/ظرف. تُستخدم للمسافة. العكس: nah (قريب).",
"Adverb. Very versatile. Used for emphasis and comparison.": "ظرف. متعدد الاستخدامات. يُستخدم للتأكيد والمقارنة.",
"Pronoun/determiner. Changes form: alle (plural), alles (everything).": "ضمير/محدد. يتغير شكله: alle (جمع)، alles (كل شيء).",
"Adverb. Combines da (there) + neben (next to).": "ظرف. يتكون من da (هناك) + neben (بجانب).",
"Preposition. Used for surfaces and specific locations.": "حرف جر. يُستخدم للأسطح والمواقع المحددة.",
"Preposition. Used for horizontal surfaces.": "حرف جر. يُستخدم للأسطح الأفقية.",
"Preposition. Always takes accusative case.": "حرف جر. يأخذ دائمًا حالة النصب (Akkusativ).",
"Preposition. Also used for approximate times: gegen 8 Uhr.": "حرف جر. يُستخدم أيضًا للأوقات التقريبية: gegen 8 Uhr.",
"Preposition. 'Über' also means 'about' a topic.": "حرف جر. 'Über' تعني أيضًا 'حول/عن' موضوع.",
"Preposition. Time: vor einer Stunde (an hour ago). Place: vor dem Haus.": "حرف جر. الزمن: vor einer Stunde (قبل ساعة). المكان: vor dem Haus (أمام المنزل).",
"Preposition. Marks a starting point: ab Montag (from Monday).": "حرف جر. يحدد نقطة البداية: ab Montag (من يوم الاثنين).",
"Adverb of time. Very common in everyday speech.": "ظرف زمان. شائع جدًا في الكلام اليومي.",
"Adverb. Used to sequence events or actions.": "ظرف. يُستخدم لترتيب الأحداث أو الأفعال.",
"Adverb of frequency. Opposite: nie (never).": "ظرف تكرار. العكس: nie (أبدًا).",
"Adverb of time. Emphasizes the present moment.": "ظرف زمان. يؤكد اللحظة الحالية.",
"Adverb of frequency. Opposite: immer (always).": "ظرف تكرار. العكس: immer (دائمًا).",
"Adverb. Context changes meaning: noch = still, noch nicht = not yet.": "ظرف. السياق يغيّر المعنى: noch = لا يزال، noch nicht = ليس بعد.",
"Adverb. Limits or restricts what follows.": "ظرف. يحدّ أو يقيّد ما يليه.",
"Adverb of frequency. Between immer and manchmal.": "ظرف تكرار. بين immer (دائمًا) و manchmal (أحيانًا).",
"Adverb. Can also express surprise or reassurance.": "ظرف. يمكن أن يعبّر أيضًا عن المفاجأة أو الطمأنة.",
"Adverb. Stronger than 'bald' (soon).": "ظرف. أقوى من 'bald' (قريبًا).",
"Adverb. Softens statements and suggestions.": "ظرف. يلطّف العبارات والاقتراحات.",
"Adverb. Indicates repetition.": "ظرف. يشير إلى التكرار.",
"Separable verb: ab + fliegen. Ich fliege morgen ab.": "فعل منفصل: ab + fliegen. .Ich fliege morgen ab",
"Separable verb: ab + holen. Ich hole dich ab.": "فعل منفصل: ab + holen. .Ich hole dich ab",
"Inseparable verb. Wir besichtigen das Schloss.": "فعل غير منفصل. .Wir besichtigen das Schloss",
"Strong verb: er hält. Also used for buses: Der Bus hält hier.": "فعل قوي: er hält. يُستخدم أيضًا للحافلات: .Der Bus hält hier",
"Irregular verb. Ich stehe, du stehst, er steht.": "فعل شاذ. ich stehe, du stehst, er steht.",
"Regular verb. Ich suche, du suchst.": "فعل منتظم. ich suche, du suchst.",
"Regular verb. Ich wandere, du wanderst.": "فعل منتظم. ich wandere, du wanderst.",
"Irregular verb. Ich bleibe, du bleibst. Past: geblieben.": "فعل شاذ. ich bleibe, du bleibst. الماضي: geblieben.",
"Regular verb. Es dauert zwei Stunden.": "فعل منتظم. .Es dauert zwei Stunden",
"Strong verb: er hilft (stem changes e to i). Takes dative.": "فعل قوي: er hilft (تغيّر الجذع e إلى i). يأخذ حالة الجر (Dativ).",
"Strong verb. Ich leihe dir mein Buch. Context determines lend vs. borrow.": "فعل قوي. .Ich leihe dir mein Buch. السياق يحدد إن كانت بمعنى يُعير أو يستعير.",
"Separable verb: mit + kommen. Kommst du mit?": "فعل منفصل: mit + kommen. ?Kommst du mit",
"Regular verb. Ich zeige, du zeigst.": "فعل منتظم. ich zeige, du zeigst.",
"Separable verb: mit + nehmen. Er nimmt mich mit.": "فعل منفصل: mit + nehmen. .Er nimmt mich mit",
"Separable verb: weiter + fahren. Wir fahren weiter.": "فعل منفصل: weiter + fahren. .Wir fahren weiter",
"Separable verb: um + steigen. Sie steigen in Frankfurt um.": "فعل منفصل: um + steigen. .Sie steigen in Frankfurt um",
"Separable: Das Geschäft ist auf. Colloquial for 'offen sein'.": "فعل منفصل: .Das Geschäft ist auf. عامية بمعنى 'أن يكون مفتوحًا'.",
"Neuter noun. Plural: die Dörfer.\\nSmaller than a Stadt (city) and an Ort (town).": "اسم محايد. الجمع: die Dörfer.\\nأصغر من Stadt (مدينة) و Ort (بلدة).",
"Adverb of place. Indicates a higher position.\\nOpposite: unten (below).": "ظرف مكان. يشير إلى موقع أعلى.\\nالعكس: unten (أسفل).",
"Adverb of place. Indicates a lower position.\\nOpposite: oben (above).": "ظرف مكان. يشير إلى موقع أسفل.\\nالعكس: oben (أعلى).",
"Adverb of place. Refers to the back position.\\nOpposite: vorne (in front).": "ظرف مكان. يشير إلى الخلف.\\nالعكس: vorne (في الأمام).",
"Adverb of place. Indicates being outside.\\nOpposite: drinnen (inside).": "ظرف مكان. يشير إلى الخارج.\\nالعكس: drinnen (في الداخل).",
"Draußen and drinnen are perfect opposites. 'Draußen vor der Tür' is the title of a famous German post-war play. Draußen always carries a sense of separation.": "draußen و drinnen متضادان تامان. 'Draußen vor der Tür' عنوان مسرحية ألمانية شهيرة من فترة ما بعد الحرب. draußen تحمل دائمًا إحساسًا بالانفصال.",
"Adverb of place. More specific than da (there).\\nDort drüben = over there.": "ظرف مكان. أكثر تحديدًا من da (هناك).\\nDort drüben = هناك.",
"Dort is more precise than da. Da = there (neutral). Dort = there (at a specific, visible location). 'Dort drüben' means over there and is very common in directions.": "dort أدق من da. da = هناك (محايد). dort = هناك (في مكان محدد مرئي). 'Dort drüben' تعني 'هناك' وشائعة جدًا في الإرشادات.",
"Adverb of direction. Means going back to a previous position.\\nGehen Sie zurück = go back.": "ظرف اتجاه. بمعنى العودة إلى موقع سابق.\\nGehen Sie zurück = ارجع.",
"Zurück is one of the most common German words for travelers. Rückfahrkarte (return ticket) has zurück hidden in Rück-. Hin und zurück = there and back.": "zurück من أكثر الكلمات الألمانية شيوعًا للمسافرين. Rückfahrkarte (تذكرة عودة) تخفي zurück في Rück-. Hin und zurück = ذهاب وإياب.",

// exampleSrc
"A: Do you know the shop?\\nB: Yes, the shop is very good.": "A: هل تعرف المحل؟\\nB: نعم، المحل جيد جدًا.",
"A: Is there a good restaurant here?\\nB: Yes, the restaurant at the square is great.": "A: هل يوجد مطعم جيد هنا؟\\nB: نعم، المطعم عند الساحة ممتاز.",
"A: What kind of place is that?\\nB: That is a small town in Bavaria.": "A: ما نوع هذا المكان؟\\nB: هذه بلدة صغيرة في بافاريا.",
"A: Do you live in the city?\\nB: No, I live in a small village.": "A: هل تعيش في المدينة؟\\nB: لا، أعيش في قرية صغيرة.",
"A: Is this seat free?\\nB: Yes, please sit down.": "A: هل هذا المقعد فارغ؟\\nB: نعم، تفضل بالجلوس.",
"A: Where is the doctor's office?\\nB: The doctor's office is on the second floor.": "A: أين عيادة الطبيب؟\\nB: العيادة في الطابق الثاني.",
"A: Shall we go to the swimming pool?\\nB: Yes, good idea!": "A: هل نذهب إلى المسبح؟\\nB: نعم، فكرة جيدة!",
"A: What is the best attraction?\\nB: The Brandenburg Gate!": "A: ما أفضل معلم سياحي؟\\nB: بوابة براندنبورغ!",
"A: Where is the hotel?\\nB: In the center of the city.": "A: أين الفندق؟\\nB: في وسط المدينة.",
"A: Attention! The train is coming.\\nB: Thanks for the warning!": "A: انتباه! القطار قادم.\\nB: شكرًا على التنبيه!",
"A: Where is the information desk?\\nB: The information desk is at the entrance.": "A: أين مكتب الاستعلامات؟\\nB: مكتب الاستعلامات عند المدخل.",
"A: Do I have a connection to Munich?\\nB: Yes, the connection is in ten minutes.": "A: هل لدي رحلة ربط إلى ميونخ؟\\nB: نعم، رحلة الربط بعد عشر دقائق.",
"A: Are we taking the highway?\\nB: Yes, that is faster.": "A: هل نسلك الأوتوبان؟\\nB: نعم، هذا أسرع.",
"A: Are you going by train?\\nB: Yes, I am going by train to Hamburg.": "A: هل تسافر بالقطار؟\\nB: نعم، أسافر بالقطار إلى هامبورغ.",
"A: Who is the driver?\\nB: The driver's name is Thomas.": "A: من السائق؟\\nB: اسم السائق توماس.",
"A: Do you have a bicycle?\\nB: Yes, I ride my bicycle every day.": "A: هل لديك دراجة؟\\nB: نعم، أركب دراجتي كل يوم.",
"A: From which track does the train leave?\\nB: From track five.": "A: من أي رصيف يغادر القطار؟\\nB: من الرصيف الخامس.",
"A: What is that?\\nB: That is a big truck.": "A: ما هذا؟\\nB: هذه شاحنة كبيرة.",
"A: Shall we take the S-Bahn?\\nB: Yes, the S-Bahn is faster than the bus.": "A: هل نأخذ الـ S-Bahn؟\\nB: نعم، الـ S-Bahn أسرع من الحافلة.",
"A: Does a tram run here?\\nB: Yes, the tram comes every ten minutes.": "A: هل يمر ترام هنا؟\\nB: نعم، الترام يأتي كل عشر دقائق.",
"A: Where is Hamburg?\\nB: Hamburg is in the north.": "A: أين هامبورغ؟\\nB: هامبورغ في الشمال.",
"A: Where is Munich?\\nB: Munich is in the south.": "A: أين ميونخ؟\\nB: ميونخ في الجنوب.",
"A: Where is Dresden?\\nB: Dresden is in the east.": "A: أين درسدن؟\\nB: درسدن في الشرق.",
"A: Where is Cologne?\\nB: Cologne is in the west.": "A: أين كولونيا؟\\nB: كولونيا في الغرب.",
"A: Where do we meet?\\nB: At the train station, on Monday.": "A: أين نلتقي؟\\nB: عند محطة القطار، يوم الاثنين.",
"A: Where are you going?\\nB: I am going to the cinema.": "A: إلى أين تذهب؟\\nB: أذهب إلى السينما.",
"A: Is the tower tall?\\nB: Yes, it is very tall.": "A: هل البرج عالٍ؟\\nB: نعم، إنه عالٍ جدًا.",
"A: Is the train station far?\\nB: No, only five minutes on foot.": "A: هل محطة القطار بعيدة؟\\nB: لا، خمس دقائق مشيًا فقط.",
"A: Berlin is so big!\\nB: Yes, the city is really that big.": "A: برلين كبيرة جدًا!\\nB: نعم، المدينة كبيرة فعلًا بهذا الحجم.",
"A: Is everyone here?\\nB: Yes, everyone is here.": "A: هل الجميع هنا؟\\nB: نعم، الجميع هنا.",
"A: Where is the pharmacy?\\nB: Do you see the shop? Next to it.": "A: أين الصيدلية؟\\nB: هل ترى المحل؟ بجانبه.",
"A: Where is the restaurant?\\nB: Upstairs, on the second floor.": "A: أين المطعم؟\\nB: في الأعلى، في الطابق الثاني.",
"A: Where is the exit?\\nB: Downstairs, next to the entrance.": "A: أين المخرج؟\\nB: في الأسفل، بجانب المدخل.",
"A: Where do you sit on the bus?\\nB: At the back, by the window.": "A: أين تجلس في الحافلة؟\\nB: في الخلف، بجانب النافذة.",
"A: Where is Lukas?\\nB: Outside, he is waiting in front of the hotel.": "A: أين لوكاس؟\\nB: في الخارج، ينتظر أمام الفندق.",
"A: Where is the train station?\\nB: There, at the end of the street.": "A: أين محطة القطار؟\\nB: هناك، في نهاية الشارع.",
"A: I will be right back.\\nB: Okay, I will wait here.": "A: سأعود حالًا.\\nB: حسنًا، سأنتظر هنا.",
"A: When do you depart?\\nB: I depart at eight o'clock.": "A: متى تغادر؟\\nB: أغادر الساعة الثامنة.",
"A: Can you pick me up?\\nB: Yes, I will pick you up at the station.": "A: هل يمكنك أن تأخذني؟\\nB: نعم، سآخذك من المحطة.",
"A: What are we doing today?\\nB: We are visiting the Brandenburg Gate.": "A: ماذا نفعل اليوم؟\\nB: نزور بوابة براندنبورغ.",
"A: Does the bus stop here?\\nB: Yes, the bus stops at this stop.": "A: هل تتوقف الحافلة هنا؟\\nB: نعم، الحافلة تتوقف في هذه المحطة.",
"A: Where are you standing?\\nB: I am standing in front of the train station.": "A: أين تقف؟\\nB: أقف أمام محطة القطار.",
"A: What are you looking for?\\nB: I am looking for the exit.": "A: عمّ تبحث؟\\nB: أبحث عن المخرج.",
"A: Do you like hiking?\\nB: Yes, I hike every weekend.": "A: هل تحب المشي في الطبيعة؟\\nB: نعم، أمشي كل نهاية أسبوع.",
"A: How long are you staying in Berlin?\\nB: I am staying three days.": "A: كم ستبقى في برلين؟\\nB: سأبقى ثلاثة أيام.",
"A: How long does the trip take?\\nB: It takes one hour.": "A: كم تستغرق الرحلة؟\\nB: تستغرق ساعة واحدة.",
"A: Can you help me?\\nB: Yes, of course. How can I help?": "A: هل يمكنك مساعدتي؟\\nB: نعم، بالطبع. كيف أساعدك؟",
"A: Can you lend me your phone?\\nB: Yes, here you go.": "A: هل يمكنك إعارتي هاتفك؟\\nB: نعم، تفضل.",
"A: I am going to the museum. Are you coming along?\\nB: Yes, I would love to come along!": "A: سأذهب إلى المتحف. هل تأتي معي؟\\nB: نعم، أحب أن آتي معك!",
"A: Can you show me the way?\\nB: Yes, I will show you the way.": "A: هل يمكنك أن تريني الطريق؟\\nB: نعم، سأريك الطريق.",
"A: Are you taking the umbrella along?\\nB: Yes, I am taking it along.": "A: هل ستأخذ المظلة معك؟\\nB: نعم، سآخذها معي.",
"A: Do we get off here?\\nB: No, we continue to Alexanderplatz.": "A: هل ننزل هنا؟\\nB: لا، نتابع إلى ألكسندربلاتز.",
"A: Do I have to transfer?\\nB: Yes, you transfer at the main station.": "A: هل يجب أن أغيّر؟\\nB: نعم، تغيّر في المحطة الرئيسية.",
"A: Is the bakery open?\\nB: Yes, it is open until six.": "A: هل المخبز مفتوح؟\\nB: نعم، مفتوح حتى السادسة.",
"A: What are you doing right now?\\nB: I am at the train station right now.": "A: ماذا تفعل الآن؟\\nB: أنا في محطة القطار حاليًا.",
"A: How is the view from here?\\nB: The view is fantastic!": "A: كيف المنظر من هنا؟\\nB: المنظر رائع!",
"A: Do you need help?\\nB: Yes, I need help with the map.": "A: هل تحتاج مساعدة؟\\nB: نعم، أحتاج مساعدة مع الخريطة.",
"A: Did you hear the announcement?\\nB: Yes, the train is delayed.": "A: هل سمعت الإعلان؟\\nB: نعم، القطار متأخر.",
"A: Where can I get information?\\nB: Ask at the information desk.": "A: أين أحصل على معلومات؟\\nB: اسأل في مكتب الاستعلامات.",
"A: Can you give me an example?\\nB: Yes, for example this one.": "A: هل يمكنك إعطائي مثالًا؟\\nB: نعم، مثلًا هذا.",
"A: What was that?\\nB: That was an announcement. The train is coming later.": "A: ما كان ذلك؟\\nB: كان إعلانًا. القطار سيأتي لاحقًا.",
"A: What does the sign say?\\nB: The sign says: Exit.": "A: ماذا تقول اللافتة؟\\nB: اللافتة تقول: مخرج.",
"A: Careful! The street is wet.\\nB: Thanks, I will be careful.": "A: انتبه! الشارع مبلل.\\nB: شكرًا، سأكون حذرًا.",
"A: Have you been to the sea?\\nB: Yes, the North Sea is beautiful.": "A: هل زرت البحر؟\\nB: نعم، بحر الشمال جميل.",
"A: Shall we go to the lake?\\nB: Yes, the lake is very beautiful.": "A: هل نذهب إلى البحيرة؟\\nB: نعم، البحيرة جميلة جدًا.",
"A: Shall we take a day trip?\\nB: Yes, we are taking a day trip to Potsdam.": "A: هل نأخذ رحلة يومية؟\\nB: نعم، نأخذ رحلة يومية إلى بوتسدام.",
"A: Is there a guided tour?\\nB: Yes, the tour starts at eleven o'clock.": "A: هل توجد جولة إرشادية؟\\nB: نعم، الجولة تبدأ الساعة الحادية عشرة.",
"A: Do you have a map?\\nB: Yes, I have a map of Berlin.": "A: هل لديك خريطة؟\\nB: نعم، لدي خريطة لبرلين.",
"A: Do you have a brochure?\\nB: Yes, here is the museum brochure.": "A: هل لديك نشرة؟\\nB: نعم، هذه نشرة المتحف.",
"A: Where do I book the trip?\\nB: At the travel agency at the square.": "A: أين أحجز الرحلة؟\\nB: في وكالة السفر عند الساحة.",
"A: Do you have a travel guide?\\nB: Yes, the guide recommends this restaurant.": "A: هل لديك دليل سفر؟\\nB: نعم، الدليل يوصي بهذا المطعم.",
"A: Would you like this hotel?\\nB: No, the other hotel is better.": "A: هل تريد هذا الفندق؟\\nB: لا، الفندق الآخر أفضل.",
"A: Do you have everything?\\nB: Yes, I have everything. We can go.": "A: هل معك كل شيء؟\\nB: نعم، معي كل شيء. يمكننا الذهاب.",
"A: How much is the admission?\\nB: The admission is ten euros.": "A: كم رسم الدخول؟\\nB: رسم الدخول عشرة يورو.",

// goals
"Demonstrate article mastery": "إتقان أدوات التعريف",
"Apply direction and place knowledge": "تطبيق معرفة الاتجاهات والأماكن",
"Learn travel and transport verbs": "تعلّم أفعال السفر والنقل",
"Navigate public transport in German": "التنقل بالمواصلات العامة بالألمانية",
"Discover Berlin's Döner culture": "اكتشاف ثقافة الدونر في برلين",
"Learn sondern vs aber": "تعلّم الفرق بين sondern و aber",
"Master denn as conjunction": "إتقان denn كأداة ربط",
"Reflect on Unit 2 vocabulary": "مراجعة مفردات الوحدة ٢",
"Learn 20 essential adverbs, prepositions, and connectors": "تعلّم ٢٠ ظرفًا وحرف جر ورابطًا أساسيًا",
"Use time words like jetzt, bald, schon in sentences": "استخدام كلمات الزمن مثل jetzt، bald، schon في جمل",
"Navigate conversations with auf, durch, über, vor": "التنقل في المحادثات مع auf، durch، über، vor",
"Learn 18 city places and location nouns": "تعلّم ١٨ اسمًا لأماكن المدينة والمواقع",
"Ask and answer 'Where is...?' questions": "طرح أسئلة 'أين...؟' والإجابة عنها",
"Navigate with confidence using place vocabulary": "التنقل بثقة باستخدام مفردات الأماكن",
"Learn 20 transport and direction words": "تعلّم ٢٠ كلمة للنقل والاتجاهات",
"Use compass directions: Norden, Süden, Osten, Westen": "استخدام الاتجاهات: Norden، Süden، Osten، Westen",
"Understand contractions like am and ins": "فهم الاختصارات مثل am و ins",
"Learn 18 movement and action verbs": "تعلّم ١٨ فعل حركة وفعل",
"Use separable verbs like abholen, mitkommen, umsteigen": "استخدام الأفعال المنفصلة مثل abholen، mitkommen، umsteigen",
"Talk about travel actions and plans": "التحدث عن أنشطة السفر والخطط",
"Learn 20 city and tourism vocabulary words": "تعلّم ٢٠ كلمة عن المدينة والسياحة",
"Ask for help and information confidently": "طلب المساعدة والمعلومات بثقة",
"Describe sights, views, and places": "وصف المعالم والمناظر والأماكن",

// tips (long text with \\n)
"Every German noun has a gender. Watch the colors on every word card:\\n\\nder = blue (masculine)\\ndie = crimson (feminine)\\ndas = green (neuter)\\n\\nYour brain will start seeing patterns. Trust the colors.": "كل اسم ألماني له جنس نحوي. راقب الألوان على كل بطاقة كلمة:\\n\\nder = أزرق (مذكر)\\ndie = قرمزي (مؤنث)\\ndas = أخضر (محايد)\\n\\nدماغك سيبدأ برؤية الأنماط. ثق بالألوان.",
"Proto-Germanic had three genders, inherited from Proto-Indo-European. Most modern Germanic languages reduced this: English dropped all three, Dutch merged to two (de/het), Swedish and Danish use two (en/ett).\\n\\nGerman kept all three. This is one reason German is harder for English speakers than Dutch or Swedish.\\n\\nThe good news: you only need to assign the right article to the right noun. You do not need to understand WHY Mädchen (girl) is neuter or why Sonne (sun) is feminine. Just learn the word with its article every time.": "الجرمانية البدائية كان فيها ثلاثة أجناس نحوية، موروثة من الهندو-أوروبية البدائية. معظم اللغات الجرمانية الحديثة قلّصتها: الإنجليزية أسقطت الثلاثة، الهولندية دمجتها في اثنين (de/het)، السويدية والدانماركية تستخدمان اثنين (en/ett).\\n\\nالألمانية احتفظت بالثلاثة. هذا أحد أسباب صعوبة الألمانية مقارنة بالهولندية أو السويدية.\\n\\nالخبر الجيد: تحتاج فقط أن تربط الأداة الصحيحة بالاسم الصحيح. لا تحتاج أن تفهم لماذا Mädchen (فتاة) محايد أو لماذا Sonne (شمس) مؤنث. فقط تعلّم الكلمة مع أداتها في كل مرة.",
"Words ending in -ung, -ei, -keit, -heit, -ie are ALWAYS feminine (die).\\nWords ending in -chen are ALWAYS neuter (das).\\nCompound nouns take the gender of the LAST word.\\nThese rules cover hundreds of nouns.": "الكلمات المنتهية بـ -ung، -ei، -keit، -heit، -ie دائمًا مؤنثة (die).\\nالكلمات المنتهية بـ -chen دائمًا محايدة (das).\\nالأسماء المركبة تأخذ جنس الكلمة الأخيرة.\\nهذه القواعد تغطي مئات الأسماء.",
"German borrowed thousands of words from Latin and French. Nouns ending in -tion (Station, Nation, Organisation) are ALL feminine (die).\\n\\nSimilarly:\\n-tät (Qualität, Universität) = always die\\n-ik (Musik, Physik) = usually die\\n-ismus (Tourismus, Idealismus) = always der\\n-ment (Instrument, Moment) = usually das\\n\\nKnowing these suffix rules handles a large proportion of technical and academic vocabulary without memorization.": "الألمانية استعارت آلاف الكلمات من اللاتينية والفرنسية. الأسماء المنتهية بـ -tion (Station، Nation، Organisation) كلها مؤنثة (die).\\n\\nوكذلك:\\n-tät (Qualität، Universität) = دائمًا die\\n-ik (Musik، Physik) = عادة die\\n-ismus (Tourismus، Idealismus) = دائمًا der\\n-ment (Instrument، Moment) = عادة das\\n\\nمعرفة قواعد اللواحق هذه تغطي نسبة كبيرة من المفردات التقنية والأكاديمية بدون حفظ.",
"German borrowed thousands of words from Latin and French. Nouns ending in -tion (Station, Nation, Organisation) are ALL feminine (die).\\n\\nSimilarly:\\n-taet (Qualitaet, Universitaet) = always die\\n-ik (Musik, Physik) = usually die\\n-ismus (Tourismus, Idealismus) = always der\\n-ment (Instrument, Moment) = usually das\\n\\nKnowing these suffix rules handles a large proportion of technical and academic vocabulary without memorization.": "الألمانية استعارت آلاف الكلمات من اللاتينية والفرنسية. الأسماء المنتهية بـ -tion (Station، Nation، Organisation) كلها مؤنثة (die).\\n\\nوكذلك:\\n-tät (Qualität، Universität) = دائمًا die\\n-ik (Musik، Physik) = عادة die\\n-ismus (Tourismus، Idealismus) = دائمًا der\\n-ment (Instrument، Moment) = عادة das\\n\\nمعرفة قواعد اللواحق هذه تغطي نسبة كبيرة من المفردات التقنية والأكاديمية بدون حفظ.",
"German has a special word for contradicting a negative:\\n\\nA: Du kommst nicht? (You are not coming?)\\nB: Doch! Ich komme. (Yes I am! I am coming.)\\n\\nDoch = yes (but I disagree with your negative assumption)\\nJa = yes (regular agreement)\\nNein = no\\n\\nIf you say 'ja' to a negative question, the meaning is unclear in German. Doch removes all ambiguity.": "الألمانية فيها كلمة خاصة لنقض النفي:\\n\\nA: Du kommst nicht? (ألن تأتي؟)\\nB: Doch! Ich komme. (بلى! سآتي.)\\n\\nDoch = بلى (أعارض افتراضك السلبي)\\nJa = نعم (موافقة عادية)\\nNein = لا\\n\\nإذا قلت 'ja' لسؤال منفي، المعنى غامض بالألمانية. doch تزيل كل الغموض.",
"Many languages have a third answer word for contradicting negatives. French has 'si', German has 'doch', Dutch has 'toch' (in some uses) or 'jawel'.\\n\\nEnglish lost this word. When someone says 'You didn't eat, did you?' and you DID eat, English speakers say 'Yes I did!' with heavy stress. German uses one word: Doch.\\n\\nDoch has many other uses in German (e.g., as a softener, in commands, in exclamations). For now, master the contradiction function.": "كثير من اللغات فيها كلمة ثالثة للرد على النفي. الفرنسية فيها 'si'، الألمانية 'doch'، الهولندية 'toch' (في بعض الاستخدامات) أو 'jawel'.\\n\\nالعربية مثل الألمانية! كلمة 'بلى' تنقض النفي تمامًا مثل doch.\\n\\nلـ doch استخدامات أخرى كثيرة في الألمانية (مثل التلطيف، في الأوامر، في التعجب). الآن أتقن وظيفة نقض النفي.",
"The subject of a sentence (who/what DOES the action) uses the nominative case.\\n\\nder Mann sieht = the man sees\\ndie Frau steht = the woman stands\\ndas Kind spielt = the child plays\\n\\nNominative articles: der (masculine), die (feminine), das (neuter), die (plural).": "فاعل الجملة (من/ما يقوم بالفعل) يستخدم حالة الرفع (Nominativ).\\n\\nder Mann sieht = الرجل يرى\\ndie Frau steht = المرأة تقف\\ndas Kind spielt = الطفل يلعب\\n\\nأدوات الرفع: der (مذكر)، die (مؤنث)، das (محايد)، die (جمع).",
"In German, to ask a yes/no question, you swap the subject and verb:\\n\\nDu hast einen Bruder. (statement)\\nHast du einen Bruder? (question)\\n\\nSie sprechen Deutsch. (statement)\\nSprechen Sie Deutsch? (question)\\n\\nEr wohnt in Berlin. (statement)\\nWohnt er in Berlin? (question)\\n\\nThis inversion rule applies to ALL German verbs.": "في الألمانية، لطرح سؤال نعم/لا، تقلب ترتيب الفاعل والفعل:\\n\\nDu hast einen Bruder. (جملة خبرية)\\nHast du einen Bruder? (سؤال)\\n\\nSie sprechen Deutsch. (جملة خبرية)\\nSprechen Sie Deutsch? (سؤال)\\n\\nEr wohnt in Berlin. (جملة خبرية)\\nWohnt er in Berlin? (سؤال)\\n\\nقاعدة القلب هذه تسري على جميع الأفعال الألمانية.",
"German has two question types with different word order:\\n\\n1. Yes/No questions: Verb first, then subject.\\nHast du eine Fahrkarte? (Do you have a ticket?)\\n\\n2. W-questions: W-word first, verb second, then subject.\\nWo hast du eine Fahrkarte? (Where do you have a ticket?)\\n\\nBoth types put the verb very early. In statements, the verb is in position 2. In yes/no questions, it moves to position 1.": "الألمانية فيها نوعان من الأسئلة بترتيب كلمات مختلف:\\n\\n١. أسئلة نعم/لا: الفعل أولًا، ثم الفاعل.\\nHast du eine Fahrkarte? (هل لديك تذكرة؟)\\n\\n٢. أسئلة W: كلمة W أولًا، الفعل ثانيًا، ثم الفاعل.\\nWo hast du eine Fahrkarte? (أين لديك تذكرة؟)\\n\\nكلا النوعين يضعان الفعل مبكرًا جدًا. في الجمل الخبرية، الفعل في الموقع ٢. في أسئلة نعم/لا، ينتقل إلى الموقع ١.",
"ALWAYS die (feminine):\\n-ung: die Richtung, die Kreuzung, die Verbindung\\n-heit/-keit: die Freiheit, die Möglichkeit\\n-schaft: die Freundschaft\\n-tion: die Nation, die Station\\n-ei: die Bäckerei\\n\\nALWAYS das (neuter):\\n-chen: das Mädchen, das Brötchen\\n-lein: das Büchlein\\n-um: das Museum\\n\\nOften der (masculine):\\n-er (agent nouns): der Lehrer, der Fahrer\\nDays, months, seasons = der\\nCompound nouns = gender of LAST word (Stadtplan: Plan = der)": "دائمًا die (مؤنث):\\n-ung: die Richtung، die Kreuzung، die Verbindung\\n-heit/-keit: die Freiheit، die Möglichkeit\\n-schaft: die Freundschaft\\n-tion: die Nation، die Station\\n-ei: die Bäckerei\\n\\nدائمًا das (محايد):\\n-chen: das Mädchen، das Brötchen\\n-lein: das Büchlein\\n-um: das Museum\\n\\nغالبًا der (مذكر):\\n-er (أسماء الفاعل): der Lehrer، der Fahrer\\nالأيام والأشهر والفصول = der\\nالأسماء المركبة = جنس الكلمة الأخيرة (Stadtplan: Plan = der)",
"German drops the article before professions after sein:\\n\\nIch bin Lehrer. (NOT: Ich bin ein Lehrer)\\nSie ist Ärztin. (NOT: Sie ist eine Ärztin)\\nEr ist Student. (NOT: Er ist ein Student)\\n\\nException: if you add an adjective, the article returns:\\nEr ist ein sehr guter Lehrer.": "الألمانية تحذف أداة التعريف قبل المهن بعد sein:\\n\\nIch bin Lehrer. (وليس: Ich bin ein Lehrer)\\nSie ist Ärztin. (وليس: Sie ist eine Ärztin)\\nEr ist Student. (وليس: Er ist ein Student)\\n\\nاستثناء: إذا أضفت صفة، تعود الأداة:\\nEr ist ein sehr guter Lehrer.",
"Job titles after 'sein' classify the person rather than count them as objects. German omits the article for exactly this reason. The same happens with nationalities (Ich bin Deutsche) and religions. Once an adjective is added, the article returns because a full noun phrase is restored.": "المسميات الوظيفية بعد 'sein' تصنّف الشخص بدلًا من عدّه ككائن. الألمانية تحذف الأداة لهذا السبب بالذات. نفس الشيء مع الجنسيات (Ich bin Deutsche) والأديان. بمجرد إضافة صفة، تعود الأداة لأن العبارة الاسمية الكاملة تُستعاد.",
"You will see 'geschlossen' on every shop door on Sundays. Germany's Sonntagsruhe (Sunday rest) means most shops close. Bakeries sometimes open Sunday morning.": "ستشاهد 'geschlossen' على باب كل محل أيام الأحد. راحة الأحد في ألمانيا (Sonntagsruhe) تعني أن معظم المحلات مغلقة. المخابز أحيانًا تفتح صباح الأحد.",
"German distinguishes between doing something and the result:\\n\\nlegen (to lay) vs liegen (it is lying)\\nsetzen (to seat) vs sitzen (it is sitting)\\nstellen (to place) vs stehen (it is standing)\\n\\nThe -e- verb is the ACTION. The -i- verb is the STATE.": "الألمانية تفرّق بين القيام بالفعل والنتيجة:\\n\\nlegen (يضع) مقابل liegen (ممدد)\\nsetzen (يُجلس) مقابل sitzen (جالس)\\nstellen (يضع واقفًا) مقابل stehen (واقف)\\n\\nالفعل بـ -e- هو الحركة. الفعل بـ -i- هو الحالة.",
"The key question is: is the object UPRIGHT (bottle, vase, lamp) or FLAT (book, paper, clothes)?\\n\\nUpright: stehen (state) / stellen (action)\\nFlat: liegen (state) / legen (action)\\n\\nThen ask: LOCATION (already there) or ACTION (you move it)?\\n\\nLocation: stehen / liegen + dative (wo?)\\nAction: stellen / legen + accusative (wohin?)\\n\\nExample: 'Das Buch liegt auf dem Tisch' (state, flat). 'Ich lege das Buch auf den Tisch' (action, flat).": "السؤال الأساسي: هل الشيء واقف (زجاجة، مزهرية، مصباح) أم ممدد (كتاب، ورقة، ملابس)؟\\n\\nواقف: stehen (حالة) / stellen (حركة)\\nممدد: liegen (حالة) / legen (حركة)\\n\\nثم اسأل: موقع (موجود بالفعل) أم حركة (تنقله)؟\\n\\nموقع: stehen / liegen + حالة الجر (wo?)\\nحركة: stellen / legen + حالة النصب (wohin?)\\n\\nمثال: 'Das Buch liegt auf dem Tisch' (حالة، ممدد). 'Ich lege das Buch auf den Tisch' (حركة، ممدد).",
"Aber = but (general contrast):\\nDas Hotel ist klein, aber schön.\\n\\nSondern = but rather (corrects a negation):\\nDas ist nicht die Bank, sondern die Apotheke.\\n\\nRule: If there is 'nicht' or 'kein' before 'but,' use sondern.\\nOtherwise, use aber.": "aber = لكن (تناقض عام):\\nDas Hotel ist klein, aber schön.\\n\\nsondern = بل (تصحّح النفي):\\nDas ist nicht die Bank, sondern die Apotheke.\\n\\nالقاعدة: إذا سبقها 'nicht' أو 'kein'، استخدم sondern.\\nغير ذلك، استخدم aber.",
"Particle in questions: 'Was ist denn das?' (adds curiosity)\\n\\nConjunction meaning 'because/for':\\n'Ich gehe ins Café, denn ich bin müde.'\\n\\nYou learned the particle earlier. Now you know the conjunction too.": "أداة في الأسئلة: '?Was ist denn das' (تضيف فضولًا)\\n\\nأداة ربط بمعنى 'لأن':\\n'.Ich gehe ins Café, denn ich bin müde'\\n\\nتعلّمت الأداة سابقًا. الآن تعرف أداة الربط أيضًا.",
"What Verumius learned today:\\n\\nKönnen Sie mir helfen? = Can you help me?\\nEntschuldigung, wo ist...? = Excuse me, where is...?\\nGeradeaus, dann links/rechts = Straight, then left/right\\nNEVER cross on red (social death)\\n'Mit alles?' at the Döner stand = With everything?\\nDöner is always a good decision.": "ما تعلّمه Verumius اليوم:\\n\\n?Können Sie mir helfen = هل يمكنك مساعدتي؟\\n?...Entschuldigung, wo ist = عفوًا، أين...؟\\nGeradeaus, dann links/rechts = مباشرة، ثم يسار/يمين\\nلا تعبر أبدًا على الأحمر (موت اجتماعي)\\n'?Mit alles' عند كشك الدونر = مع كل شيء؟\\nالدونر دائمًا قرار صائب.",
"-ung = die (Richtung, Kreuzung, Verbindung, Öffnungszeit)\\n-ei = die (Bäckerei)\\n-e = usually die (Straße, Brücke, Kirche, Ecke, Sonne)\\n-chen = das (coming in Unit 3!)\\nCompound nouns = gender of LAST word\\nLatin/Greek loans = often das (Hotel, Café, Museum, Kino)\\nder See = lake, die See = sea (the ultimate trap)": "-ung = die (Richtung، Kreuzung، Verbindung، Öffnungszeit)\\n-ei = die (Bäckerei)\\n-e = غالبًا die (Straße، Brücke، Kirche، Ecke، Sonne)\\n-chen = das (قادم في الوحدة ٣!)\\nالأسماء المركبة = جنس الكلمة الأخيرة\\nالمستعارات اللاتينية/اليونانية = غالبًا das (Hotel، Café، Museum، Kino)\\nder See = بحيرة، die See = بحر (الفخ الأكبر)",
};
