/**
 * Unit 2 — Remaining notes (175+)
 */
module.exports = {
  "Preposition with multiple meanings.": "حرف جر بمعانٍ متعددة.",
  "Preposition. 'Zum' = zu + dem, 'Zur' = zu + der.": "حرف جر. Zum = zu + dem، Zur = zu + der.",
  "Preposition of location.": "حرف جر مكاني.",
  "Irregular: ich gebe, du gibst, er gibt.": "شاذ: ich gebe، du gibst، er gibt.",
  "Key phrase: es gibt = there is/are. Literally: it gives.": "عبارة مفتاحية: es gibt = يوجد. حرفيًا: يُعطي.",
  "Regular verb. Very useful for directions.": "فعل منتظم. مفيد جدًا للاتجاهات.",
  "Irregular: ich lese, du liest, er liest.": "شاذ: ich lese، du liest، er liest.",
  "Irregular stem change e→ie: ich sehe, du siehst, er sieht.": "تغير جذع شاذ e→ie: ich sehe، du siehst، er sieht.",
  "Regular verb. Zuhören = to listen actively.": "فعل منتظم. zuhören = يستمع بنشاط.",
  "Inseparable prefix verb: ver + stehen.": "فعل بسابقة غير منفصلة: ver + stehen.",
  "Predicative adjective. No ending after 'sein' (to be).": "صفة خبرية. بلا نهاية بعد sein (يكون).",
  "Predicative adjective. Opposite of groß.": "صفة خبرية. عكس groß.",
  "For physical length. 'Lange' for time duration.": "للطول الفعلي. lange لمدة الوقت.",
  "Opposite of lang.": "عكس lang.",
  "Feminine noun. 'Keine Frage!' = No doubt!": "اسم مؤنث. '!Keine Frage' = لا شك!",
  "Neuter noun. Same as English.": "اسم محايد. نفسها بالإنجليزية.",
  "Neuter noun. 'Zum Beispiel' (z.B.) = for example.": "اسم محايد. Zum Beispiel (z.B.) = على سبيل المثال.",
  "Adjective/adverb. No ending after sein.": "صفة/ظرف. بلا نهاية بعد sein.",
  "Adjective/adverb. Opposite of schnell.": "صفة/ظرف. عكس schnell.",
  "Separable verb: Ich fange an.": "فعل منفصل: Ich fange an.",
  "Separable verb: Hör auf!": "فعل منفصل: !Hör auf",
  "Irregular: ich esse, du isst, er isst.": "شاذ: ich esse، du isst، er isst.",
  "du isst sounds like du ist (you are). Context saves you!": "صوت du isst مطابق لـ du ist (أنت). السياق ينقذك!",
  "Inseparable prefix verb. Regular conjugation.": "فعل بسابقة غير منفصلة. تصريف منتظم.",
  "Inseparable prefix verb. Regular.": "فعل بسابقة غير منفصلة. منتظم.",
  "Regular verb. Ver+kaufen = to sell.": "فعل منتظم. ver+kaufen = يبيع.",
  "Regular verb. Related to Küche (kitchen).": "فعل منتظم. مرتبط بـ Küche (مطبخ).",
  "Regular verb. Opposite: schließen (to close).": "فعل منتظم. العكس: schließen (يغلق).",
  "Regular verb. 'Wie heißt du?' also uses this pattern.": "فعل منتظم. '?Wie heißt du' أيضًا تستخدم هذا النمط.",
  "Regular verb. Ich spiele, du spielst, er spielt.": "فعل منتظم. Ich spiele، du spielst، er spielt.",
  "Neuter noun. Der Spielplatz = the playground.": "اسم محايد. Der Spielplatz = ملعب الأطفال.",
  "Irregular positional verb. Ich sitze, du sitzt, er sitzt.": "فعل وضعي شاذ. Ich sitze، du sitzt، er sitzt.",
  "Irregular positional verb. Ich liege, du liegst, er liegt.": "فعل وضعي شاذ. Ich liege، du liegst، er liegt.",
  "Irregular verb. Stem change a→ä: du fährst, er fährt.": "فعل شاذ. تغير الجذع a→ä: du fährst، er fährt.",
  "Irregular verb. Stem change au→äu: du läufst, er läuft.": "فعل شاذ. تغير الجذع au→äu: du läufst، er läuft.",
  "Irregular: ich nehme, du nimmst, er nimmt.": "شاذ: ich nehme، du nimmst، er nimmt.",
  "Separable verb. Ich steige ein, du steigst ein.": "فعل منفصل. Ich steige ein، du steigst ein. السابقة تذهب لنهاية الجملة.",
  "Separable verb. Ich steige aus, du steigst aus.": "فعل منفصل. Ich steige aus، du steigst aus.",
  "Separable verb. Ich steige um, du steigst um.": "فعل منفصل. Ich steige um، du steigst um.",
  "Neuter noun. Spaß machen = to be fun.": "اسم محايد. Spaß machen = يكون ممتعًا.",
  "Neuter noun. 'Ein Stück Kuchen' = a piece of cake.": "اسم محايد. Ein Stück Kuchen = قطعة كعك.",
  "Regular verb. CAREFUL: bekommen ≠ to become! It means 'to get/receive.'": "فعل منتظم. انتبه: bekommen ≠ يصبح! تعني 'يحصل/يستلم'. صديق زائف شهير.",
  "Masculine noun. Plural: die Flüsse.": "اسم مذكر. الجمع: die Flüsse.",
  "Feminine noun. No plural.": "اسم مؤنث. لا جمع.",
  "Masculine noun. GENDER TRAP: der See = lake. die See = sea!": "اسم مذكر. فخ الجنس: der See = بحيرة. die See = بحر!",
  "Separable verb: ab + fahren. Der Zug fährt ab.": "فعل منفصل: ab + fahren. Der Zug fährt ab (القطار يغادر).",
  "Separable verb: an + kommen. Der Zug kommt an.": "فعل منفصل: an + kommen. Der Zug kommt an (القطار يصل).",
  "Inseparable prefix be-. Ich besuche, du besuchst.": "سابقة غير منفصلة be-. Ich besuche، du besuchst.",
  "Irregular: ich fliege, du fliegst, er fliegt.": "شاذ: ich fliege، du fliegst، er fliegt.",
  "Verb with dative. 'Mir gefällt Berlin!' = Berlin pleases me = I like Berlin.": "فعل مع المجرور. '!Mir gefällt Berlin' = برلين تعجبني. مثل العربية: الفاعل هو ما يُعجب!",
  "Regular verb. Ich schließe, du schließt. Past: schloss.": "فعل. Ich schließe، du schließt. الماضي: schloss.",
  "Adverb. 'Leider' softens bad news. 'Leider nein' = Unfortunately no.": "ظرف. leider تلطف الأخبار السيئة. Leider nein = للأسف لا.",
  "Conjunction. Corrects a negation: nicht A, sondern B.": "أداة ربط. تصحح النفي: nicht A, sondern B.",
  "Feminine noun. Eine gute Idee! = A good idea!": "اسم مؤنث. !Eine gute Idee = فكرة جيدة!",
  "Feminine noun. Plural: die Sachen. Also means 'stuff/things.'": "اسم مؤنث. الجمع: die Sachen. تعني أيضًا 'أغراض/أشياء'.",
  "Adverb. 'Bald' = soon (NOT bold/bald!).": "ظرف. bald = قريبًا (ليس جريء/أصلع!).",
  "Adverb. Dann gehen wir! = Then let's go!": "ظرف. !Dann gehen wir = إذن هيا نذهب!",
  "Adverb. 'Immer geradeaus' = always straight ahead.": "ظرف. Immer geradeaus = دائمًا مباشرة للأمام.",
  "Adverb. 'Jetzt oder nie!' = Now or never!": "ظرف. '!Jetzt oder nie' = الآن أو أبدًا!",
  "Adverb. Opposite of immer. 'Nie wieder!' = Never again!": "ظرف. عكس immer. '!Nie wieder' = لا مرة أخرى أبدًا!",
  "Adverb. 'Noch ein Bier!' = Another beer! 'Noch nicht' = not yet.": "ظرف. '!Noch ein Bier' = بيرة أخرى! Noch nicht = ليس بعد.",
  "Adverb. 'Nur ein Kaffee, bitte.' = Only one coffee, please.": "ظرف. Nur ein Kaffee, bitte = فقط قهوة واحدة من فضلك.",
  "Adverb. 'Ich gehe oft ins Kino.' = I often go to the cinema.": "ظرف. Ich gehe oft ins Kino = أذهب غالبًا إلى السينما.",
  "Adverb. 'Schon gut!' = It's alright! 'Schon wieder?' = Again?": "ظرف. '!Schon gut' = لا بأس! '?Schon wieder' = مجددًا؟",
  "Adverb. 'Komm sofort!' = Come immediately!": "ظرف. '!Komm sofort' = تعال فورًا!",
  "Adverb. Synonym of vielleicht. 'Vielleicht morgen' = Maybe tomorrow.": "ظرف. مرادف لـ vielleicht. Vielleicht morgen = ربما غدًا.",
  "Adverb. 'Komm wieder!' = Come again/back! 'Auf Wiedersehen' uses the same root.": "ظرف. '!Komm wieder' = عد مجددًا! Auf Wiedersehen تستخدم نفس الجذر.",
  "Two-way preposition. Location (dative) or direction (accusative).": "حرف جر ثنائي. مكان (مجرور) أو اتجاه (منصوب). مثل الإعراب بالعربية!",
  "Two-way preposition. Auf dem Tisch (on the table, location) vs Auf den Tisch (onto the table, direction).": "حرف جر ثنائي. Auf dem Tisch (على الطاولة، مكان) مقابل Auf den Tisch (إلى الطاولة، اتجاه).",
  "Accusative preposition. Durch den Park = Through the park.": "حرف جر منصوب. Durch den Park = عبر الحديقة.",
  "Accusative preposition. Gegen die Wand = Against the wall. Gegen 3 Uhr = Around 3 o'clock.": "حرف جر منصوب. Gegen die Wand = ضد الحائط. Gegen 3 Uhr = حوالي الثالثة.",
  "Two-way preposition. Über die Brücke (across the bridge, direction) vs über dem Fluss (above the river, location).": "حرف جر ثنائي. Über die Brücke (عبر الجسر، اتجاه) مقابل über dem Fluss (فوق النهر، مكان).",
  "Two-way preposition. Vor dem Haus (in front of the house, location). Vor einer Stunde (an hour ago, time).": "حرف جر ثنائي. Vor dem Haus (أمام المنزل، مكان). Vor einer Stunde (قبل ساعة، زمن).",
  "Dative preposition. 'Ab morgen' = from tomorrow. 'Ab 8 Uhr' = from 8 o'clock.": "حرف جر مجرور. Ab morgen = من الغد. Ab 8 Uhr = من الساعة ٨.",
  "Adjective. 'Eine breite Straße' = a wide street.": "صفة. Eine breite Straße = شارع عريض.",
  "Contraction of 'an + dem'. Used everywhere in spoken German.": "اختصار an + dem. تُستخدم في كل مكان بالألمانية المنطوقة.",
  "Contraction of 'in + das'. 'Ins Kino gehen' = to go to the cinema.": "اختصار in + das. Ins Kino gehen = الذهاب إلى السينما.",
  "Adjective. 'Ein hohes Gebäude' = a tall building. Opposite: niedrig.": "صفة. Ein hohes Gebäude = مبنى عالٍ. العكس: niedrig.",
  "Adjective. 'Weit weg' = far away. Opposite: nah (near).": "صفة. Weit weg = بعيد جدًا. العكس: nah (قريب).",
  "Adverb. 'So ist das!' = That's how it is!": "ظرف. '!So ist das' = هكذا الأمر!",
  "Determiner. 'Alle Leute' = all people. 'Alles klar?' = Everything clear?": "محدد. Alle Leute = كل الناس. '?Alles klar' = كل شيء واضح؟",
  "Adverb. 'Da daneben' = right next to it. Points to adjacent location.": "ظرف. Da daneben = بجانبه مباشرة. يشير إلى موقع مجاور.",
  "Adverb. 'Nach oben' = upward. Opposite: unten.": "ظرف. Nach oben = إلى الأعلى. العكس: unten.",
  "Adverb. 'Nach unten' = downward. Opposite: oben.": "ظرف. Nach unten = إلى الأسفل. العكس: oben.",
  "Adverb. 'Hinten im Bus' = at the back of the bus. Opposite: vorne.": "ظرف. Hinten im Bus = في مؤخرة الحافلة. العكس: vorne.",
  "Adverb. 'Draußen ist es kalt' = Outside it is cold. Opposite: drinnen.": "ظرف. Draußen ist es kalt = الجو بارد في الخارج. العكس: drinnen.",
  "Adverb. 'Dort drüben!' = Over there! More specific than 'da.'": "ظرف. '!Dort drüben' = هناك! أدق من da.",
  "Adverb. 'Geh zurück!' = Go back! 'Hin und zurück' = round trip.": "ظرف. '!Geh zurück' = ارجع! Hin und zurück = ذهاب وعودة.",
  "Separable verb. Prefix ab-. Der Zug fährt um 8 ab.": "فعل منفصل. سابقة ab-. Der Zug fährt um 8 ab.",
  "Separable verb. Prefix ab-. Ich hole dich ab = I'll pick you up.": "فعل منفصل. سابقة ab-. Ich hole dich ab = سآخذك.",
  "Inseparable prefix be-. Wir besichtigen Berlin = We tour Berlin.": "سابقة غير منفصلة be-. Wir besichtigen Berlin = نتجول في برلين.",
  "Irregular: er hält, du hältst. Stem change a→ä.": "شاذ: er hält، du hältst. تغير الجذع a→ä.",
  "Irregular positional verb. Ich stehe, du stehst.": "فعل وضعي شاذ. Ich stehe، du stehst.",
  "Regular verb. Ich suche = I'm looking for. 'Ich suche den Bahnhof.'": "فعل منتظم. Ich suche = أبحث عن. Ich suche den Bahnhof.",
  "Regular verb. 'Wir wandern im Wald' = We hike in the forest.": "فعل منتظم. Wir wandern im Wald = نتنزه في الغابة.",
  "Irregular verb. Ich bleibe, du bleibst. Past: blieb.": "فعل شاذ. Ich bleibe، du bleibst. الماضي: blieb.",
  "Regular verb. 'Wie lange dauert das?' = How long does that take?": "فعل منتظم. '?Wie lange dauert das' = كم يستغرق هذا؟",
  "Regular verb. Leihen = both to lend AND to borrow. Context decides.": "فعل منتظم. leihen = يُقرض ويستعير معًا. السياق يحدد.",
  "Separable verb: mit + kommen. 'Kommst du mit?' = Are you coming along?": "فعل منفصل: mit + kommen. '?Kommst du mit' = هل ستأتي معنا؟",
  "Regular verb. Ich zeige, du zeigst. 'Zeig mir!' = Show me!": "فعل منتظم. Ich zeige، du zeigst. '!Zeig mir' = أرني!",
  "Separable: mit + nehmen. 'Zum Mitnehmen' = to go (food).": "منفصل: mit + nehmen. Zum Mitnehmen = للأخذ (طعام).",
  "Separable: weiter + fahren. 'Fahr weiter!' = Keep driving!": "منفصل: weiter + fahren. '!Fahr weiter' = واصل القيادة!",
  "Separable: um + steigen. Essential for public transit.": "منفصل: um + steigen. أساسي للنقل العام.",
  "Phrase. 'Der Laden hat geöffnet' = The shop is open.": "عبارة. Der Laden hat geöffnet = المحل مفتوح.",
  "Colloquial for 'just now.' 'Ich war gerade da' = I was just there.": "عامية لـ 'للتو'. Ich war gerade da = كنت هناك للتو.",
  "Masculine noun. 'Der Blick auf Berlin' = The view of Berlin.": "اسم مذكر. Der Blick auf Berlin = المنظر على برلين.",
  "Feminine noun. 'Hilfe!' = Help! 'Erste Hilfe' = First aid.": "اسم مؤنث. '!Hilfe' = النجدة! Erste Hilfe = الإسعافات الأولية.",
  "Feminine noun. An announcement over speakers at stations.": "اسم مؤنث. إعلان عبر السماعات في المحطات.",
  "Feminine noun. 'Die Auskunft' = information desk. Or phone directory.": "اسم مؤنث. die Auskunft = مكتب الاستعلامات. أو دليل الهاتف.",
  "Feminine noun. durch (through) + Sage (saying) = through-saying.": "اسم مؤنث. durch (عبر) + Sage (قول) = 'قول عبر'.",
  "Neuter noun. 'Das Schild lesen' = to read the sign.": "اسم محايد. Das Schild lesen = قراءة اللافتة.",
  "Feminine noun. 'Vorsicht, Stufe!' = Caution, step!": "اسم مؤنث. '!Vorsicht, Stufe' = حذار، درجة!",
  "Neuter noun. 'Ans Meer fahren' = to go to the sea.": "اسم محايد. Ans Meer fahren = الذهاب إلى البحر.",
  "Masculine noun. 'Einen Ausflug machen' = to take a day trip.": "اسم مذكر. Einen Ausflug machen = القيام برحلة نهارية.",
  "Neuter noun. 'Ein Foto machen' = to take a photo.": "اسم محايد. Ein Foto machen = التقاط صورة.",
  "Feminine noun. Stadtführung = city tour. Museumsführung = museum tour.": "اسم مؤنث. Stadtführung = جولة مدينة. Museumsführung = جولة متحف.",
  "Feminine noun. Karte can mean map, ticket, or card.": "اسم مؤنث. Karte يمكن أن تعني خريطة أو تذكرة أو بطاقة.",
  "Masculine noun. From French 'prospectus.' Free at tourist offices.": "اسم مذكر. من الفرنسية prospectus. مجاني في المكاتب السياحية.",
  "Neuter noun. Reise (travel) + Büro (office) = travel office.": "اسم محايد مركب. Reise (سفر) + Büro (مكتب) = مكتب السفر. مثل الإضافة بالعربية.",
  "Masculine noun. Can be a book or a person who guides tours.": "اسم مذكر. يمكن أن يكون كتابًا أو شخصًا يرشد الجولات.",
  "Adjective/pronoun. 'Ein anderer Tag' = another day.": "صفة/ضمير. Ein anderer Tag = يوم آخر.",
  "Pronoun. 'Ich habe alles' = I have everything.": "ضمير. Ich habe alles = لدي كل شيء.",
  "Masculine noun. 'Freier Eintritt' = free admission.": "اسم مذكر. Freier Eintritt = دخول مجاني.",
  "Stem vowel e changes to ie in du and er/sie/es. Same pattern: lesen, sehen.": "حركة الجذع e تتحول إلى ie في صيغتي du و er/sie/es. نفس النمط: lesen، sehen.",
  "Regular pattern. Einkaufen (separable) = to shop: Ich kaufe ein.": "نمط منتظم. einkaufen (منفصل) = يتسوق: Ich kaufe ein.",
  "Regular pattern. Der Koch = the cook (noun). Die Küche = the kitchen.": "نمط منتظم. der Koch = الطباخ (اسم). die Küche = المطبخ.",
  "Regular verb. Opposite: schließen. Öffnungszeiten = opening hours.": "فعل منتظم. العكس: schließen. Öffnungszeiten = ساعات العمل.",
  "Regular verb. Arbeit (work, noun) + -en = to work.": "فعل منتظم. Arbeit (عمل، اسم) + en- = يعمل.",
};
