/** Unit 04 Part 2 — Arabic translations (302 strings) */
module.exports = {
  "An employee sorts shelves. Verumius asks: 'The flour?' The man points left. Then right. Then says: 'Aisle seven. I think.'": "موظف يُرتّب الرفوف. فيروميوس يسأل: 'الطحين؟' الرجل يشير يساراً. ثم يميناً. ثم يقول: 'الممر السابع. أظن.'",
  "Aisle seven. There it is. Flour. For Hildi. She said: 'Without flour, no cake.' I understand that even without a dictionary.": "الممر السابع. ها هو. الطحين. لهيلدي. قالت: 'بدون طحين، لا كعك.' أفهم ذلك حتى بدون قاموس.",
  "The bakery counter. You MUST take a number. The deli weighs in Gramm. And you can pay bar or mit Karte. Maybe.": "طاولة المخبز. يجب أن تأخذ رقماً. المعجّنات تُوزن بالغرام. ويمكنك الدفع bar أو mit Karte. ربما.",
  "bekommen vs kriegen": "bekommen مقابل kriegen",
  "Payment vocabulary": "مفردات الدفع",
  "Quantities in practice": "الكميات في التطبيق العملي",
  "Back at the bakery counter. The display says: 45. Verumius has number 47. His heart beats faster. Two more. A woman buys three types of bread. Slowly.": "مرة أخرى عند طاولة المخبز. الشاشة تقول: 45. فيروميوس يحمل الرقم 47. قلبه يدق أسرع. اثنان بعد. امرأة تشتري ثلاثة أنواع من الخبز. ببطء.",
  "47! The saleswoman looks at Verumius. 'Yes?' He points at a roll. 'Two, please.' She nods. It works. Language works!": "47! البائعة تنظر إلى فيروميوس. 'نعم؟' يشير إلى كعكة. 'اثنتين، من فضلك.' تومئ. الأمر ينجح. اللغة تنجح!",
  "to get / to receive": "يحصل على / يتلقى",
  "FALSE FRIEND: does NOT mean 'to become'!": "صديق زائف: لا يعني 'يُصبح'!",
  "A: What would you like? (lit: What do you get?)\\nB: I'll have the bread.": "A: ماذا تريد؟ (حرفياً: ماذا تحصل؟)\\nB: آخذ الخبز.",
  "'Was bekommen Sie?' is how EVERY German shop assistant asks what you want. Bekommen does NOT mean 'become.' That trap catches every English speaker. 'Werden' = to become.": "'Was bekommen Sie?' هكذا يسألك كل بائع في ألمانيا عمّا تريد. bekommen لا تعني 'يُصبح'. هذا الفخ يقع فيه كل متحدث بالإنجليزية. 'werden' = يُصبح.",
  "to get (casual synonym of bekommen)": "يحصل على (مرادف عامّي لـ bekommen)",
  "Casual. 'Ich kriege einen Kaffee.' Same meaning as bekommen.": "عامّي. 'Ich kriege einen Kaffee.' نفس معنى bekommen.",
  "A: What are you getting?\\nB: I'm getting a bread roll.": "A: ماذا ستأخذ؟\\nB: سآخذ كعكة خبز.",
  "'Kriegen' also historically means 'to wage war' (der Krieg = war). But in everyday speech it just means 'to get.' Context is everything.": "'kriegen' تاريخياً تعني أيضاً 'يشنّ حرباً' (der Krieg = الحرب). لكن في الكلام اليومي تعني فقط 'يحصل على'. السياق هو كل شيء.",
  "to offer": "يعرض / يُقدّم",
  "Separable: wir bieten... an. 'Das Angebot' comes from this verb.": "فعل منفصل: wir bieten... an. كلمة 'das Angebot' (العرض) مشتقة من هذا الفعل.",
  "A: What do you offer?\\nB: We offer fresh bread.": "A: ماذا تعرضون؟\\nB: نعرض خبزاً طازجاً.",
  "Separable: an|bieten. 'Das Angebot' (the offer) is the noun form. Compound magic: verb to noun in one step.": "فعل منفصل: an|bieten. كلمة 'das Angebot' (العرض) هي الشكل الاسمي. سحر التركيب: من فعل إلى اسم في خطوة واحدة.",
  "cash (adjective/adverb)": "نقداً (صفة/ظرف)",
  "'Bar zahlen' = pay cash. Noun 'die Bar' = a pub/bar.": "'bar zahlen' = يدفع نقداً. الاسم 'die Bar' = حانة.",
  "A: Are you paying cash?\\nB: Yes, cash please.": "A: هل تدفع نقداً؟\\nB: نعم، نقداً من فضلك.",
  "'Bar' as payment = cash. 'Die Bar' as a place = pub. Same word, totally different meaning and gender!": "'bar' كدفع = نقداً. 'die Bar' كمكان = حانة. نفس الكلمة، لكن المعنى والجنس مختلفان تماماً!",
  "light / heavy (also: easy / difficult)": "خفيف / ثقيل (أيضاً: سهل / صعب)",
  "Both have double meanings: physical weight AND difficulty.": "كلاهما لهما معنيان: الوزن الفعلي والصعوبة.",
  "A: Is the bag heavy?\\nB: No, it is light.": "A: هل الحقيبة ثقيلة؟\\nB: لا، إنها خفيفة.",
  "'Schwer' also means 'difficult.' 'Leicht' also means 'easy.' 'Das war schwer!' could mean heavy OR hard. Context saves you.": "'schwer' تعني أيضاً 'صعب'. 'leicht' تعني أيضاً 'سهل'. 'Das war schwer!' قد تعني ثقيلاً أو صعباً. السياق يُنقذك.",
  "to transfer (money)": "يُحوّل (مالاً)",
  "Inseparable: ich überweise. Also: die Bank, das Konto.": "فعل غير منفصل: ich überweise. أيضاً: die Bank، das Konto.",
  "A: I am transferring the money.\\nB: Thank you!": "A: أنا أحوّل المال.\\nB: شكراً!",
  "Germans LOVE bank transfers (Überweisungen). Many bills are paid this way, not by card. The Überweisung is a German institution.": "الألمان يعشقون التحويلات البنكية (Überweisungen). كثير من الفواتير تُدفع بهذه الطريقة، لا بالبطاقة. التحويل البنكي مؤسسة ألمانية بحد ذاتها.",
  "Verumius stands at the Bäckerei counter.\\nNo number. 'Wer ist dran?' calls the baker.\\nThree people wave their numbers.\\nVerumius stares.\\n\\nThe annoyed customer behind him sighs:\\n'Nummer ziehen!'\\nPull a number!\\n\\nLesson learned: always take a number at German counters.": "فيروميوس يقف عند طاولة المخبز.\\nبلا رقم. 'Wer ist dran?' ينادي الخبّاز.\\nثلاثة أشخاص يلوّحون بأرقامهم.\\nفيروميوس يحدّق.\\n\\nالزبون المنزعج خلفه يتنهّد:\\n'Nummer ziehen!'\\nاسحب رقماً!\\n\\nالدرس المستفاد: خذ دائماً رقماً عند الطاولات الألمانية.",
  "Bekommen = to get/receive, NOT to become!": "bekommen = يحصل على / يتلقى، وليس 'يُصبح'!",
  "Separable verb: the 'an' is at the end. The verb stem goes in the blank.": "فعل منفصل: 'an' تأتي في النهاية. جذر الفعل يوضع في الفراغ.",
  "We offer fresh cake.": "نحن نعرض كعكاً طازجاً.",
  "affordable / good value": "بسعر معقول / قيمة جيدة",
  "Positive: good price-to-quality ratio. More polite than billig.": "إيجابي: نسبة سعر إلى جودة جيدة. أكثر أدباً من billig.",
  "A: The wine is very affordable!\\nB: Yes, only three euros.": "A: النبيذ بسعر معقول جداً!\\nB: نعم، ثلاثة يورو فقط.",
  "Günstig implies good value, not just low price. Preiswert (price-worthy) means the same thing. Both are compliments. Billig, by contrast, implies low quality.": "günstig تعني قيمة جيدة، لا مجرد سعر منخفض. preiswert (تستحق ثمنها) تعني نفس الشيء. كلتاهما مجاملة. أما billig فتوحي بجودة منخفضة.",
  "cheap / low quality": "رخيص / جودة منخفضة",
  "Can mean inexpensive, but often implies low quality. Not always a compliment.": "قد تعني غير مكلف، لكن غالباً توحي بجودة منخفضة. ليست دائماً مجاملة.",
  "A: The meat is very cheap.\\nB: Yes, but does it taste good?": "A: اللحم رخيص جداً.\\nB: نعم، لكن هل طعمه جيد؟",
  "Günstig = good deal. Billig = suspiciously cheap. Germans take quality seriously: billig food raises eyebrows. In clothing, billig fashion is fast fashion.": "günstig = صفقة جيدة. billig = رخيص بشكل مريب. الألمان يأخذون الجودة على محمل الجد: الطعام الرخيص يثير الشكوك. في الملابس، billig تعني الأزياء السريعة.",
  "The cashier asks about your payment method. Physical money = ?": "الكاشير يسأل عن طريقة الدفع. المال الملموس = ؟",
  "A bag full of fruit is not light.": "حقيبة مليئة بالفواكه ليست خفيفة.",
  "The bag is heavy. It has a lot of fruit.": "الحقيبة ثقيلة. فيها كثير من الفواكه.",
  "'I get' at the deli counter. Plus a number of bread rolls.": "'أحصل على' عند طاولة المعجّنات. بالإضافة إلى عدد من كعكات الخبز.",
  "I get two hundred grams of ham and three bread rolls.": "أحصل على مئتي غرام من لحم الخنزير المقدّد وثلاث كعكات خبز.",
  "Bargeld is neuter. Negating a noun. Does the negator change for neuter?": "Bargeld محايد (das). نفي اسم. هل تتغير أداة النفي مع المحايد؟",
  "Polite imperative: verb + ?": "أمر مهذب: فعل + ؟",
  "Take this cake!": "خذ هذه الكعكة!",
  "You are negating an adjective, not a noun. Which negator goes with adjectives?": "أنت تنفي صفة، لا اسماً. أي أداة نفي تُستخدم مع الصفات؟",
  "200g of ham at a certain price. Which DOGFU preposition means 'for the purpose of'?": "200 غرام من اللحم المقدّد بسعر معين. أي حرف جر من DOGFU يعني 'من أجل'؟",
  "Buy two hundred grams of ham for the price of three euros.": "اشترِ مئتي غرام من اللحم المقدّد بسعر ثلاثة يورو.",
  "Konto is neuter. Für needs accusative. What ending for welch- with neuter acc?": "Konto محايد (das). für تحتاج حالة النصب. ما نهاية welch- مع المحايد المنصوب؟",
  "Two bread rolls in a paper bag. Warm. This is my first success in a German supermarket. Small, but real.": "كعكتا خبز في كيس ورقي. دافئتان. هذا أول نجاح لي في سوبرماركت ألماني. صغير، لكنه حقيقي.",
  "The moment of truth. Items fly across the scanner. The cashier doesn't pause. The next customer is already loading. ALL grammar from this unit in action.": "لحظة الحقيقة. المنتجات تتطاير عبر الماسح. الكاشير لا يتوقف. الزبون التالي يُحمّل أغراضه بالفعل. كل القواعد من هذه الوحدة قيد التطبيق.",
  "Test all 6 grammar constructs": "اختبر جميع التراكيب النحوية الستة",
  "Multi-construct combinations": "تركيبات نحوية متعددة",
  "Survive the Kasse": "انجُ من الكاسّة (Kasse)",
  "The checkout. The conveyor belt. The cashier. She picks up the first item. Beep. The second. Beep. Third, fourth, fifth. BeepBeepBeep. Faster than Verumius can think.": "الكاسّة. الحزام المتحرك. الكاشير. تلتقط العنصر الأول. بيب. الثاني. بيب. الثالث، الرابع، الخامس. بيب بيب بيب. أسرع مما يستطيع فيروميوس التفكير.",
  "The products come faster than I can pack. Milk, bananas, cheese, everything slides. The man behind me is already placing his things on the belt. HIS things. Next to MY things.": "المنتجات تأتي أسرع مما أستطيع التعبئة. حليب، موز، جبن، كل شيء ينزلق. الرجل خلفي يضع أغراضه على الحزام بالفعل. أغراضه هو. بجانب أغراضي أنا.",
  "'Do you need a bag?' Verumius does not understand the word. Tüte? What is a Tüte? He says: 'Yes?' It costs twenty cents. For a plastic bag.": "'هل تحتاج كيساً؟' فيروميوس لا يفهم الكلمة. Tüte؟ ما هي Tüte؟ يقول: 'نعم؟' تكلف عشرين سنتاً. لكيس بلاستيكي.",
  "The conveyor belt moves. Verumius places his items:\\nden Fisch, die Bananen, das Brot, keine Tüte.\\nThe cashier scans without looking up.\\n'Dreiundvierzig Euro achtundsiebzig.'\\nVerumius fumbles for his Kreditkarte.\\n'Nur bar!' says the cashier.\\nPanic.": "الحزام المتحرك يتحرك. فيروميوس يضع أغراضه:\\nden Fisch, die Bananen, das Brot, keine Tüte.\\nالكاشير يمسح دون أن يرفع نظره.\\n'Dreiundvierzig Euro achtundsiebzig.'\\nفيروميوس يتلمّس بطاقته.\\n'Nur bar!' يقول الكاشير.\\nذعر.",
  "Fisch is masculine. Direct object = accusative = den.": "Fisch مذكر. مفعول به = حالة نصب = den.",
  "A chicken costs less than ten euros.": "دجاجة تكلف أقل من عشرة يورو.",
  "The chicken costs nine euros fifty.": "الدجاجة تكلف تسعة يورو وخمسين سنتاً.",
  "Tüte is feminine. What ending does the noun-negator need for feminine?": "Tüte مؤنث (die). ما النهاية التي تحتاجها أداة نفي الاسم مع المؤنث؟",
  "Liter is masculine in the accusative. The quantity is 200g. Third blank: which DOGFU preposition means 'for'?": "Liter مذكر في حالة النصب. الكمية 200 غرام. الفراغ الثالث: أي حرف جر من DOGFU يعني 'من أجل'؟",
  "I am buying one liter of milk and two hundred grams of butter for the family.": "أشتري لتراً واحداً من الحليب ومئتي غرام من الزبدة للعائلة.",
  "Brot is neuter, accusative. Check the demonstrative endings for neuter.": "Brot محايد (das)، حالة نصب. تحقق من نهايات أسماء الإشارة للمحايد.",
  "Rechnung is feminine. Acc feminine = no change from nom.": "Rechnung مؤنث (die). المؤنث المنصوب = لا تغيير عن حالة الرفع.",
  "At 3 euros, the wine is NOT expensive.": "بثلاثة يورو، النبيذ ليس غالياً.",
  "Cash or with card? Two payment methods.": "نقداً أم بالبطاقة؟ طريقتا دفع.",
  "Are you paying cash or with card?": "هل تدفع نقداً أم بالبطاقة؟",
  "Movement THROUGH something. First letter of DOGFU.": "حركة عبر شيء ما. الحرف الأول من DOGFU.",
  "Ohne requires a specific case. Think about what happens to the article.": "ohne تتطلب حالة إعرابية محددة. فكّر فيما يحدث للأداة.",
  "Without a euro I cannot get a shopping cart.": "بدون يورو لا أستطيع الحصول على عربة تسوق.",
  "per": "لكل / لِـ",
  "Latin loanword. Used with prices, quantities, and rates.": "كلمة مستعارة من اللاتينية. تُستخدم مع الأسعار والكميات والمعدلات.",
  "A: How much does a kilo cost?\\nB: Two euros per kilo.": "A: كم يكلف الكيلو؟\\nB: يورو لكل كيلو.",
  "'Pro' comes directly from Latin and is the same in many European languages. At the market it pairs with units: pro Kilo, pro Stück (per piece), pro Person.": "'pro' جاءت مباشرة من اللاتينية وهي متشابهة في كثير من اللغات الأوروبية. في السوق تقترن بالوحدات: pro Kilo، pro Stück (للقطعة)، pro Person.",
  "Per kilogram. 'Pro Kilo' means per kilo in German.": "لكل كيلوغرام. 'pro Kilo' تعني لكل كيلو بالألمانية.",
  "Polite imperative + masculine accusative + good value.": "أمر مهذب + مذكر منصوب + قيمة جيدة.",
  "Take this cake! It is on offer today.": "خذ هذه الكعكة! إنها معروضة اليوم.",
  "Polite imperative. Kuchen is masculine. What form does the demonstrative take in accusative?": "أمر مهذب. Kuchen مذكر. ما شكل اسم الإشارة في حالة النصب؟",
  "Was für requires a specific article form. Think about the noun's gender.": "was für تتطلب شكلاً محدداً للأداة. فكّر في جنس الاسم.",
  "What kind of vegetables are you buying?": "أي نوع من الخضراوات تشتري؟",
  "dreihundert=300, fünfundsechzig=65.": "dreihundert = 300، fünfundsechzig = 65.",
  "First two blanks negate nouns (different genders). Third blank negates the verb, not a noun.": "الفراغان الأولان ينفيان اسمين (جنسان مختلفان). الفراغ الثالث ينفي الفعل، لا اسماً.",
  "I have no cash and no credit card. I cannot pay at all.": "ليس عندي نقود ولا بطاقة ائتمان. لا أستطيع الدفع أبداً.",
  "Kunde is masculine. Nominative case. What form does jed- take?": "Kunde مذكر. حالة رفع. ما شكل jed- هنا؟",
  "Fruit weighs less than meat. Comparative of leicht.": "الفاكهة أخف من اللحم. صيغة المقارنة من leicht.",
  "The fruit is lighter than the meat.": "الفاكهة أخف من اللحم.",
  "Asking about WHAT you are shopping for.": "السؤال عمّا تتسوق من أجله.",
  "The price FOR this fish. Which accusative preposition?": "السعر من أجل هذه السمكة. أي حرف جر يأخذ النصب؟",
  "The price for this fish is seven euros.": "سعر هذه السمكة سبعة يورو.",
  "Verumius stands outside REWE. Two full bags. Red hands. Sweat on his forehead. He survived. Barely.": "فيروميوس يقف خارج REWE. حقيبتان ممتلئتان. يدان حمراوان. عرق على جبينه. نجا. بالكاد.",
  "Verumius made it home. Bags borrowed, groceries secured. Time to review everything from the supermarket adventure. All 6 grammar constructs in multi-construct combinations.": "فيروميوس وصل إلى البيت. الأكياس مُستعارة، والمشتريات مؤمّنة. حان وقت مراجعة كل شيء من مغامرة السوبرماركت. جميع التراكيب النحوية الستة في تركيبات متعددة.",
  "Comprehensive Unit 4 review": "مراجعة شاملة للوحدة الرابعة",
  "Multi-construct quiz steps": "خطوات اختبار متعددة التراكيب",
  "Celebrate surviving German shopping": "احتفل بالنجاة من التسوق الألماني",
  "The kitchen. Verumius puts everything on the table. Cheese, milk, bananas (with broccoli price), rolls, flour. More than he needs. Less than he wanted.": "المطبخ. فيروميوس يضع كل شيء على الطاولة. جبن، حليب، موز (بسعر البروكلي)، كعكات خبز، طحين. أكثر مما يحتاج. أقل مما أراد.",
  "I take a photo and send it to Yilmaz. 'My first shopping trip!' She replies immediately.": "ألتقط صورة وأرسلها ليلماز. 'أول رحلة تسوق لي!' تردّ فوراً.",
  "Very good! But... where is the bread? And the rice? And the eggs? Hildi will ask.": "ممتاز! لكن... أين الخبز؟ والأرز؟ والبيض؟ هيلدي ستسأل.",
  "Verumius stands in his kitchen. Results:\\n\\nNo bags (keine Tüte) = borrowed from a kind Kundin\\nPfandautomat rejected his foreign bottle\\nForgot to weigh his tomatoes\\n\\nBut: amazing bread, perfect Schinken, fresh Obst, and cheap Wein.\\nVerumius: 1. German supermarket: 0.": "فيروميوس يقف في مطبخه. النتائج:\\n\\nلا أكياس (keine Tüte) = استعار من زبونة لطيفة\\nجهاز الإيداع رفض زجاجته الأجنبية\\nنسي أن يزن طماطمه\\n\\nلكن: خبز رائع، Schinken مثالي، Obst طازج، و Wein رخيص.\\nفيروميوس: 1. السوبرماركت الألماني: 0.",
  "One masculine direct object, one feminine direct object. How does ein change for each?": "مفعول به مذكر ومفعول به مؤنث. كيف تتغير ein لكل منهما؟",
  "Deli meat is weighed in this small unit.": "لحم المعجّنات يُوزن بهذه الوحدة الصغيرة.",
  "Through the store, fruit FOR the family, but WITHOUT meat.": "عبر المتجر، فاكهة للعائلة، لكن بدون لحم.",
  "I go through the supermarket and buy fruit for the family, but without meat.": "أمرّ عبر السوبرماركت وأشتري فاكهة للعائلة، لكن بدون لحم.",
  "Brot is neuter. What form does welcher take for neuter accusative?": "Brot محايد (das). ما شكل welcher مع المحايد المنصوب؟",
  "German numbers: ones digit first, then und, then tens. Five-and-seventy.": "الأعداد الألمانية: رقم الآحاد أولاً، ثم und، ثم العشرات. خمسة وسبعون.",
  "The milk costs one euro seventy-five cents.": "الحليب يكلف يورو واحداً وخمسة وسبعين سنتاً.",
  "Polite imperative + masculine accusative + good value.": "أمر مهذب + مذكر منصوب + قيمة جيدة.",
  "Buy the fish! It is affordable today.": "اشترِ السمكة! إنها بسعر معقول اليوم.",
  "Two nouns: one neuter, one feminine. The noun-negator changes with gender.": "اسمان: واحد محايد وواحد مؤنث. أداة نفي الاسم تتغير مع الجنس.",
  "Kundin is feminine. Jeder declines like der. Feminine nom = jede.": "Kundin مؤنث. jeder يُصرّف مثل der. المؤنث في حالة الرفع = jede.",
  "Every customer must take a number.": "كل زبونة يجب أن تأخذ رقماً.",
  "Wein is masculine and a direct object. How does ein change in accusative?": "Wein مذكر ومفعول به. كيف تتغير ein في حالة النصب؟",
  "Chicken: 8 Euro 90. Potatoes: 2 Euro 50.": "الدجاج: 8 يورو و90 سنتاً. البطاطا: 2 يورو و50 سنتاً.",
  "The chicken costs eight euros ninety and the potatoes cost two euros fifty.": "الدجاج يكلف ثمانية يورو وتسعين سنتاً والبطاطا تكلف يورو وخمسين سنتاً.",
  "Contrast with günstig. The red bag costs a lot.": "بالمقارنة مع günstig. الحقيبة الحمراء تكلف كثيراً.",
  "Kilo is neuter. Accusative neuter = no change.": "Kilo محايد (das). المحايد المنصوب = لا تغيير.",
  "I need one kilo of potatoes.": "أحتاج كيلو بطاطا واحداً.",
  "Brötchen is neuter. Du-imperative + neuter acc = das.": "Brötchen محايد (das). أمر المخاطب + محايد منصوب = das.",
  "First blank negates a feminine noun. Second blank negates a neuter noun. Third blank is an adjective, not a negator.": "الفراغ الأول ينفي اسماً مؤنثاً. الفراغ الثاني ينفي اسماً محايداً. الفراغ الثالث صفة، لا أداة نفي.",
  "Verumius has no bag and no cash. But he has fresh fruit!": "فيروميوس ليس عنده كيس ولا نقود. لكن عنده فاكهة طازجة!",
  "Ohne takes accusative case. What happens to ein with masculine nouns?": "ohne تأخذ حالة النصب. ماذا يحدث لـ ein مع الأسماء المذكرة؟",
  "MOST people shop here. Superlative of viel.": "أكثر الناس يتسوقون هنا. صيغة التفضيل من viel.",
  "The most people shop here.": "أكثر الناس يتسوقون هنا.",
  "hundert=100, dreiundfünfzig=53.": "hundert = 100، dreiundfünfzig = 53.",
  "Polite: go through the store and pay for the (masc acc) purchase!": "بأدب: امشِ عبر المتجر وادفع ثمن المشتريات (مذكر منصوب)!",
  "Go please through the store and pay for the purchase!": "امشِ من فضلك عبر المتجر وادفع ثمن المشتريات!",
  "Verumius stands in his kitchen. Bread on the table, fruit in the fridge, wine on the shelf. Tomorrow: cooking. Without a recipe, without a plan, but with courage. And with a shopping list. Hildi wrote him one.": "فيروميوس يقف في مطبخه. الخبز على الطاولة، الفاكهة في الثلاجة، النبيذ على الرف. غداً: الطبخ. بدون وصفة، بدون خطة، لكن بشجاعة. ومع قائمة تسوق. هيلدي كتبت له واحدة.",
  "The German breakfast table, the Bäckerei, and everything you need to eat and drink your way through daily life.": "مائدة الإفطار الألمانية، المخبز (Bäckerei)، وكل ما تحتاجه لتأكل وتشرب في الحياة اليومية.",
  "Name common German foods and drinks": "تعرّف على الأطعمة والمشروبات الألمانية الشائعة",
  "Use articles with food nouns": "استخدم أدوات التعريف مع أسماء الطعام",
  "Order and shop for food items": "اطلب وتسوّق المواد الغذائية",
  "The next morning. Coffee, rolls, cheese. Verumius has breakfast like a German. Almost. The butter is missing.": "صباح اليوم التالي. قهوة، كعكات خبز، جبن. فيروميوس يتناول الإفطار كألماني. تقريباً. الزبدة مفقودة.",
  "the coffee": "القهوة",
  "Masculine noun. No plural in standard use. 'Zwei Kaffee, bitte!'": "اسم مذكر (der). لا جمع في الاستخدام العادي. 'Zwei Kaffee, bitte!'",
  "A: Would you like coffee?\\nB: Yes, a coffee with milk, please.": "A: هل تريد قهوة؟\\nB: نعم، قهوة بالحليب من فضلك.",
  "A: Do you drink milk?\\nB: No, I don't drink milk.": "A: هل تشرب حليباً؟\\nB: لا، أنا لا أشرب الحليب.",
  "German distinguishes: Vollmilch (whole milk), fettarme Milch (low-fat), Magermilch (skim). At the supermarket, the cap color tells you which type.": "الألمانية تفرّق بين: Vollmilch (كامل الدسم)، fettarme Milch (قليل الدسم)، Magermilch (منزوع الدسم). في السوبرماركت، لون الغطاء يدلّك على النوع.",
  "the tea": "الشاي",
  "Masculine noun. Plural: die Tees. 'Schwarzer Tee' = black tea.": "اسم مذكر (der). الجمع: die Tees. 'Schwarzer Tee' = شاي أسود.",
  "A: Would you like tea or coffee?\\nB: Tea, please. Green tea.": "A: هل تريد شاياً أم قهوة؟\\nB: شاياً، من فضلك. شاي أخضر.",
  "'Tee' comes from Chinese 'te' via Dutch traders. Northern Germany, especially East Frisia, has a tea culture rivaling England's. They drink more tea per capita than any other German region.": "'Tee' جاءت من الصينية 'te' عبر التجار الهولنديين. شمال ألمانيا، خاصة فريزيا الشرقية، لديها ثقافة شاي تنافس إنجلترا. يشربون شاياً للفرد أكثر من أي منطقة ألمانية أخرى.",
  "the beer": "البيرة",
  "Neuter noun. Plural: die Biere. Germany's national drink.": "اسم محايد (das). الجمع: die Biere. المشروب الوطني لألمانيا.",
  "A: A beer, please!\\nB: Which beer? Pilsner, wheat or Kölsch?": "A: بيرة من فضلك!\\nB: أي بيرة؟ Pilsner أم قمح أم Kölsch؟",
  "the wine": "النبيذ",
  "Masculine noun. Plural: die Weine. 'Rotwein' = red, 'Weißwein' = white.": "اسم مذكر (der). الجمع: die Weine. 'Rotwein' = أحمر، 'Weißwein' = أبيض.",
  "A: Do you drink wine?\\nB: Yes, I like white wine.": "A: هل تشرب نبيذاً؟\\nB: نعم، أحب النبيذ الأبيض.",
  "the bread roll": "كعكة الخبز",
  "Neuter noun. Plural: die Brötchen. Diminutive of 'Brot' (bread).": "اسم محايد (das). الجمع: die Brötchen. تصغير 'Brot' (خبز).",
  "A: I'd like two bread rolls, please.\\nB: With butter and cheese?": "A: أريد كعكتي خبز من فضلك.\\nB: بالزبدة والجبن؟",
  "Brötchen have different names across Germany: Semmel (Bavaria), Schrippe (Berlin), Wecken (Southwest). Starting a 'what is the correct name' debate is a guaranteed conversation starter.": "لكعكات الخبز أسماء مختلفة في أنحاء ألمانيا: Semmel (بافاريا)، Schrippe (برلين)، Wecken (الجنوب الغربي). بدء نقاش 'ما الاسم الصحيح' كفيل بفتح محادثة فوراً.",
  "the potato": "البطاطا",
  "Feminine noun. Plural: die Kartoffeln.": "اسم مؤنث (die). الجمع: die Kartoffeln.",
  "A: Do you like potatoes?\\nB: Yes, fried potatoes are my favorite food!": "A: هل تحب البطاطا؟\\nB: نعم، البطاطا المقلية أكلتي المفضلة!",
  "Kartoffel comes from Italian 'tartufolo' (truffle), because early potatoes looked like truffles. Frederick the Great forced Prussians to eat them. Now Germany eats 60 kg per person per year.": "Kartoffel جاءت من الإيطالية 'tartufolo' (كمأة)، لأن البطاطا الأولى كانت تشبه الكمأة. فريدريك الأكبر أجبر البروسيين على أكلها. الآن ألمانيا تأكل 60 كغ للفرد سنوياً.",
  "the rice": "الأرز",
  "Masculine noun. No standard plural. 'Reis mit Gemüse' = rice with vegetables.": "اسم مذكر (der). لا جمع معتاد. 'Reis mit Gemüse' = أرز مع خضراوات.",
  "A: Would you like rice or potatoes?\\nB: Rice, please.": "A: هل تريد أرزاً أم بطاطا؟\\nB: أرزاً، من فضلك.",
  "'Reis' comes from Greek 'oryza' via Latin. In a German Mensa (university cafeteria), Reis mit Sauce is the cheapest meal option. Every student knows it.": "'Reis' جاءت من اليونانية 'oryza' عبر اللاتينية. في المطعم الجامعي الألماني (Mensa)، Reis mit Sauce هي أرخص وجبة. كل طالب يعرف ذلك.",
  "the salad": "السلطة",
  "Masculine noun. Plural: die Salate. Also means 'lettuce.'": "اسم مذكر (der). الجمع: die Salate. تعني أيضاً 'الخس'.",
  "A: I'll have a salad.\\nB: A large or small salad?": "A: سآخذ سلطة.\\nB: سلطة كبيرة أم صغيرة؟",
  "'Salat' in German can mean the dish (salad) OR the plant (lettuce). 'Kopfsalat' = head lettuce. 'Kartoffelsalat' = potato salad, a German BBQ essential with as many recipes as there are grandmothers.": "'Salat' بالألمانية قد تعني الطبق (سلطة) أو النبات (خس). 'Kopfsalat' = خس. 'Kartoffelsalat' = سلطة بطاطا، طبق أساسي في الشواء الألماني، له وصفات بعدد الجدّات.",
  "the pear": "الكمّثرى",
  "Feminine noun. Plural: die Birnen. Also slang for 'head.'": "اسم مؤنث (die). الجمع: die Birnen. أيضاً عامّية بمعنى 'الرأس'.",
  "A: Would you like a pear?\\nB: Yes, the pears look good!": "A: هل تريد كمّثرى؟\\nB: نعم، الكمّثرى تبدو جيدة!",
  "'Birne' also means 'light bulb' (die Glühbirne = glow-pear) because of the shape. And in slang, 'Birne' means 'head': 'Mir raucht die Birne' = my head is smoking (I'm thinking hard).": "'Birne' تعني أيضاً 'مصباح كهربائي' (die Glühbirne = كمّثرى متوهجة) بسبب الشكل. وعامّياً، 'Birne' تعني 'الرأس': 'Mir raucht die Birne' = رأسي يدخّن (أفكر بجد).",
  "the cake": "الكعك",
  "Masculine noun. Plural: die Kuchen. German Kuchen is a daily treat.": "اسم مذكر (der). الجمع: die Kuchen. الكعك الألماني متعة يومية.",
  "A: Would you like a piece of cake?\\nB: Yes, please! Apple cake?": "A: هل تريد قطعة كعك؟\\nB: نعم من فضلك! كعكة تفاح؟",
  "Kaffee und Kuchen at 3 PM is Germany's unofficial fourth meal. Popular types: Schwarzwälder Kirschtorte (Black Forest cake), Apfelkuchen, Bienenstich (bee sting cake).": "Kaffee und Kuchen الساعة الثالثة عصراً هي الوجبة الرابعة غير الرسمية في ألمانيا. أنواع شهيرة: Schwarzwälder Kirschtorte (كعكة الغابة السوداء)، Apfelkuchen، Bienenstich (كعكة لسعة النحلة).",
  "Masculine noun. Plural: die Fische.": "اسم مذكر (der). الجمع: die Fische.",
  "A: Do you like eating fish?\\nB: Yes, especially salmon.": "A: هل تحب أكل السمك؟\\nB: نعم، خاصة السلمون.",
  "Fischbrötchen (fish sandwich) is THE street food of northern Germany, especially Hamburg. It is to Hamburg what the Döner is to Berlin.": "Fischbrötchen (سندويشة السمك) هي طعام الشارع الأول في شمال ألمانيا، خاصة هامبورغ. هي لهامبورغ ما الدونر لبرلين.",
  "the chicken (cooked)": "الدجاج (مطبوخ)",
  "Neuter noun. Plural: die Hähnchen. Diminutive of Hahn (rooster).": "اسم محايد (das). الجمع: die Hähnchen. تصغير Hahn (ديك).",
  "A: I'd like chicken, please.\\nB: Chicken with rice or fries?": "A: أريد دجاجاً من فضلك.\\nB: دجاج مع أرز أم بطاطا مقلية؟",
  "Hähnchen means the cooked dish. A living chicken is 'das Huhn.' A rooster is 'der Hahn.' Half a roasted chicken at Oktoberfest is called 'ein halbes Hendl' in Bavarian.": "Hähnchen تعني الطبق المطبوخ. الدجاجة الحية 'das Huhn'. الديك 'der Hahn'. نصف دجاجة مشوية في Oktoberfest تُسمى 'ein halbes Hendl' بالبافارية.",
  "the egg": "البيضة",
  "Neuter noun. Plural: die Eier.": "اسم محايد (das). الجمع: die Eier.",
  "A: How would you like your egg?\\nB: Soft-boiled, please.": "A: كيف تريد بيضتك؟\\nB: مسلوقة ناعمة، من فضلك.",
  "The German breakfast egg (Frühstücksei) is serious business. There is even a famous comedy sketch about couples arguing over the perfect egg-boiling time: the '4.5 Minuten Ei' debate.": "بيضة الإفطار الألمانية (Frühstücksei) أمر جدّي. هناك مشهد كوميدي شهير عن أزواج يتجادلون حول وقت سلق البيضة المثالي: نقاش 'بيضة الأربع دقائق ونصف'.",
  "the oil": "الزيت",
  "Neuter noun. Plural: die Öle. Used for cooking and other purposes.": "اسم محايد (das). الجمع: die Öle. يُستخدم للطبخ وأغراض أخرى.",
  "A: Oil or butter?\\nB: Oil, please.": "A: زيت أم زبدة؟\\nB: زيت، من فضلك.",
  "'Öl' works in compounds: Olivenöl (olive oil), Sonnenblumenöl (sunflower oil), Motoröl (motor oil). Same word for kitchen and garage.": "'Öl' تعمل في المركبات: Olivenöl (زيت زيتون)، Sonnenblumenöl (زيت دوّار الشمس)، Motoröl (زيت محرك). نفس الكلمة للمطبخ والمرآب.",
  "the salt": "الملح",
  "Neuter noun. No standard plural. Essential in every kitchen.": "اسم محايد (das). لا جمع معتاد. أساسي في كل مطبخ.",
  "A: Can you pass me the salt?\\nB: Here you go.": "A: هل يمكنك تمرير الملح؟\\nB: تفضّل.",
  "Salzburg (salt castle) and the word 'salary' both come from salt. In medieval Germany, salt was so valuable it was called 'weißes Gold' (white gold).": "Salzburg (قلعة الملح) وكلمة 'salary' (الراتب) كلتاهما من الملح. في ألمانيا القرون الوسطى، كان الملح ثميناً جداً حتى سمّوه 'weißes Gold' (الذهب الأبيض).",
  "the glass": "الكأس",
  "Neuter noun. Plural: die Gläser (with umlaut!).": "اسم محايد (das). الجمع: die Gläser (مع أوملاوت!).",
  "A: Can I have a glass of water?\\nB: Here, a glass of water.": "A: هل يمكنني كأس ماء؟\\nB: تفضّل، كأس ماء.",
  "'Ein Glas Wein,' 'ein Glas Bier,' 'ein Glas Wasser.' German uses 'Glas' like English uses 'glass of.' But 'Gläser' (plural) adds an umlaut. Tricky!": "'ein Glas Wein'، 'ein Glas Bier'، 'ein Glas Wasser'. الألمانية تستخدم 'Glas' كما تستخدم العربية 'كأس من'. لكن الجمع 'Gläser' يضيف أوملاوت. صعبة!",
  "the bottle": "الزجاجة",
  "Feminine noun. Plural: die Flaschen.": "اسم مؤنث (die). الجمع: die Flaschen.",
  "A: A bottle of water, please.\\nB: Sparkling or still?": "A: زجاجة ماء من فضلك.\\nB: غازي أم عادي؟",
  "Germans LOVE sparkling water. If you ask for 'Wasser' in a restaurant, you will get sparkling. Say 'stilles Wasser' for still water. The Pfand (bottle deposit) system means you return bottles for 25 cents each.": "الألمان يعشقون المياه الغازية. إذا طلبت 'Wasser' في مطعم، ستحصل على مياه غازية. قل 'stilles Wasser' للمياه العادية. نظام Pfand (تأمين الزجاجات) يعني أنك تعيد الزجاجات مقابل 25 سنتاً لكل واحدة.",
  "Think Reinheitsgebot, Oktoberfest, and 1,500 breweries.": "فكّر في Reinheitsgebot (قانون نقاء البيرة)، Oktoberfest، و1500 مصنع جعة.",
  "These small bread rolls are a breakfast staple at the Bäckerei.": "كعكات الخبز الصغيرة هذه عنصر أساسي في إفطار المخبز (Bäckerei).",
  "Two bread rolls, please. With butter and cheese.": "كعكتا خبز من فضلك. بالزبدة والجبن.",
  "This white seasoning has been called 'white gold' in history.": "هذا التابل الأبيض سُمّي 'الذهب الأبيض' عبر التاريخ.",
  "Tomorrow I go again. This time with a coin, with a bag, and with a list. I am ready. I think.": "غداً أذهب مرة أخرى. هذه المرة بقطعة نقود، وكيس، وقائمة. أنا مستعد. أظن.",
  "Shopping means numbers. Big numbers. Learn to talk about money, measurements, and everything you need to survive a German supermarket.": "التسوق يعني أرقاماً. أرقاماً كبيرة. تعلّم الحديث عن المال والمقاييس وكل ما تحتاجه للنجاة في سوبرماركت ألماني.",
  "Use large numbers: hundreds, thousands, millions": "استخدم الأعداد الكبيرة: المئات والآلاف والملايين",
  "Name coins, currencies, and measurements": "تعرّف على العملات والوحدات والمقاييس",
  "Shop for shoes, jackets, and more": "تسوّق الأحذية والسترات وغيرها",
  "Verumius writes a list. Every word with its article. Der Reis. Die Butter. Das Mehl. He practices the prices: three euros ninety. Seven seventy-five.": "فيروميوس يكتب قائمة. كل كلمة بأداتها. Der Reis. Die Butter. Das Mehl. يتدرب على الأسعار: ثلاثة يورو وتسعون. سبعة وخمسة وسبعون.",
  "the euro": "اليورو",
  "Masculine noun. Plural: die Euro (not Euros!). 'Fünf Euro, bitte.'": "اسم مذكر (der). الجمع: die Euro (وليس Euros!). 'Fünf Euro, bitte.'",
  "A: How much does that cost?\\nB: That costs three euros fifty.": "A: كم يكلف ذلك؟\\nB: يكلف ثلاثة يورو وخمسين سنتاً.",
  "the cent": "السنت",
  "Masculine noun. Plural: die Cent. 100 Cent = 1 Euro.": "اسم مذكر (der). الجمع: die Cent. مئة Cent = يورو واحد.",
  "A: Do you have fifty cents?\\nB: No, only a euro.": "A: هل عندك خمسون سنتاً؟\\nB: لا، فقط يورو واحد.",
  "The German 1-Cent coin shows an oak leaf, the 2-Cent shows a Brandenburg Gate. Most Germans want to abolish 1 and 2 Cent coins because they cost more to make than they are worth.": "عملة الـ 1 سنت الألمانية تحمل ورقة بلوط، والـ 2 سنت تحمل بوابة براندنبورغ. معظم الألمان يريدون إلغاء عملتي الـ 1 و2 سنت لأن تكلفة صنعهما أكثر من قيمتهما.",
  "Neuter noun. Plural: die Konten. From Italian 'conto.'": "اسم محايد (das). الجمع: die Konten. من الإيطالية 'conto'.",
  "A: Do you have an account at Sparkasse?\\nB: Yes, my account is at Sparkasse.": "A: هل لديك حساب في Sparkasse؟\\nB: نعم، حسابي في Sparkasse.",
  "Number. Also simply 'hundert.' 'Einhundert Euro' = 100 euros.": "عدد. أيضاً ببساطة 'hundert'. 'Einhundert Euro' = 100 يورو.",
  "A: How much does the jacket cost?\\nB: One hundred euros.": "A: كم تكلف السترة؟\\nB: مئة يورو.",
  "German numbers get interesting after 20: 'einundzwanzig' (one-and-twenty = 21). The ones digit comes BEFORE the tens. This reversal confuses every English speaker.": "الأعداد الألمانية تصبح مثيرة بعد 20: 'einundzwanzig' (واحد وعشرون = 21). رقم الآحاد يأتي قبل العشرات. هذا العكس يربك كل متحدث بالإنجليزية. لكنه مألوف في العربية!",
  "Number. Pattern: number + hundert. Dreihundert = 300.": "عدد. النمط: عدد + hundert. مثال: Dreihundert = 300.",
  "A: How much is the rent?\\nB: Two hundred euros per room.": "A: كم الإيجار؟\\nB: مئتا يورو لكل غرفة.",
  "Large German numbers are written as one word: zweihundertfünfunddreißig = 235. This is not a typo. German really does this.": "الأعداد الألمانية الكبيرة تُكتب ككلمة واحدة: zweihundertfünfunddreißig = 235. هذا ليس خطأ مطبعياً. الألمانية تفعل هذا حقاً.",
  "Number. Also simply 'tausend.' Pattern: number + tausend.": "عدد. أيضاً ببساطة 'tausend'. النمط: عدد + tausend.",
  "A: How many people live here?\\nB: One thousand in this building.": "A: كم شخصاً يعيش هنا؟\\nB: ألف في هذا المبنى.",
  "In German, the dot and comma are swapped: 1.000 = one thousand, 1,5 = one point five. This causes endless confusion with prices and bank transfers.": "في الألمانية، النقطة والفاصلة معكوستان: 1.000 = ألف، 1,5 = واحد ونصف. هذا يسبب ارتباكاً لا نهاية له مع الأسعار والتحويلات البنكية.",
  "Number. The 'en' is dropped: sieben → siebt + zig = siebzig.": "عدد. تُحذف 'en': sieben ← siebt + zig = siebzig.",
  "A: My grandpa is seventy.\\nB: Seventy? He looks young!": "A: جدي عمره سبعون.\\nB: سبعون؟ يبدو شاباً!",
  "'Siebzig' drops the 'en' from 'sieben', unlike 'siebzehn' (17) which also shortens to 'sieb.' The pattern is consistent for 7: sieben → sieb- in compounds.": "'siebzig' تحذف 'en' من 'sieben'، مثل 'siebzehn' (17) التي تختصر أيضاً إلى 'sieb'. النمط ثابت للرقم 7: sieben ← sieb- في المركبات.",
  "the million": "المليون",
  "Feminine noun. Plural: die Millionen. 'Eine Million Euro.'": "اسم مؤنث (die). الجمع: die Millionen. 'Eine Million Euro.'",
  "A: Berlin has three million inhabitants.\\nB: And Munich?": "A: برلين فيها ثلاثة ملايين نسمة.\\nB: وميونخ؟",
  "Unlike English, 'Million' is a noun in German, so it takes an article: 'eine Million.' After eine, it stays singular. After zwei+: 'zwei Millionen' (with -en).": "بخلاف الإنجليزية، 'Million' اسم في الألمانية، لذا تأخذ أداة: 'eine Million'. بعد eine تبقى مفردة. بعد zwei وما بعدها: 'zwei Millionen' (بإضافة -en).",
  "the billion (1,000,000,000)": "المليار (1,000,000,000)",
  "Feminine noun. Plural: die Milliarden. NOT 'Billion' in German!": "اسم مؤنث (die). الجمع: die Milliarden. ليست 'Billion' بالألمانية!",
  "A: Earth has eight billion people.\\nB: That is a lot of people!": "A: الأرض فيها ثمانية مليارات نسمة.\\nB: هذا عدد كبير!",
  "TRAP: German 'Billion' = English 'trillion' (1,000,000,000,000). German 'Milliarde' = English 'billion.' This causes business misunderstandings worth billions (or Milliarden).": "فخ: 'Billion' الألمانية = تريليون بالإنجليزية (1,000,000,000,000). 'Milliarde' الألمانية = مليار بالإنجليزية. هذا يسبب سوء فهم تجاري بمليارات (أو Milliarden).",
  "cold": "بارد",
  "Opposite of warm. Used for weather, food, and objects.": "عكس warm. تُستخدم للطقس والطعام والأشياء.",
  "A: Is the water cold?\\nB: Yes, very cold. Too cold!": "A: هل الماء بارد؟\\nB: نعم، بارد جداً. بارد أكثر من اللازم!",
  "Germans say 'Kaltmiete' (cold rent) for rent without utilities, and 'Warmmiete' (warm rent) for rent with utilities included. Even rent has a temperature in German.": "الألمان يقولون 'Kaltmiete' (إيجار بارد) للإيجار بدون خدمات، و'Warmmiete' (إيجار دافئ) للإيجار مع الخدمات. حتى الإيجار له درجة حرارة في الألمانية.",
  "the degree": "الدرجة",
  "Masculine noun. Plural: die Grade. For temperature and angles.": "اسم مذكر (der). الجمع: die Grade. للحرارة والزوايا.",
  "A: How warm is it?\\nB: Twenty degrees.": "A: كم الحرارة؟\\nB: عشرون درجة.",
  "the kilogram (short form)": "الكيلوغرام (الشكل المختصر)",
  "Neuter noun. Short for Kilogramm. 'Ein Kilo Äpfel, bitte.'": "اسم محايد (das). اختصار Kilogramm. 'Ein Kilo Äpfel, bitte.'",
  "A: A kilo of potatoes, please.\\nB: Here, exactly one kilo.": "A: كيلو بطاطا من فضلك.\\nB: تفضّل، كيلو بالضبط.",
  "At German markets, you buy by the Kilo (or Pfund = 500g). 'Ein halbes Kilo' = half a kilo = 500g. Supermarket scales at the fruit section are self-service.": "في الأسواق الألمانية، تشتري بالكيلو (أو Pfund = 500 غرام). 'Ein halbes Kilo' = نصف كيلو = 500 غرام. الموازين في قسم الفاكهة للخدمة الذاتية.",
  "the kilometer": "الكيلومتر",
  "Masculine noun. Plural: die Kilometer. Abbreviated: km.": "اسم مذكر (der). الجمع: die Kilometer. الاختصار: km.",
  "A: How far is it to Hamburg?\\nB: Three hundred kilometers.": "A: كم تبعد هامبورغ؟\\nB: ثلاثمئة كيلومتر.",
  "The German Autobahn has sections with NO speed limit. The recommended speed is 130 km/h, but some drivers go 200+. 'Freie Fahrt für freie Bürger' (free driving for free citizens) is an unofficial motto.": "الأوتوبان الألماني فيه مقاطع بلا حد للسرعة. السرعة الموصى بها 130 كم/ساعة، لكن بعض السائقين يتجاوزون 200. 'Freie Fahrt für freie Bürger' (قيادة حرة لمواطنين أحرار) شعار غير رسمي.",
  "the centimeter": "السنتيمتر",
  "Masculine noun. Plural: die Zentimeter. Abbreviated: cm.": "اسم مذكر (der). الجمع: die Zentimeter. الاختصار: cm.",
  "A: How tall are you?\\nB: One eighty. A hundred eighty centimeters.": "A: كم طولك؟\\nB: متر وثمانون. مئة وثمانون سنتيمتراً.",
  "Germans say height in meters: 'eins achtzig' = 1.80m. Not in feet and inches. If someone is 'eins neunzig' (1.90m), they are considered tall.": "الألمان يقولون الطول بالأمتار: 'eins achtzig' = 1.80 م. ليس بالأقدام والبوصات. إذا كان شخص 'eins neunzig' (1.90 م)، يُعتبر طويلاً.",
  "the percent": "النسبة المئوية",
  "Neuter noun. 'Zwanzig Prozent Rabatt' = 20% discount.": "اسم محايد (das). 'Zwanzig Prozent Rabatt' = خصم 20%.",
  "A: How much discount is there?\\nB: Twenty percent off everything!": "A: كم الخصم؟\\nB: عشرون بالمئة على كل شيء!",
  "German stores have two big sale seasons: Sommerschlussverkauf (summer clearance) and Winterschlussverkauf (winter clearance). Discounts of 50-70 Prozent are common.": "المتاجر الألمانية لديها موسما تخفيضات كبيران: Sommerschlussverkauf (تصفية صيفية) وWinterschlussverkauf (تصفية شتوية). خصومات 50 إلى 70 بالمئة شائعة.",
  "the part / piece": "الجزء / القطعة",
  "Masculine noun. Plural: die Teile. 'Zum Teil' = partly.": "اسم مذكر (der). الجمع: die Teile. 'Zum Teil' = جزئياً.",
  "A: That is only one part of the problem.\\nB: And the other part?": "A: هذا جزء واحد فقط من المشكلة.\\nB: والجزء الآخر؟",
  "'Teil' builds many compounds: Stadtteil (city district), Nachteil (disadvantage, literally 'night-part'), Vorteil (advantage, 'fore-part'), Urteil (judgment).": "'Teil' تبني مركبات كثيرة: Stadtteil (حي)، Nachteil (عيب، حرفياً 'جزء الليل')، Vorteil (ميزة، 'الجزء الأمامي')، Urteil (حكم).",
  "the vending machine / ATM": "آلة البيع / الصرّاف الآلي",
  "Masculine noun. Plural: die Automaten. From Greek 'automatos.'": "اسم مذكر (der). الجمع: die Automaten. من اليونانية 'automatos'.",
  "A: Where is a vending machine?\\nB: Over there, next to the door.": "A: أين آلة البيع؟\\nB: هناك، بجانب الباب.",
  "German train stations have Fahrkartenautomaten (ticket machines) that accept coins, cards, and bills. The interface is available in 10+ languages. They replace most ticket counters.": "محطات القطار الألمانية فيها Fahrkartenautomaten (آلات التذاكر) تقبل العملات والبطاقات والأوراق النقدية. الواجهة متوفرة بأكثر من 10 لغات. تحل محل معظم شبابيك التذاكر.",
  "the jacket": "السترة",
  "Feminine noun. Plural: die Jacken.": "اسم مؤنث (die). الجمع: die Jacken.",
  "A: Put on your jacket, it is cold!\\nB: I do not need a jacket.": "A: البس سترتك، الجو بارد!\\nB: لا أحتاج سترة.",
  "Germans have a saying: 'Es gibt kein schlechtes Wetter, nur schlechte Kleidung.' There is no bad weather, only bad clothing. A good Jacke solves everything.": "الألمان لديهم مقولة: 'Es gibt kein schlechtes Wetter, nur schlechte Kleidung.' لا يوجد طقس سيئ، فقط ملابس سيئة. سترة جيدة تحل كل شيء.",
  "the shoe": "الحذاء",
  "Masculine noun. Plural: die Schuhe. German shoe sizes differ from US/UK.": "اسم مذكر (der). الجمع: die Schuhe. مقاسات الأحذية الألمانية تختلف عن الأمريكية/البريطانية.",
  "A: What shoe size do you have?\\nB: Forty-two.": "A: ما مقاس حذائك؟\\nB: اثنان وأربعون.",
  "German shoe sizes: 42 = US 9 / UK 8. The system (Pariser Stich) measures in 2/3 cm increments. If someone says 'Schuhgröße 42,' they mean European 42.": "مقاسات الأحذية الألمانية: 42 = أمريكي 9 / بريطاني 8. النظام (Pariser Stich) يقيس بزيادات 2/3 سم. إذا قال شخص 'Schuhgröße 42'، يقصد المقاس الأوروبي 42.",
  "the bag / pocket": "الحقيبة / الجيب",
  "Feminine noun. Plural: die Taschen. Dual meaning!": "اسم مؤنث (die). الجمع: die Taschen. معنى مزدوج!",
  "A: Do you have a bag?\\nB: Yes, my bag is here.": "A: هل معك حقيبة؟\\nB: نعم، حقيبتي هنا.",
  "Tasche = bag AND pocket. 'Hosentasche' = pants pocket. 'Handtasche' = handbag. 'Taschenlampe' = pocket lamp (flashlight). 'Taschenbuch' = pocket book (paperback).": "Tasche = حقيبة وجيب. 'Hosentasche' = جيب البنطلون. 'Handtasche' = حقيبة يد. 'Taschenlampe' = مصباح الجيب (كشّاف). 'Taschenbuch' = كتاب الجيب (غلاف ورقي).",
  "to sell": "يبيع",
  "Inseparable prefix verb: ich verkaufe, du verkaufst. Opposite: kaufen (buy).": "فعل بسابقة غير منفصلة: ich verkaufe, du verkaufst. العكس: kaufen (يشتري).",
  "A: Do you also sell stamps?\\nB: No, only at the counter.": "A: هل تبيعون طوابع أيضاً؟\\nB: لا، فقط عند الشبّاك.",
  "'Ver-' often adds a negative or intensive meaning: kaufen (buy) vs verkaufen (sell). 'Ver-' flips the direction. Similarly: mieten (rent) vs vermieten (rent out).": "'ver-' غالباً تضيف معنى سلبياً أو مكثّفاً: kaufen (يشتري) مقابل verkaufen (يبيع). 'ver-' تعكس الاتجاه. بالمثل: mieten (يستأجر) مقابل vermieten (يؤجّر).",
  "Regular verb: ich zahle, du zahlst. 'Ich möchte zahlen' = check please.": "فعل منتظم: ich zahle, du zahlst. 'Ich möchte zahlen' = الحساب من فضلك.",
  "A: I would like to pay, please.\\nB: Cash or card?": "A: أريد أن أدفع، من فضلك.\\nB: نقداً أم بالبطاقة؟",
  "'Zahlen, bitte!' is how you ask for the check in a German restaurant. The waiter brings a portable card reader or counts change from a wallet. No bill left on the table.": "'Zahlen, bitte!' هكذا تطلب الحساب في مطعم ألماني. النادل يحضر قارئ بطاقات محمولاً أو يعدّ الباقي من محفظته. لا فاتورة تُترك على الطاولة.",
  "mostly / most": "في الغالب / الأكثر",
  "Superlative adverb. 'Meistens' = usually/most of the time.": "ظرف تفضيل. 'meistens' = عادةً / في معظم الوقت.",
  "A: What do you usually eat?\\nB: Mostly bread rolls with cheese.": "A: ماذا تأكل عادة؟\\nB: في الغالب كعكات خبز مع جبن.",
  "'Am meisten' = the most (superlative of viel). 'Meistens' = most of the time. 'Der Meister' = the master. All from the same root.": "'am meisten' = الأكثر (صيغة تفضيل viel). 'meistens' = في معظم الوقت. 'der Meister' = الأستاذ/المعلم. كلها من نفس الجذر.",
  "Germans use the metric system for height, not feet or pounds.": "الألمان يستخدمون النظام المتري للطول، لا الأقدام أو الأرطال.",
  "A number! The price is X euros and fifty cents.": "عدد! السعر X يورو وخمسون سنتاً.",
  "That costs three euros fifty.": "يكلف ثلاثة يورو وخمسين سنتاً.",
  "REWE. Red letters. Automatic doors. But this time: a coin in the pocket, a list in the hand, and a word on the lips. 'Guten Tag.'": "REWE. حروف حمراء. أبواب أوتوماتيكية. لكن هذه المرة: قطعة نقود في الجيب، وقائمة في اليد، وكلمة على الشفاه. 'Guten Tag.'"
};
