#!/usr/bin/env node
/**
 * _fix_nl_whitelist_round3.cjs
 * Adds third batch of Dutch words to the nl whitelist in pp63_audit.cjs.
 */
'use strict';
const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, 'pp63_audit.cjs');
let content = fs.readFileSync(filePath, 'utf8');

// Round 3: remaining flagged words - all legitimate Dutch discourse vocabulary
const extraWords = [
  // Proper names / proper nouns (sentence-start capitalized in examples)
  'Welkom','Fijne','George','Gotische','Leefstijl',
  // Common everyday words
  'welkom','gratis','ups','rust','ruzie',
  'pasta','rijst','risotto','soep','sap','suiker','appels',
  'piano','viool','cello','raket',
  'stoel','tafel','stoep',
  'vis','vlees','vegetarisch','vegetarische',
  'prijs','prijzen','prijzig',
  'route','routes',
  'show','shows',
  'test','tests','testte',
  'check','checken','checked',
  'scan','scannen',
  'record','records',
  'tip','tips',
  'size',
  'tablet','tabletten',
  'stream','streams',
  'startup','startups',
  // Common verb forms missed
  'vormt','vormen','vormde',
  'vormt',
  'voldoet','voldoen','voldeed',
  'volstaat','volstaan',
  'vult','vullen','vulde',
  'voeg','voegen','voegde',
  'verklaart','verklaren','verklaarde',
  'stuitte','stuiten',
  'stortte','storten',
  'steunde','steunen',
  'schudde','schudden',
  'schuimt','schuimen',
  'sloeg','slaan',
  'sms','sms\'en',
  'rukte','rukken',
  'rolde','rollen',
  'registratie','registreren',
  'gebiedt','gebieden','gebood',
  'aftreedt','aftreden',
  'wisselt','wisselen','wisselde',
  'vriest','vriezen','vroor',
  'vrolijk','vrolijke',
  // Adjectives and participials still flagged
  'protestantse','protestants',
  'zakelijke','zakelijk',
  'zorgelijke','zorgelijk',
  'tastbaar','tastbare',
  'stabiel','stabiele',
  'sceptisch','sceptische',
  'roekeloos','roekeloze',
  'retro',
  'respectvol','respectvolle',
  'religieus',
  'reëel','reele',
  'primitief','primitieve',
  'productief','productieve',
  'psychologische',
  'privé','private',
  'plantagaire',
  'sympathiek','sympathieke',
  'stijlvol','stijlvolle',
  'statistische',
  'secundaire',
  'transparant','transparante',
  'transparantie',
  'tragisch','tragische',
  'troebel','troebele',
  'triest','trieste',
  'vrijwillig','vrijwillige',
  'vredig','vredige',
  'vicieuze',
  'vlekkeloos','vlekkeloze',
  'welbespraakt',
  'wiskundig','wiskundige',
  'zielig','zielige',
  // Nouns still flagged
  'zwembril','zwembrillen',
  'zonnebrand',
  'zorgstelsel',
  'zijde','zijden',
  'zwembad',
  'zetel','zetels',
  'wonnis','vonnis','vonnissen',
  'vondst','vondsten',
  'voedselexporteur',
  'voetbalshirts',
  'vliegveld','vliegvelden',
  'vloed','vloeden',
  'volgorde',
  'uitweg',
  'uitsluitsel',
  'uitslag','uitslagen',
  'uitbraak','uitbraken',
  'uitgebuit',
  'upgrade','upgrades',
  'uur','uren',
  'vakgebied','vakgebieden',
  'variatie','variaties',
  'wekte','wekken',
  'welkom',
  'wils',
  'websites',
  'toezicht',
  'toegang','toegangen',
  'toegankelijk','toegankelijke',
  'transport','transporten',
  'tosti',
  'theologie',
  'tegels','tegel',
  'tarief','tarieven',
  'tatoeage','tatoeages',
  'tafel','tafels',
  'technologisch','technologische',
  'technologiebeurs',
  'teamprestatie',
  'telefonisch','telefonische',
  'tempranillo',
  'theologie',
  'staatsbezoek',
  'stippellijn',
  'stemgedrag',
  'stemrecht',
  'stick','sticks',
  'stijf','stijve',
  'stimulatie',
  'stoet','stoeten',
  'stonk','stinken',
  'streek','streken',
  'stroef','stroeffe',
  'studeer','studeren',
  'tabak',
  'sateh',
  'slaapzak','slaapzakken',
  'slap','slappe',
  'slechts',
  'snap','snappen',
  'sociologie',
  'spaar','sparen',
  'spam',
  'speculatie','speculaties',
  'speeches','speech',
  'spektakel',
  'spelletje','spelletjes',
  'spoed',
  'sportveld','sportvelden',
  'staar','staren',
  'stagiair','stagiaires',
  'picknick','picknicken',
  'pilsje',
  'placebo','placebos',
  'plak','plakken',
  'plantages','plantage',
  'pochet','pochets',
  'portfolio','portfolio\u2019s',
  'portie','porties',
  'pretpark','pretparken',
  'proef','proeven',
  'proefschrift',
  'proeft','proeven',
  'productie','producties',
  'publicaties','publicatie',
  'pumps',
  'puzzel','puzzels',
  'raad','raden',
  'raadsels','raadsel',
  'raadslid',
  'racket','rackets',
  'rampgebied',
  'relaties','relatie',
  'religies',
  'repetitie','repetities',
  'retorica',
  'retourtje',
  'revolutie','revoluties',
  'risotto',
  'rotonde','rotondes',
  'ruimtes',
  'pseudoniem',
  'psyche',
  'protocols','protocol',
  'procedures',
  'patroon','patronen',
  'picknick',
  'piano','piano\u2019s',
  'pasta',
  'portfolio',
  'positiefs',
  'seconde','seconden',
  'secretariaat',
  'sedum',
  'segregatie',
  'shift','shifts',
  'schaamte',
  'scheef','scheve',
  'scheert','scheren',
  'schrift','schriften',
  'gebobsleed',
  'gelvariant',
  'geschrapt',
  'gestudeerd',
  'gevaarlijkst',
  'gevelbreedte',
  'gevraagde',
  'gokprobleem',
  'golfde',
  'graphics',
  'grillig','grillige',
  'facilitaire',
  'fraudezaak',
  'dolle',
  'drs',
  'appels',
  'adobo',
  'artificiële',
  'bezochte',
  'blouse','blouses',
  'care',
  'case','cases',
  'chagrijnig','chagrijnige',
  'chic',
  'chirurgie',
  'cirkelt','cirkelen',
  'collecte','collectes',
  'een', // ensure
  'kapte','kappen',
  'news',
  '\u00e9\u00e9n',  // één
];

// Find the nl Set end and insert before it
const nlSetStart = content.indexOf("'nl': new Set([");
if (nlSetStart === -1) {
  console.log('ERROR: could not find nl Set');
  process.exit(1);
}

const nlSetEnd = content.indexOf(']),', nlSetStart);
if (nlSetEnd === -1) {
  console.log('ERROR: could not find end of nl Set');
  process.exit(1);
}

const before = content.slice(0, nlSetEnd);
const after = content.slice(nlSetEnd);

const extraStr = extraWords.map(w => "'" + w + "'").join(',');
const newContent = before + ',' + extraStr + after;

fs.writeFileSync(filePath, newContent, 'utf8');
console.log('SUCCESS: added', extraWords.length, 'extra words to nl whitelist');
console.log('New file size:', newContent.length);
