/**
 * Add trAr (Arabic translation) field to all B2 CEFR vocabulary entries
 * in src/data/cefr-reference/german.js
 *
 * Strategy: For each B2 entry, extract the primary German word from `w`,
 * look it up in the translation map, and add trAr before the closing `}`
 */

const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, '..', 'src', 'data', 'cefr-reference', 'german.js');

// Master translation map: German word (from w field) -> Arabic translation
// For multi-word garbage entries, we translate the first recognizable word
const TRANSLATIONS = {
  // Line 4760+
  "Vorstellung": "التصوّر",
  "Zitat": "الاقتباس",
  "Fernweh": "الحنين إلى السفر",
  "Arbeitsvertag": "عقد العمل",
  "auflösen": "يحلّ",
  "beantragen leichtfallen": "يتقدّم بطلب / يسهل",
  "eröffnen": "يفتتح",
  "Handyvertrag": "عقد الهاتف",
  "knüpfen": "يربط",
  "Kontakt": "الاتصال",
  "Mietvertrag": "عقد الإيجار",
  "Nachmieter": "المستأجر اللاحق",
  "abenteuerlich sehnsüchtig": "مغامر / مشتاق",
  "Arbeitserlaubnis": "تصريح العمل",
  "aufgeregt wagen": "متحمّس / يجرؤ",
  "Auslandserfahrung": "خبرة في الخارج",
  "auswandern": "يهاجر",
  "bereuen 2b empfinden": "يندم / يشعر",
  "Blog": "المدوّنة",
  "einleben": "يتأقلم",
  "Erfahrung": "الخبرة",
  "erweitern": "يوسّع",
  "gestresst": "متوتّر",
  "Landessprache": "لغة البلاد",
  "Amtssprache": "اللغة الرسمية",
  "anerkennen": "يعترف بـ",
  "Elite": "النخبة",
  "Identität": "الهوية",
  "komplex sämtlich": "معقّد / جميع",
  "konfrontieren": "يواجه",
  "multikulturell die Sprachenvielfalt": "متعدّد الثقافات / التنوّع اللغوي",
  "Parlament": "البرلمان",
  "Sachverhalt": "الوقائع",
  "trösten das Verkehrsschild": "يواسي / لافتة المرور",
  "Vertrautheit": "الألفة",
  "Verwaltungssprache": "اللغة الإدارية",
  "Vielfalt": "التنوّع",
  "vielsprachig der Wandel": "متعدّد اللغات / التحوّل",
  "Landesgesetz": "قانون البلاد",
  "Vielsprachigkeit": "تعدّد اللغات",
  "Alltagsprodukt": "منتج يومي",
  "amtlich erstaunlich": "رسمي / مذهل",
  "beherrschen": "يتقن",
  "beherrschen) hilfreich": "يتقن / مفيد",
  "Bekanntmachung": "الإعلان",
  "beschriften nützlich": "يضع ملصقاً / نافع",
  "betreffen": "يتعلّق بـ",
  "einheitlich der anderen Seite …)": "موحّد / من الجهة الأخرى",
  "fälschlicherweise die Sicht": "خطأً / وجهة النظر",
  "Flyer": "النشرة",
  "missverständlich": "ملتبس",
  "Abteil": "المقصورة",
  "missverstehen": "يُسيء الفهم",
  "missverstanden üblich": "أُسيء فهمه / معتاد",
  "peinlich 3a die Spielregel": "محرج / قاعدة اللعبة",
  "Abstand": "المسافة",
  "Art": "النوع",
  "äußerst atypisch": "بالغ / غير نمطي",
  "bedenken": "يأخذ بالاعتبار",
  "Begleiter": "المرافق",
  "breit": "عريض",
  "Freundlichkeit": "اللطف",
  "Gegenüber": "الشخص المقابل",
  "jeglich nonverbal": "أيّ / غير لفظي",
  "Lächeln": "الابتسامة",
  "Öffentlichkeit": "العلنية",
  "Chancengleichheit": "تكافؤ الفرص",
  "Migrationshintergrund": "خلفية مهاجرة",
  "Schlüsselwort": "الكلمة المفتاحية",
  "völlig inmitten": "تماماً / في وسط",
  "Kindergartenpflicht": "إلزامية رياض الأطفال",
  "Schuluniform": "الزيّ المدرسي",
  "eingehen": "يدخل في",
  "eingegangen nachdenklich": "دخل في / متأمّل",
  "Einrichtung": "المؤسسة",
  "ermöglichen die Option": "يتيح / الخيار",
  "Lehrkraft": "المعلّم",
  "Migrantenfamilie": "عائلة مهاجرة",
  "Migrantenkind": "طفل مهاجر",
  "Pate": "الكفيل",
  "Senior": "كبير السنّ",
  "sinnvoll der / Wanderarbeiter": "مجدٍ / العامل المتنقّل",
  "Zugewanderte": "المهاجر الوافد",
  "anfügen weitergegangen": "يُلحق / تابع",
  "ausbremsen die Windeseile": "يُبطئ / سرعة البرق",
  "Ausländerquote": "نسبة الأجانب",
  "Automobilhersteller": "صانع السيارات",
  "Betriebswirtschaft": "إدارة الأعمال",
  "Diskriminierung": "التمييز",
  "farbenfroh zusammengebunden": "زاهي الألوان / مربوط",
  "fernliegen": "يبعد عن",
  "Feuerholz": "حطب",
  "flechten": "يضفر",
  "geflochtener Zopf) annehmen": "ضفيرة / يقبل",
  "führen": "يقود",
  "gelegentlich einig": "أحياناً / متّفق",
  "Gemüsegeschäft": "محلّ خضار",
  "Gründer": "المؤسّس",
  "Hausverwaltung": "إدارة العقار",
  "Hochschulreife": "شهادة الثانوية العامة",
  "Abstammung": "الأصل",
  "Amateur-Boxer/in": "ملاكم هاوٍ",
  "begehrt": "مرغوب",
  "bürgerlich der / Kneipenbesitzer": "بورجوازي / صاحب الحانة",
  "Diplom": "الشهادة",
  "Drehbuchautor": "كاتب السيناريو",
  "Drehbuchpreis": "جائزة السيناريو",
  "Durchbruch": "الاختراق",
  "Einwanderer": "المهاجر",
  "entstammen das Milieu": "ينحدر من / البيئة",
  "Filmregisseur": "مخرج سينمائي",
  "Gangsterkino": "سينما العصابات",
  "geprägt": "متأثّر",
  "gläubig der / Regisseur": "مؤمن / المخرج",
  "Härte": "القسوة",
  "Hauptrolle": "الدور الرئيسي",
  "heimisch der Spielfilm": "محلّي / الفيلم الروائي",
  "Hommage": "تحيّة تقدير",
  "Juryvorsitz": "رئاسة لجنة التحكيم",
  "katholisch die Trophäe": "كاثوليكي / الكأس",
  "Kiez": "الحيّ",
  "Kinofilm": "فيلم سينمائي",
  "Kinokasse": "شبّاك التذاكر",
  "Nonsens": "الهراء",
  "unerwartet": "غير متوقّع",
  "Piktogramm": "الرسم التوضيحي",
  "Anlass": "المناسبة",
  "kommunizieren": "يتواصل",
  "ausstrecken wesentlich": "يمدّ / جوهري",
  "Auszeit": "استراحة",
  "Gebärdensprache": "لغة الإشارة",
  "Schranke": "الحاجز",
  "weisen) 3c deuten": "يشير / يدلّ",
  "Stopp": "توقّف",
  "weisen": "يشير",
  "Körpersprache": "لغة الجسد",
  "Emotion": "العاطفة",
  "Körpersignal": "إشارة جسدية",
  "verraten": "يكشف",
  "allzu feststellen": "مفرط / يكتشف",
  "anlegen": "ينشئ",
  "mehrere Sprachen zu lernen.) geduldig": "صبور",
  "auszahlen": "يدفع",
  "Autor": "المؤلّف",
  "betroffen herumschlagen": "متأثّر / يتصارع مع",
  "bilingual sich herum": "ثنائي اللغة",
  "einsprachig kinderleicht": "أحادي اللغة / سهل جداً",
  "fehlerlos das Kleinkind": "بلا أخطاء / الطفل الصغير",
  "Kompetenz": "الكفاءة",
  "Konzentrationsleistung": "أداء التركيز",
  "monolingual Kindern um?)": "أحادي اللغة",
  "nachweisen": "يثبت",
  "Phase": "المرحلة",
  "Psychologe": "عالم النفس",
  "schwerfallen": "يصعب",
  "schwergefallen werben": "صعب / يروّج",
  "Sprachenpolitik": "السياسة اللغوية",
  "Sprachentwicklung": "تطوّر اللغة",
  "Sprachschatz": "الثروة اللغوية",
  "Sprachwissenschaftler": "عالم اللغويات",
  "Startchance": "فرصة الانطلاق",
  "Trendforscher": "باحث الاتجاهات",
  "überfordern 3b das Prinzip": "يُرهق / المبدأ",
  "Basis": "الأساس",
  "entspannt ernst meinen": "مسترخٍ / يقصد بجدّية",
  "Teilthema": "موضوع فرعي",
  "gehen": "يذهب",
  "sicher gehen) die Zeiterscheinung": "يتأكّد / ظاهرة العصر",
  "gründlich 4a nichtssagend": "شامل / لا معنى له",
  "Lage": "الوضع",
  "Nummer": "الرقم",
  "gehen) 4b ratsam": "يذهب / من المستحسن",
  "Talent": "الموهبة",
  "eilig": "مستعجل",
  "austeilen": "يوزّع",
  "Berufsschule": "المدرسة المهنية",
  "draufhauen die Bank": "يضرب / المقعد",
  "einstecken": "يتحمّل",
  "Gepäckermittler": "موظّف البحث عن الأمتعة",
  "Kabarettist": "فنّان الكباريه",
  "Kritik": "النقد",
  "nehmen": "يأخذ",
  "persönlich nehmen) erzeugen": "يأخذ شخصياً / يُنتج",
  "Respekt": "الاحترام",
  "ruhig": "هادئ",
  "nicht auf.) hitzig": "حادّ الطباع",
  "touren die Konfliktlösung": "يجول / حلّ النزاع",
  "zusammengehören konkret": "ينتمي لبعض / ملموس",
  "üben": "يتدرّب",
  "aggressiv die Linie": "عدواني / الخطّ",
  "auffordern": "يطالب",
  "blamieren": "يُحرج",
  "Mitleid": "الشفقة",
  "Verbesserung": "التحسين",
  "verschuldet tatsächlich": "مديون / فعلاً",
  "hinhören der / Therapeut": "يصغي / المعالج",
  "Konsens": "الإجماع",
  "Sache": "الأمر",
  "Schwäche": "الضعف",
  "Aufgabenteilung": "توزيع المهامّ",
  "auslösen": "يُثير",
  "vorkommen": "يحدث",
  "vor.) nehmen": "يأخذ على عاتقه",
  "Vorwurf": "الاتّهام",
  "ziehen": "يسحب",
  "ziehen) der Probenraum": "يسحب / غرفة التمرين",
  "Ausgang": "المخرج",
  "Geschichte?) Rücksicht nehmen)": "يراعي",
  "nerven das Seminar": "يُزعج / الندوة",
  "Tagebuch": "اليوميات",
  "berücksichtigen der / Telefonist": "يأخذ بالاعتبار / عامل الهاتف",
  "Bibliothekar": "أمين المكتبة",
  "Cello": "التشيلّو",
  "hektisch": "محموم",
  "abgesehen": "بصرف النظر",
  "bewusst": "واعٍ",
  "brillieren": "يتألّق",
  "daherkommen": "يظهر",
  "dahergekommen smart": "ظهر / أنيق",
  "Dringlichkeit": "الإلحاح",
  "gezeichnet sein systematisch": "متأثّر / منهجي",
  "Gunst": "الحظوة",
  "hervorragend ungefragt": "ممتاز / بلا طلب",
  "Indie-Pop": "إندي بوب",
  "klatschen der Walzer": "يصفّق / الفالس",
  "Komponist": "المؤلّف الموسيقي",
  "Last": "العبء",
  "Macht": "السلطة",
  "haben) obligatorisch": "إلزامي",
  "blitzen stürmen": "يبرق / يعصف",
  "gewittern ziehen": "يرعد / يتحرّك",
  "hageln bitte das Fenster zu.)": "يبرد / أغلق النافذة",
  "Bestandteil": "العنصر",
  "betreiben": "يُدير",
  "Blogger": "المدوّن",
  "durchhalten": "يصمد",
  "Geruchssinn": "حاسّة الشمّ",
  "Handwerk": "الحرفة",
  "hängen": "يعلّق",
  "den Nagel hängen) dekorieren": "يعلّق / يزيّن",
  "hauptberuflich drauf": "كمهنة أساسية",
  "Hautcreme": "كريم البشرة",
  "kreieren einsehen": "يبتكر / يدرك",
  "Lifestyle": "نمط الحياة",
  "Mode": "الموضة",
  "Nagel": "المسمار",
  "Nervenkitzel": "الإثارة",
  "Parfümeur": "صانع العطور",
  "Fingerspitzengefühl": "الحسّ المرهف",
  "Genauigkeit": "الدقّة",
  "Geschick": "المهارة",
  "handwerklich restaurieren": "حرفي / يرمّم",
  "Innenarchitektur": "التصميم الداخلي",
  "Klavierbauer": "صانع البيانو",
  "Konzertpianist": "عازف بيانو محترف",
  "Stellenanzeige": "إعلان وظيفي",
  "Bauzeichner": "رسّام معماري",
  "Bürokauffrau": "موظّفة مكتب",
  "Informatiker": "عالم الحاسوب",
  "Jurist": "قانوني",
  "Praktikumsbörse": "بورصة التدريب",
  "Schneider": "الخيّاط",
  "Nebenjob": "عمل جانبي",
  "Absage": "الرفض",
  "Berufserfahrung": "الخبرة المهنية",
  "aufreiben": "يستنزف",
  "erfüllen": "يحقّق",
  "Erwartung": "التوقّع",
  "rein": "صافٍ",
  "überlastet kooperativ": "مُثقل / تعاوني",
  "Vergnügen": "المتعة",
  "angestellt": "موظّف",
  "drei Monaten bei der Firma fest locken": "ثابت في الشركة / يغري",
  "angestellt.) lösen": "موظّف / يحلّ",
  "Ansehen": "السمعة",
  "anspruchsvoll der / Manager": "متطلّب / المدير",
  "Arbeitslose": "العاطل عن العمل",
  "Arbeitsumfeld": "بيئة العمل",
  "ausgehen": "ينطلق",
  "ausgegangen": "انطلق",
  "richtige Job glücklich machen kann.)": "الوظيفة المناسبة",
  "ausüben": "يمارس",
  "Ausweg": "المخرج",
  "Banklehre": "التدريب المصرفي",
  "Befragte": "المستطلَع",
  "besagen": "يفيد",
  "beschäftigen": "يُشغّل",
  "anspruchsvollen Aufgaben.) stattdessen": "بدلاً من ذلك",
  "bewältigen der Stellenwechsel": "يتغلّب على / تغيير الوظيفة",
  "Dauer": "المدّة",
  "demotivieren unverzichtbar": "يُحبط / لا غنى عنه",
  "Druck": "الضغط",
  "eingestehen": "يعترف",
  "sich eingestanden": "اعترف لنفسه",
  "eingestehen) wirtschaftlich": "يعترف / اقتصادي",
  "erhöhen die Zufriedenheit": "يرفع / الرضا",
  "fachlich 3 die Wichtigkeit": "تخصّصي / الأهمية",
  "Finanzkrise": "الأزمة المالية",
  "Teamgeist": "روح الفريق",
  "doof umrunden": "غبي / يطوف حول",
  "Event": "الحدث",
  "Abfahrt": "المغادرة",
  "Freizeitkleidung": "ملابس غير رسمية",
  "Geschäftsleitung": "إدارة الشركة",
  "Grillmeister": "خبير الشواء",
  "machen": "يفعل",
  "nahegelegen die Teambildungsaktivität": "قريب / نشاط بناء الفريق",
  "rudern": "يجدّف",
  "Absprache": "الاتفاق",
  "Ausarbeitung": "الإعداد",
  "Auslandssemester": "فصل دراسي في الخارج",
  "Bachelor": "البكالوريوس",
  "Bachelorarbeit": "رسالة البكالوريوس",
  "Betreuung": "الإشراف",
  "Bewerbungstrainer": "مدرّب التقديم للوظائف",
  "Catering": "خدمة الطعام",
  "Datumsangabe": "تحديد التاريخ",
  "Dokument": "المستند",
  "Durchführung": "التنفيذ",
  "EDV-Kenntnisse": "معرفة الحاسوب",
  "Eventmanagement": "إدارة الفعاليات",
  "Highlight": "أبرز حدث",
  "Kalkulation": "الحساب",
  "Kenntnis": "المعرفة",
  "Konzeption": "التصميم",
  "Koordination": "التنسيق",
  "Management": "الإدارة",
  "Messecatering": "خدمة طعام المعارض",
  "Mitarbeit": "المشاركة",
  "Nationalität": "الجنسية",
  "Neukundengewinnung": "استقطاب عملاء جدد",
  "Organisation": "التنظيم",
  "Persönlichkeitstraining": "تدريب الشخصية",
  "Präsentationssoftware": "برنامج العروض التقديمية",
  "Projektleitung": "إدارة المشروع",
  "Rechtschreibfehler": "خطأ إملائي",
  "seriös": "جادّ",
  "Spalte": "العمود",
  "zweite Spalte der Tabelle.) die Erfahrung": "العمود الثاني / الخبرة",
  "Sprachkenntnisse": "المهارات اللغوية",
  "Start-up": "شركة ناشئة",
  "übersichtlich liegen": "واضح / يقع",
  "Veranstaltungskonzept": "مفهوم الفعالية",
  "verhandlungssicher": "قادر على التفاوض",
  "verhandlungssicher.) das Unternehmen": "متمكّن من التفاوض / الشركة",
  "Verkaufsassistent": "مساعد مبيعات",
  "wirkungsvoll das Vorstellungsgespräch": "فعّال / مقابلة العمل",
  "Zusammenhang": "السياق",
  "EDV": "تقنية المعلومات",
  "informativ die Schlussformel": "إعلامي / الخاتمة",
  "jetzig die Vorliebe": "حالي / التفضيل",
  "Wechsel": "التغيير",
  "Anschrift": "العنوان",
  "Betreffzeile": "سطر الموضوع",
  "Bewerbungsbrief": "رسالة التقديم",
  "Anbau": "البناء الملحق",
  "Arbeitsmarkt": "سوق العمل",
  "Aufsehen": "الضجّة",
  "ausgesprochen": "واضح",
  "ist ausgesprochen groß.) das Lob": "واضح جداً / المديح",
  "avancieren": "يرتقي",
  "Baumwolle": "القطن",
  "Bekleidung": "الملابس",
  "Billiglohnland": "بلد الأجور المنخفضة",
  "Biobaumwolltasche": "حقيبة قطن عضوي",
  "erregen": "يثير",
  "Garn": "الخيط",
  "gefragt sein die Transparenz": "مطلوب / الشفافية",
  "Gerechtigkeitssinn": "حسّ العدالة",
  "Geschäftsführer": "المدير التنفيذي",
  "Gewerkschaft": "النقابة",
  "Grundvoraussetzung": "الشرط الأساسي",
  "herstellen verzweifelt": "يصنع / يائس",
  "hierzulande die Werbeagentur": "في هذا البلد / وكالة الإعلان",
  "hofieren zutrauen": "يتودّد / يثق بـ",
  "final": "نهائي",
  "Komma": "الفاصلة",
  "Cartoon": "الرسوم المتحرّكة",
  "Gewalt": "العنف",
  "Ärger": "الغضب",
  "bauen": "يبني",
  "begründen das Hausverbot": "يبرّر / حظر الدخول",
  "beibringen": "يعلّم",
  "Dach": "السقف",
  "haben) die Kids": "الأطفال",
  "Diebstahl": "السرقة",
  "Disziplin": "الانضباط",
  "Eintragung": "التسجيل",
  "erneut vertreiben)": "مجدّداً / يطرد",
  "erwischen der Liegestütz": "يمسك / تمرين الضغط",
  "Faust": "القبضة",
  "fluchen motiviert": "يسبّ / محفَّز",
  "Führungszeugnis": "شهادة حسن السلوك",
  "randalieren vertreiben": "يشاغب / يطرد",
  "regelmäßig Langeweile vertreiben)": "بانتظام / يقضي على الملل",
  "respektieren die Waffe": "يحترم / السلاح",
  "Sachbeschädigung": "إتلاف الممتلكات",
  "schnappen 1c machtlos": "يقبض على / عاجز",
  "schwach": "ضعيف",
  "Selbstbeherrschung": "ضبط النفس",
  "Sicherheitsleiter": "مسؤول الأمن",
  "sprühen": "يرشّ",
  "stärken ganz nach den Wünschen meiner": "يقوّي",
  "stellen": "يضع",
  "Taekwondo": "التايكوندو",
  "tatenlos sich angeschlossen": "بلا حراك / انضمّ",
  "treiben": "يمارس",
  "übergeben": "يسلّم",
  "übergibt die Jugendlichen der Polizei.) erschreckend": "يسلّم / مرعب",
  "verbauen": "يسدّ",
  "bringen)": "يجلب",
  "abgeben": "يسلّم",
  "gegen eine niedrige Gebühr abgeben) erstrebenswert": "يسلّم مقابل رسوم / جدير بالسعي",
  "akut erwerben": "حادّ / يكتسب",
  "anbringen": "يثبّت",
  "angebracht.) folglich": "ملائم / بالتالي",
  "anerkannt": "معترف به",
  "Arbeitslohn": "الأجر",
  "Asylberechtigte": "صاحب حقّ اللجوء",
  "aufbereiten": "يعالج",
  "gereinigt und wieder aufbereitet.) gedacht": "نظّف وأعيد تدويره / مقصود",
  "Aufruf": "النداء",
  "Auftakt": "الافتتاح",
  "ausgeliefert sein das Gelände": "مسلَّم لـ / الأرض",
  "Ausgrenzung": "الإقصاء",
  "ausmachen": "يشكّل",
  "ausreichen haben)": "يكفي",
  "Auswirkung": "التأثير",
  "bedürftig": "محتاج",
  "Bedürftige": "المحتاج",
  "Bestellung": "الطلب",
  "Bettzeug": "أغطية السرير",
  "Bevölkerungswachstum": "النموّ السكاني",
  "Bildungsabschluss": "المؤهّل الدراسي",
  "Bildungschance": "فرصة التعليم",
  "Bildungserfolg": "النجاح التعليمي",
  "Bildungserwartung": "التوقّعات التعليمية",
  "definieren die Lebenslage": "يعرّف / الوضع المعيشي",
  "Dürreperiode": "فترة الجفاف",
  "einwerfen": "يلقي",
  "Post im Briefkasten ein.) das Lernmaterial": "يلقي البريد / المواد التعليمية",
  "Entstehung": "النشأة",
  "Epidemie": "الوباء",
  "erachten": "يعتبر",
  "erfassen die Naturkatastrophe": "يرصد / الكارثة الطبيعية",
  "erhalten": "يحافظ على",
  "erhaltene Kleidungsstücke) das Portemonnaie": "قطع الملابس / المحفظة",
  "problemlos steigern": "بلا مشاكل / يزيد",
  "richten": "يوجّه",
  "schätzen": "يقدّر",
  "Schulzeit": "فترة الدراسة",
  "schutzlos der Vortrag": "بلا حماية / المحاضرة",
  "Sozialhilfeempfänger": "متلقّي المساعدة الاجتماعية",
  "Spende": "التبرّع",
  "spenden die Zuneigung": "يتبرّع / المودّة",
  "Spendenbereitschaft": "الاستعداد للتبرّع",
  "Stand": "المستوى",
  "mit dem Stand der Familie zusammen.)": "مع مستوى العائلة",
  "Behandlungsmöglichkeit": "خيار العلاج",
  "Merkmal": "السمة",
  "Onlinesucht": "إدمان الإنترنت",
  "Sucht": "الإدمان",
  "Suchtkrankheit": "مرض الإدمان",
  "anstellen": "يوظّف",
  "Computerspielsucht": "إدمان ألعاب الحاسوب",
  "ergreifen": "يتّخذ",
  "ergreifen) zugrunde liegen": "يتّخذ / يكمن وراء",
  "Parallelwelt": "عالم موازٍ",
  "versetzen": "ينقل",
  "virtuell kommen)": "افتراضي",
  "kommen)": "يأتي",
  "Kamm": "المشط",
  "scheren) der Lebensentwurf": "يقصّ / مشروع الحياة",
  "pauschalisieren der Lebensverlauf": "يعمّم / مسار الحياة",
  "prinzipiell mehrheitlich": "مبدئياً / بالأغلبية",
  "scheren": "يقصّ",
  "verallgemeinern orientiert": "يعمّم / موجَّه",
  "Klischee": "الصورة النمطية",
  "abweichen": "ينحرف",
  "Alleinernährer": "المعيل الوحيد",
  "Balance": "التوازن",
  "Bein": "الساق",
  "bemerkenswert eigenen Beinen stehen)": "جدير بالملاحظة / يقف على قدميه",
  "bleiben": "يبقى",
  "Erwerbsarbeit": "العمل المأجور",
  "Erwerbstätigkeit": "النشاط المهني",
  "Familiengründung": "تأسيس عائلة",
  "Frauensache": "شأن المرأة",
  "Frauenzeitschrift": "مجلّة نسائية",
  "Gebildete": "المثقّف",
  "gefährdet der Wert": "مهدَّد / القيمة",
  "hinauszögern Werten und Einstellungen ab.)": "يؤجّل / قيم ومواقف",
  "insbesondere der Wertewandel": "بالأخصّ / تحوّل القيم",
  "Kindererziehung": "تربية الأطفال",
  "kinderfeindlich zeitintensiv": "معادٍ للأطفال / يستغرق وقتاً",
  "zurückhaltend 5d übertrieben": "متحفّظ / مبالغ فيه",
  "zuversichtlich 6b ablegen": "متفائل / يخلع",
  "Lauf": "الجري",
  "auffällig": "لافت",
  "holen": "يحضر",
  "Rat": "النصيحة",
  "Comic": "القصّة المصوّرة",
  "Kabarett": "الكباريه",
  "Gewohnheit": "العادة",
  "Schwiegermutter": "الحماة",
  "Macke": "الغرابة",
  "benachteiligt": "محروم",
  "Beratungsagentur": "وكالة استشارية",
  "bestechend": "مبهر",
  "einfach.) qualitativ": "ببساطة / نوعي",
  "Betreiber": "المشغّل",
  "Bundesverband": "الاتحاد الفيدرالي",
  "bundesweit samt": "على مستوى البلاد / مع",
  "einwandfrei sicherstellen": "بلا عيب / يضمن",
  "Geringverdiener": "ذو الدخل المنخفض",
  "grundsätzlich stecken": "أساساً / يكمن",
  "Handelsunternehmen": "شركة تجارية",
  "Helfer": "المساعد",
  "Informationsmaterial": "مواد إعلامية",
  "Infrastruktur": "البنية التحتية",
  "Kfz-Betrieb": "ورشة سيارات",
  "kinderreich Verband.)": "كثير الأطفال / الاتحاد",
  "Know-how": "الخبرة العملية",
  "Kraftstoff": "الوقود",
  "Kühlfahrzeug": "مركبة مبرّدة",
  "Kühlraum": "غرفة التبريد",
  "Lagerhaltung": "التخزين",
  "Leben": "الحياة",
  "Milchprodukt": "منتج ألبان",
  "Acht": "الحذر",
  "Anfang": "البداية",
  "Beachtung": "الاهتمام",
  "Fairness": "الإنصاف",
  "Flucht": "الهروب",
  "Benzinmotor": "محرّك بنزين",
  "Längeneinheit": "وحدة الطول",
  "Mittelalter": "العصور الوسطى",
  "Flügel": "الجناح",
  "Hieroglyphe": "الهيروغليفية",
  "Kalorie": "السعرة الحرارية",
  "Keilschrift": "الكتابة المسمارية",
  "ausgewechselt": "مُستبدَل",
  "verhalten) klagen": "يتصرّف / يشتكي",
  "bestmöglich die Konzentration": "أفضل ما يمكن / التركيز",
  "entfalten": "ينمّي",
  "lenken": "يوجّه",
  "Lippe": "الشفة",
  "Weiche": "المفترق",
  "stellen) naturwissenschaftlich": "يضع / علمي طبيعي",
  "abbauen": "يُزيل",
  "absolvieren das Phänomen": "ينجز / الظاهرة",
  "analytisch": "تحليلي",
  "außergewöhnlich qualifizieren": "استثنائي / يؤهّل",
  "Becher": "الكوب",
  "Berufsentscheidung": "قرار مهني",
  "einstellen": "يوظّف",
  "über Nacht ein.) schrumpfen": "بين ليلة وضحاها / يتقلّص",
  "Experiment": "التجربة",
  "experimentieren stellen": "يجرّب / يضع",
  "Forschungseinrichtung": "مؤسسة بحثية",
  "geben": "يعطي",
  "geben) das Umfeld": "يعطي / المحيط",
  "Gießkanne": "إبريق الريّ",
  "heranführen": "يقرّب إلى",
  "Ingenieurwissenschaft": "علم الهندسة",
  "Initiative": "المبادرة",
  "Kindergartenalter": "سنّ الروضة",
  "Erfinder": "المخترع",
  "Notlüge": "الكذبة البيضاء",
  "Schneeball": "كرة الثلج",
  "wälzen die Psyche": "يقلّب / النفس",
  "Sprichwort": "المثل",
  "abstrakt regulieren": "مجرّد / ينظّم",
  "akustisch schwindeln": "سمعي / يكذب",
  "Artgenosse": "فرد من النوع",
  "Bekanntschaft": "المعرفة",
  "Bewertung": "التقييم",
  "dermaßen": "لدرجة",
  "dass niemand ihm glaubt.) verarbeiten": "لا أحد يصدّقه / يعالج",
  "ertragen": "يتحمّل",
  "erwecken verfügen": "يوقظ / يملك",
  "glaubwürdig": "موثوق",
  "greifen": "يمسك",
  "ignorieren die Versuchsreihe": "يتجاهل / سلسلة التجارب",
  "intellektuell das Warnsignal": "فكري / إشارة التحذير",
  "Kandidat": "المرشّح",
  "Kommunikationsmittel": "وسيلة اتصال",
  "Kompliment": "المجاملة",
  "kontinuierlich 3 der Bescheid": "مستمرّ / الإشعار",
  "kurzfristig die Besprechung": "قصير المدى / الاجتماع",
  "längerfristig mit dem Chef)": "طويل المدى / مع المدير",
  "Lügengeschichte": "قصّة كاذبة",
  "Kundengespräch": "محادثة مع العميل",
  "Mitbewohner": "شريك السكن",
  "Schulden": "الديون",
  "Strauß": "الباقة",
  "unpassend": "غير مناسب",
  "ansiedeln": "يستوطن",
  "Atomenergie": "الطاقة النووية",
  "Atomkraftwerk": "محطّة طاقة نووية",
  "Atommeiler": "المفاعل النووي",
  "Aufbau": "البناء",
  "aufhalten": "يوقف",
  "auftanken die Pumpe": "يعبّئ الوقود / المضخّة",
  "ausfallen": "يتعطّل",
  "ausgefallen.) romantisch": "تعطّل / رومانسي",
  "auskommen": "يكتفي بـ",
  "Bahn": "السكّة الحديدية",
  "Bakterie": "البكتيريا",
  "Bauwerk": "المبنى",
  "bedroht stimmen": "مهدَّد / يجعل",
  "Blei": "الرصاص",
  "Damm": "السدّ",
  "deprimierend der / Techniker": "محبط / الفنّي",
  "dramatisch der Tunnel": "دراماتيكي / النفق",
  "einstürzen der Überblick": "ينهار / النظرة العامّة",
  "Forscher": "الباحث",
  "gesamt überleben": "إجمالي / ينجو",
  "geschützt der Überrest": "محميّ / البقايا",
  "Gewinner": "الفائز",
  "Griff": "المقبض",
  "Grundwasser": "المياه الجوفية",
  "hinterlassen": "يترك",
  "intakt die Vision": "سليم / الرؤية",
  "Kakerlake": "الصرصور",
  "Kämpfer": "المقاتل",
  "Kraftwerk": "محطّة الطاقة",
  "Kühlsystem": "نظام التبريد",
  "langlebig 1d übereinstimmen": "طويل العمر / يتّفق",
  "Laus": "القملة",
  "Notversorgung": "الإمداد الطارئ",
  "ausschlafen": "ينام كفاية",
  "ausgeschlafen dauerhaft": "نشيط / دائم",
  "dösen durcharbeiten": "يغفو / يعمل متواصلاً",
  "Murmeltier": "الغرير",
  "Nickerchen": "القيلولة",
  "Allesfresser": "حيوان قارت",
  "arg eintauchen": "شديد / يغوص",
  "ausreichend der / Feind": "كافٍ / العدوّ",
  "Ausweis": "البطاقة",
  "durchzuarbeiten gilt als Ausweis der / Gealterte": "العمل المتواصل / المسنّ",
  "besonderer Leistungsfähigkeit.) gehoben": "أداء مميّز / راقٍ",
  "Beleg": "الإيصال",
  "Bettflüchter": "من يستيقظ باكراً",
  "gleichermaßen 3a die Gymnastik": "بالتساوي / الجمباز",
  "global das Herzproblem": "عالمي / مشكلة القلب",
  "hemmen der Mittagsschlaf": "يكبح / قيلولة الظهر",
  "Herzinfarkt": "النوبة القلبية",
  "Hirn": "الدماغ",
  "kahl 3b das Fazit": "أصلع / الخلاصة",
  "Konkurrenz": "المنافسة",
  "Lebenskunst": "فنّ الحياة",
  "Leistungsfähigkeit": "القدرة على الأداء",
  "Markt": "السوق",
  "Matratze": "المرتبة",
  "Mediziner": "الطبيب",
  "Ministerpräsident": "رئيس الوزراء",
  "Mittagsschläfchen": "قيلولة قصيرة",
  "mittelalterlich betonen": "قروسطي / يشدّد على",
  "Mitternacht": "منتصف الليل",
  "müdegearbeitet derzeit": "مُرهَق / حالياً",
  "Nachteule": "البومة الليلية",
  "ohnehin der Kulturwandel": "على أيّ حال / التحوّل الثقافي",
  "Organ": "العضو",
  "Partylöwe": "محبّ الحفلات",
  "preisen": "يمدح",
  "preisen ihre Produkte.) der Leserbrief": "يمدح منتجاته / رسالة القارئ",
  "Pubertierende": "المراهق",
  "rastlos der Schlafraum": "لا يهدأ / غرفة النوم",
  "ruhen das Service-Unternehmen": "يستريح / شركة الخدمات",
  "Schläfchen": "غفوة",
  "Schlaflabor": "مختبر النوم",
  "schlaflos die Tatsache": "بلا نوم / الحقيقة",
  "Schlafmangel": "نقص النوم",
  "Schlafstörung": "اضطراب النوم",
  "Schnitt": "المعدّل",
  "Schreibtischplatte": "سطح المكتب",
  "Seele": "الروح",
  "solide der Ruheraum": "متين / غرفة الراحة",
  "tagsüber 6b einverstanden sein": "نهاراً / يوافق",
  "verpennen kommen": "يفوته النوم / يأتي",
  "Verschwendung": "الهدر",
  "vorbildlich realisieren": "مثالي / يحقّق",
  "Zeitalter": "العصر",
  "zufolge": "وفقاً لـ",
  "ankündigen erhalten": "يعلن / يتلقّى",
  "Atombombe": "القنبلة النووية",
  "aufgeben": "يتخلّى",
  "seine deutsche Nationalität auf und wird Expedition begeben)": "يتخلّى عن جنسيته / البعثة",
  "aufrufen": "يدعو",
  "Beitrag": "المساهمة",
  "beleuchten": "يسلّط الضوء",
  "beleuchten) das Hauptwerk": "يسلّط الضوء / العمل الرئيسي",
  "bemühen": "يسعى",
  "Effekt": "التأثير",
  "eigensinnig inhaltlich": "عنيد / من حيث المحتوى",
  "Einsatz": "الاستخدام",
  "Elektrizität": "الكهرباء",
  "erfolglos langwierig": "فاشل / طويل",
  "maßgeblich die Richtigkeit": "حاسم / الصحّة",
  "Meinungsfreiheit": "حرّية الرأي",
  "Militarisierung": "التسليح",
  "Nationalsozialismus": "النازية",
  "Nationalsozialist": "النازي",
  "Nobelpreis": "جائزة نوبل",
  "Nobelpreisträger": "الحائز على جائزة نوبل",
  "Pazifismus": "السلمية",
  "Pflichtveranstaltung": "فعالية إلزامية",
  "physikalisch verleihen": "فيزيائي / يمنح",
  "Physiker": "الفيزيائي",
  "Präsident": "الرئيس",
  "Preis": "الجائزة",
  "publizieren die Vortragsreihe": "ينشر / سلسلة المحاضرات",
  "Rahmen": "الإطار",
  "bestätigt.) wenden": "مؤكَّد / يتوجّه",
  "revolutionieren": "يُحدث ثورة في",
  "Vordergrund": "المقدّمة",
  "Vorgang": "العملية",
  "kurios der Diamant": "غريب / الألماس",
  "Oberbegriff": "المصطلح الشامل",
  "Schwager": "صهر",
  "Silber": "الفضّة",
  "Analogie": "القياس",
  "Onlineeinkauf": "التسوّق الإلكتروني",
  "Benutzerkonto": "حساب المستخدم",
  "Browser": "المتصفّح",
  "Datenschutz": "حماية البيانات",
  "Doppelklick": "النقر المزدوج",
  "Firewall": "جدار الحماية",
  "Konsument": "المستهلك",
  "Kontodaten": "بيانات الحساب",
  "Onlinebanking": "الخدمات المصرفية عبر الإنترنت",
  "Passwort": "كلمة المرور",
  "Rechnungsbetrag": "مبلغ الفاتورة",
  "Startseite": "الصفحة الرئيسية",
  "Suchmaschine": "محرّك البحث",
  "Verschlüsselung": "التشفير",
  "Virenschutzprogramm": "برنامج مكافحة الفيروسات",
  "Virus": "الفيروس",
  "Ratgebersendung": "برنامج نصائح",
  "Anprobe": "التجربة",
  "Bequemlichkeit": "الراحة",
  "Kreditkartenbetrug": "احتيال بطاقة الائتمان",
  "Lieferzeit": "مدّة التوصيل",
  "Mindestbestellwert": "الحدّ الأدنى للطلب",
  "Preisvergleich": "مقارنة الأسعار",
  "Produktbeschreibung": "وصف المنتج",
  "Reklamation": "الشكوى",
  "eingeben": "يُدخل",
  "Geschäftsbedingungen": "شروط العمل",
  "Anrufer": "المتّصل",
  "Coach": "المدرّب",
  "Auskunft": "المعلومات",
  "ausrichten": "يبلّغ",
  "etwas ausrichten?) die Zusammenfassung": "يبلّغ / الملخّص",
  "Diagramm": "الرسم البياني",
  "Durchwahl": "الرقم الداخلي",
  "festhalten": "يتمسّك بـ",
  "Rückversicherung": "إعادة التأمين",
  "verbleiben": "يبقى",
  "verbleiben wir also so": "نتّفق إذاً على ذلك",
  "Benehmen": "السلوك",
  "Hilfsbereitschaft": "الاستعداد للمساعدة",
  "Höflichkeit": "الأدب",
  "Kommunikationsfähigkeit": "مهارة التواصل",
  "Kritikfähigkeit": "القدرة على تقبّل النقد",
  "Offenheit": "الانفتاح",
  "Teamfähigkeit": "القدرة على العمل الجماعي",
  "Wertschätzung": "التقدير",
  "anerkennend reden)": "يتحدّث بتقدير",
  "Arbeitsatmosphäre": "جوّ العمل",
  "Arbeitsklima": "مناخ العمل",
  "kann viel ausmachen.) die Veränderung": "يحدث فرقاً / التغيير",
  "befehlen": "يأمر",
  "Bereitschaft": "الاستعداد",
  "bewirken der Vorzug": "يُحدث / الميزة",
  "Diskussionsbedarf": "الحاجة للنقاش",
  "entgegenbringen": "يُبدي",
  "entgegengebracht": "أُبدي",
  "entgegenbringen) 2a die Stellungnahme": "يُبدي / الموقف",
  "Feedback": "التعليقات",
  "freundschaftlich vorkommen": "ودّي / يبدو",
  "geben) in dieses Team passen.)": "ينسجم مع الفريق",
  "geben) benehmen": "يعطي / يتصرّف",
  "gestalten benommen": "يصمّم / مذهول",
  "klären": "يوضّح",
  "Konfliktpotential": "احتمال النزاع",
  "Konzept": "المفهوم",
  "einprägen": "يحفظ",
  "einteilen": "يقسّم",
  "gönnen bewusst": "يمنح / بوعي",
  "Prüfungsangst": "رهبة الامتحان",
  "dran": "حانت نوبته",
  "Lernphase": "مرحلة التعلّم",
  "einplanen der Traubenzucker": "يخطّط لـ / سكّر العنب",
  "entgegensehen": "يتوقّع",
  "entgegengesehen": "توقّع",
  "entgegensehen)": "يتوقّع",
  "fallen": "يسقط",
  "fallen) verschaffen": "يسقط / يوفّر",
  "geben) verunsichern": "يعطي / يزعزع",
  "Gesamtwiederholung": "المراجعة الشاملة",
  "klarmachen": "يوضّح",
  "konstant": "ثابت",
  "Korrektur": "التصحيح",
  "Lernstoff": "المادّة الدراسية",
  "meiden": "يتجنّب",
  "Mühe": "الجهد",
  "Musterklausur": "امتحان نموذجي",
  "nachhaken das Lager": "يتابع / المخزن",
  "Nervosität": "التوتّر",
  "Prüfer": "الممتحِن",
  "Puffertag": "يوم احتياطي",
  "rechtzeitig umgangssprachlich": "في الوقت المناسب / عامّي",
  "schlimmstenfalls 4c der Terminvorschlag": "في أسوأ الأحوال / اقتراح الموعد",
  "angewiesen sein": "يعتمد على",
  "Bundespolizei": "الشرطة الاتحادية",
  "Jugendbereich": "قسم الشباب",
  "Kader": "الكوادر",
  "Kartrennen": "سباق الكارت",
  "kommen": "يأتي",
  "kommen) der Rollstuhl": "يأتي / الكرسي المتحرّك",
  "Kunstturnen": "الجمباز الفنّي",
  "Kunstturner": "لاعب الجمباز",
  "Lebensjahr": "سنة العمر",
  "Monoski": "التزلّج الأحادي",
  "Monoskibobfahrer": "متزلّج أحادي",
  "Nationalmannschaft": "المنتخب الوطني",
  "voranstellen": "يقدّم",
  "Kunstwerk": "العمل الفنّي",
  "Weltkulturerbe": "التراث الثقافي العالمي",
  "schützenswert das Hofzeremoniell": "جدير بالحماية / مراسم البلاط",
  "Audioguide": "الدليل الصوتي",
  "besteigen": "يصعد",
  "einführen": "يُدخل",
  "Giraffe": "الزرافة",
  "Gitter": "الشبكة",
  "Regierungszeit": "فترة الحكم",
  "Schlossbesichtigung": "زيارة القصر",
  "Schlossgarten": "حديقة القصر",
  "Schulpflicht": "إلزامية التعليم",
  "Staatsgeschäfte": "شؤون الدولة",
  "Thron": "العرش",
  "Tiergarten": "حديقة الحيوان",
  "Tiergehege": "حظيرة الحيوانات",
  "Kaiser": "الإمبراطور",
  "Anlage": "المنشأة",
  "entstehen": "ينشأ",
  "Kunstraub": "سرقة الأعمال الفنّية",
  "annehmen": "يفترض",
  "aufsehenerregend das Lösegeld": "مثير / الفدية",
  "Bande": "العصابة",
  "basieren": "يستند إلى",
  "Besucherzelle": "زنزانة الزوّار",
  "Einbruch": "السطو",
  "expressionistisch 3a ausrauben": "تعبيري / يسرق",
  "fassen": "يقبض على",
  "filmreif entführen": "سينمائي / يختطف",
  "Gemälde": "اللوحة",
  "gestehen": "يعترف",
  "Ich-Erzähler/in": "الراوي بصيغة المتكلّم",
  "Idiot": "الأحمق",
  "knurren der / Kommissar": "يتذمّر / المحقّق",
  "Nerv": "العصب",
  "nicht mehr mit.) 3c die Aufklärung": "التوضيح",
  "Notizblock": "دفتر الملاحظات",
  "rechnen": "يحسب",
  "runterfallen": "يسقط",
  "schlagartig schlagen": "فجأة / يضرب",
  "schwitzen Herz schlägt ganz schnell)": "يعرق / القلب ينبض بسرعة",
  "Verdächtige": "المشتبه به",
  "erpressen wegbleiben": "يبتزّ / يغيب",
  "Erpressung": "الابتزاز",
  "Gehilfe": "المساعد",
  "Gemälderaub": "سرقة اللوحات",
  "Gericht": "المحكمة",
  "eine Sprache stirbt.) die Fantasiewelt": "عالم الخيال",
  "anpassen": "يتكيّف",
  "aussterben": "ينقرض",
  "Bedeutungsnuance": "فارق المعنى",
  "Bedeutungsverlust": "فقدان المعنى",
  "Einfluss": "التأثير",
  "Einzelfall": "حالة فردية",
  "Organismus": "الكائن الحيّ",
  "Roboter": "الروبوت",
  "Sprachensterben": "انقراض اللغات",
  "Sprachforscher": "باحث لغوي",
  "Stamm": "القبيلة",
  "Tierspur": "أثر الحيوان",
  "Todesurteil": "حكم الإعدام",
  "übersetzbar 4 bestehen": "قابل للترجمة / يتكوّن",
  "Übertragung": "النقل",
  "überwiegend 5 der Dialekt": "غالباً / اللهجة",
  "Verbreitung": "الانتشار",
  "Abenteuerlust": "حبّ المغامرة",
  "an sich": "بحدّ ذاته",
  "übertrieben.) aufgeschwungen": "مبالغ فيه",
  "ausgewogen äußere": "متوازن / خارجي",
  "Bauwagen": "عربة البناء",
  "begegnen": "يصادف",
  "bereiten": "يهيّئ",
  "bereitet.) besehen": "يهيّئ / يتأمّل",
  "Besprechung": "الاجتماع",
  "eines Buchs) betreten": "دخل",
  "Charakter": "الشخصية",
  "sind gut geschildert.) die Eidechse": "مصوَّرة جيداً / السحلية",
  "einlassen": "يسمح لـ",
  "hat sich eingelassen die Empfindung": "انخرط في / الإحساس",
  "erben fein": "يرث / رقيق",
  "fraglich der Flügel": "مشكوك فيه / الجناح",
  "gelungen der Geist": "ناجح / الروح",
  "Genuss": "المتعة",
  "Herz": "القلب",
  "Hundehütte": "كوخ الكلب",
  "klischeehaft die Holztür": "نمطي / الباب الخشبي",
  "Lektüre": "القراءة",
  "Melancholie": "السوداوية",
  "Mischung": "المزيج",
  "philosophisch der Schließzylinder": "فلسفي / أسطوانة القفل",
  "reifen der Schuhabdruck": "ينضج / أثر الحذاء",
  "Resignation": "الاستسلام",
  "Road Movie": "فيلم الطريق",
  "Schicksalsschlag": "ضربة القدر",
  "schließen": "يغلق",
  "Skepsis": "الشكّ",
  "skeptisch": "متشكّك",
  "Textstelle": "مقطع نصّي",
  "Überlegung": "التأمّل",
  "unglaubwürdig": "غير موثوق",
  "versterben": "يتوفّى",
  "vorausgehen": "يسبق",
  "vorausgegangen der Zeigefinger": "سبق / السبّابة",
  "wundervoll 3b aufreißen": "رائع / يفتح بقوّة",
  "Buchbesprechung": "مراجعة كتاب",
  "Unterhaltungswert": "قيمة ترفيهية",
  "Angel": "صنّارة الصيد",
  "angelehnt": "مستوحى من",
  "Pfeife": "الصفّارة",
  "Rauschen": "الحفيف",
  "Sinn": "المعنى",
  "ticken das Konzept": "يدقّ / المفهوم",
  "Toilettenspülung": "سيفون المرحاض",
  "verleihen": "يمنح",
  "wegkommen": "يبتعد",
  "Zuordnung": "التصنيف",
  "ablegen": "يخلع",
  "aufliegen": "يعلو",
  "aufgelegen": "علا",
  "auf den Wangen auf.) stapfen": "على الخدّين / يمشي بثقل",
  "Auftreten": "الظهور",
  "besorgt": "قلق",
  "bringen": "يجلب",
  "dem Konzept bringen) 5b die Partie": "يربك / المباراة",
  "durchsichtig 8a das Musikkonzert": "شفّاف / الحفل الموسيقي",
  "Fakt": "الحقيقة",
  "Feststellung": "الاستنتاج",
  "füllig das Sportereignis": "ممتلئ / الحدث الرياضي",
  "fürsorglich die Sportveranstaltung": "حنون / الفعالية الرياضية",
  "gepflegt 8c die Klammer": "مهندم / القوس",
  "gewohnt sein Klammern.)": "معتاد على",
  "Groll": "الحقد",
  "Alltagsszene": "مشهد يومي",
  "ankaufen": "يشتري",
  "antreten": "يبدأ",
  "antreten / zur Wahl antreten) sozialistisch": "يترشّح / اشتراكي",
  "berühren die Strömung": "يلمس / التيّار",
  "Betrachter": "المشاهد",
  "charakteristisch Malerei.)": "مميّز / الرسم",
  "Entdecker": "المكتشف",
  "erstarren": "يتجمّد",
  "Fertigstellung": "الإنجاز",
  "Galerist": "صاحب المعرض",
  "gegenständlich vorangegangen": "تشكيلي / سبق",
  "Generation": "الجيل",
  "großformatig die Wende": "كبير الحجم / التحوّل",
  "hinaustragen": "يحمل إلى الخارج",
  "hinausgetragen": "حمل إلى الخارج",
  "hinaustragen) das Zugunglück": "يحمل / حادث القطار",
  "Honorarprofessur": "أستاذية فخرية",
  "Inspiration": "الإلهام",
  "Kunstikone": "أيقونة فنّية",
  "Label": "العلامة التجارية",
  "Leinwand": "اللوحة القماشية",
  "Malerei": "الرسم",
  "auflisten der Palast": "يسرد / القصر",
  "Hauptattraktion": "الجاذبية الرئيسية",
  "Monotonie": "الرتابة",
  "verweisen": "يحيل",
  "verwiesen zusammengeschrieben.)": "أحال / كُتب معاً",
  "zusammenschreiben": "يكتب معاً",
  "hat zusammengeschrieben": "كتب معاً",
  "Weltgeschichte": "التاريخ العالمي",
  "Antike": "العصور القديمة",
  "Zeitreise": "السفر عبر الزمن",
  "Burgdame": "سيّدة القلعة",
  "Knecht": "الخادم",
  "Krieger": "المحارب",
  "Magd": "الخادمة",
  "Musikant": "العازف",
  "Ritter": "الفارس",
  "Turnier": "البطولة",
  "Bestseller-Liste": "قائمة الأكثر مبيعاً",
  "Camp": "المخيّم",
  "Faszination": "الانبهار",
  "Gemeinschaft": "المجتمع",
  "Isolation": "العزلة",
  "kennzeichnen": "يميّز",
  "Maß": "المقياس",
  "Reiz": "الجاذبية",
  "Rollentausch": "تبادل الأدوار",
  "Amt": "المنصب",
  "werden) der Orden": "الوسام",
  "arbeitsfrei die Protestaktion": "عطلة / الاحتجاج",
  "ausgezeichnet": "ممتاز",
  "Beteiligung": "المشاركة",
  "Bundeskanzler": "المستشار الاتحادي",
  "Bundestagsfraktion": "كتلة البرلمان",
  "Bundestagswahl": "انتخابات البرلمان",
  "distanzieren": "يتباعد",
  "Ehrentag": "يوم التكريم",
  "Entfernung": "المسافة",
  "entlassen": "يطلق سراح",
  "Fachwelt": "الوسط المتخصّص",
  "gesetzlich der / Lokführer": "قانوني / سائق القطار",
  "Gründung": "التأسيس",
  "Hilfsorganisation": "منظّمة إغاثة",
  "immerwährend der Vulkanausbruch": "دائم / ثوران البركان",
  "initiieren 3c ereignen": "يبادر / يحدث",
  "Koalition": "الائتلاف",
  "Machtwechsel": "تغيير السلطة",
  "Nationalfeiertag": "العيد الوطني",
  "Buchdruck": "الطباعة",
  "angehen": "يبدأ بـ",
  "Buchseite": "صفحة الكتاب",
  "Drucktafel": "لوح الطباعة",
  "durchsetzen schnitzen": "يفرض / ينحت",
  "ergeben": "يُظهر",
  "verschiedenen Untersuchungen.) taufen": "فحوصات مختلفة / يعمّد",
  "fehlen": "يفتقد",
  "Handelsbeziehung": "العلاقة التجارية",
  "Holzplatte": "لوح خشبي",
  "irren": "يخطئ",
  "Teilung": "التقسيم",
  "abgrenzen der Verlauf": "يحدّد / المسار",
  "abriegeln 2c die Abschiedsszene": "يطوّق / مشهد الوداع",
  "Absperrung": "الحاجز",
  "Aufteilung": "التوزيع",
  "Ausbau": "التوسيع",
  "ausbauen auseinandergerissen.)": "يوسّع / مُمزَّق",
  "Ausreisekontrolle": "مراقبة المغادرة",
  "Bauarbeiter": "عامل بناء",
  "Besatzungszone": "منطقة الاحتلال",
  "Bewachung": "الحراسة",
  "endgültig ergehen": "نهائي / يصدر",
  "errichten": "يشيّد",
  "festlegen der Familienbesuch": "يحدّد / زيارة العائلة",
  "Gehweg": "الرصيف",
  "Genehmigung": "التصريح",
  "Grenzgebiet": "المنطقة الحدودية",
  "Grenzkontrolle": "مراقبة الحدود",
  "Grenzsoldat": "جندي الحدود",
  "großteils ungewiss": "بشكل كبير / غير أكيد",
  "Hinterhof": "الفناء الخلفي",
  "komfortabel die Verabschiedungshalle": "مريح / قاعة الوداع",
  "Kontrollsystem": "نظام المراقبة",
  "Lebensbedingung": "ظروف المعيشة",
  "perfektionieren 3b die Ausreise": "يتقن / المغادرة",
  "rücksichtslos ausreisen": "متهوّر / يغادر",
  "Schließung": "الإغلاق",
  "sogenannt beigetragen": "ما يُسمّى / ساهم",
  "überwachen besetzen": "يراقب / يحتلّ",
  "überwinden": "يتغلّب على",
  "ungehindert erzwingen": "بلا عوائق / يفرض",
  "Unterteilung": "التقسيم الفرعي",
  "Wachturm": "برج المراقبة",
  "Wirtschaftssektor": "القطاع الاقتصادي",
  "Zaun": "السياج",
  "zumauern die Massenflucht": "يسدّ بجدار / الهروب الجماعي",
  "Zusammenbruch": "الانهيار",
  "Revolution": "الثورة",
  "Staatsführer": "رئيس الدولة",
  "Wiedervereinigung": "إعادة التوحيد",
  "Mauerfall": "سقوط الجدار",
  "Pressekonferenz": "المؤتمر الصحفي",
  "Pressesprecher": "المتحدّث الرسمي",
  "Regelung": "التنظيم",
  "Staatschef": "رئيس الدولة",
  "Voraussetzung": "الشرط المسبق",
  "Chronik": "السجلّ",
  "Zeitzeuge": "شاهد العصر",
  "Amtsinhaber": "شاغل المنصب",
  "ausgerechnet": "بالتحديد",
  "komme ich zu spät.) der Langlauf": "التزلّج الريفي",
  "beitreten": "ينضمّ",
  "Bundesminister": "الوزير الاتحادي",
  "Bundestag": "البرلمان الاتحادي",
  "eintreten": "يدخل",
  "Entscheidung": "القرار",
  "treffen) rustikal": "يتّخذ / ريفي",
  "ernennen": "يعيّن",
  "Festspiel": "المهرجان",
  "Forelle": "سمك السلمون المرقّط",
  "freihalten": "يبقي فارغاً",
  "fusionieren treffen": "يندمج / يلتقي",
  "Gemüsebeet": "حوض الخضراوات",
  "Höhepunkt": "الذروة",
  "Jugendzeit": "فترة الشباب",
  "Kanzler": "المستشار",
  "Abhängigkeit": "التبعية",
  "ängstigen": "يخيف",
  "Eifersucht": "الغيرة",
  "eifersüchtig": "غيور",
  "Examen": "الامتحان",
  "bang aufgehen": "خائف / ينفتح",
  "golden Frühling gehen die Knospen der Pflanzen": "ذهبي / في الربيع تتفتّح البراعم",
  "Käfig": "القفص",
  "rettungslos beladen": "ميؤوس منه / محمَّل",
  "rinnen": "يسيل",
  "rinnt die Straße hinunter.) beschwerst": "يسيل / تشتكي",
  "schlummerlos drauflos": "بلا نوم / مندفع",
  "unbewusst die Knospe": "لاواعٍ / البرعم",
  "vorüber rotschämen": "مضى / يخجل بشدّة",
  "Zweifel": "الشكّ",
  "Zweig": "الغصن",
  "schrecklich": "فظيع",
  "bemühen)": "يسعى",
  "sehnen": "يشتاق",
  "talentlos zusammenbrechen": "بلا موهبة / ينهار",
  "talentvoll zusammengebrochen": "موهوب / انهار",
  "üppig 2 der Spruch": "فاخر / المقولة",
  "ablaufen": "ينتهي",
  "laufen viele Prozesse ab.) reproduzieren": "تنتهي عمليات / يعيد إنتاج",
  "Alzheimer": "الزهايمر",
  "anknüpfen": "يتابع",
  "Atmung": "التنفّس",
  "auswendig lernen schmerzlindernd": "يحفظ غيباً / مسكّن للألم",
  "Befinden": "الحالة الصحية",
  "beruhigend sozusagen": "مهدّئ / إذا صحّ التعبير",
  "Betroffene": "المتضرّر",
  "Bewegungsstörung": "اضطراب الحركة",
  "Blutdruck": "ضغط الدم",
  "chronisch": "مزمن",
  "Demenz": "الخرف",
  "durchaus vielfach": "بالتأكيد / عدّة مرّات",
  "Gedächtnis": "الذاكرة",
  "Gedächtnisinhalt": "محتوى الذاكرة",
  "Gehirnaktivität": "نشاط الدماغ",
  "Gelenkschmerzen": "آلام المفاصل",
  "gesundheitsfördernd die Verarbeitung": "معزّز للصحّة / المعالجة",
  "Herzfrequenz": "معدّل ضربات القلب",
  "Hirnschaden": "تلف الدماغ",
  "Lerneffekt": "أثر التعلّم",
  "Lerninhalt": "محتوى التعلّم",
  "Musiktherapeut": "معالج بالموسيقى",
  "Pulsschlag": "نبض القلب",
  "Pessimismus": "التشاؤم",
  "Reinheit": "النقاء",
  "Trauer": "الحزن",
  "Verzweiflung": "اليأس",
  "ärgern": "يغضب",
  "ärgern) 1c der Befehl": "يغضب / الأمر",
  "Himmel": "السماء",
  "versprechen) die Ermunterung": "يعد / التشجيع",
  "schwarz": "أسود",
  "verstärken 2b abschwächen": "يعزّز / يخفّف",
  "Weste": "الصدرية",
  "Ampelprinzip": "مبدأ إشارة المرور",
  "dem Ampelprinzip täglich eine Mischung abgeschrieben": "مبدأ الإشارة الضوئية",
  "aus rotem": "من الأحمر",
  "depressiv": "مكتئب",
  "melancholisch die Reue": "سوداوي / الندم",
  "einfrieren": "يجمّد",
  "Endorphin": "الإندورفين",
  "Feuerwerk": "الألعاب النارية",
  "Grab": "القبر",
  "Hoch": "المرتفع الجوّي",
  "vergolden der Magen": "يذهّب / المعدة",
  "ziehen) der Schmetterling": "يسحب / الفراشة",
  "Refrain": "اللازمة",
  "pessimistisch": "متشائم",
  "Angstreaktion": "ردّ فعل الخوف",
  "Badesee": "بحيرة السباحة",
  "Notwendigkeit": "الضرورة",
  "vorausdenken": "يفكّر مسبقاً",
  "vorausgedacht das Urteilsvermögen": "فكّر مسبقاً / القدرة على الحكم",
  "Gedankenschritt": "خطوة فكرية",
  "Lesetext": "نصّ القراءة",
  "Pfeil": "السهم",
  "strukturiert die Routine": "منظّم / الروتين",
  "Verstand": "العقل",
  "Bauch": "البطن",
  "haben) zugreifen": "يستخدم",
  "Dilemma": "المعضلة",
  "einholen das Business-Outfit": "يلحق / الزيّ المهني",
  "fällen": "يتّخذ قراراً",
  "Fehlentscheidung": "قرار خاطئ",
  "Gefahr": "الخطر",
  "Gewissen": "الضمير",
  "und Gewissen) die Schale": "الضمير / الوعاء",
  "investieren": "يستثمر",
  "Investition": "الاستثمار",
  "laufen": "يجري",
  "limitiert": "محدود",
  "ähneln parodieren": "يشبه / يحاكي ساخراً",
  "Alltagssprache": "لغة الحياة اليومية",
  "Arbeitschance": "فرصة عمل",
  "Außenseiter/in": "الدخيل",
  "bankrott die Romantik": "مفلس / الرومانسية",
  "bedeutend der / Romantiker": "مهمّ / الرومانسي",
  "beerdigen der / Satiriker": "يدفن / كاتب السخرية",
  "befassen": "يهتمّ بـ",
  "Bewunderer": "المعجب",
  "Bezug": "المرجع",
  "daraufhin der Spott": "عقب ذلك / السخرية",
  "Dichter": "الشاعر",
  "Einnahme": "الدخل",
  "entlaufen": "يهرب",
  "Essayist": "كاتب المقالات",
  "Feuilleton": "الملحق الثقافي",
  "Friedhof": "المقبرة",
  "Gesellschaftskritik": "النقد الاجتماعي",
  "Gesetzesreform": "إصلاح القانون",
  "Grenze": "الحدود",
  "Handelsschule": "المدرسة التجارية",
  "Kunstform": "الشكل الفنّي",
  "Liberalität": "الليبرالية",
  "Lyrik": "الشعر الغنائي",
  "mythologisch ziehen": "أسطوري / ينتقل",
  "Niederlage": "الهزيمة",
  "Hörspiel": "المسلسل الإذاعي",
  "aufwärmen die Reaktionszeit": "يسخّن / زمن ردّ الفعل",
  "ausführen": "ينفّذ",
  "ausräumen": "يزيل",
  "ausräumen) die Überzeugungskraft": "يزيل / قوّة الإقناع",
  "Autofahrer": "سائق السيارة",
  "Branche": "القطاع",
  "einleuchtend wegfallen": "واضح / يسقط",
  "einräumen": "يعترف بـ",
  "Empathie": "التعاطف",
  "interagieren": "يتفاعل",
  "Krankenhausaufenthalt": "الإقامة في المستشفى",
  "Menschenleben": "حياة بشرية",
  "Mitschüler": "زميل الدراسة",
  "Notruf": "نداء الطوارئ",
  "Diagnose": "التشخيص",
  "diagnostizieren das Gesundheitsgerät": "يشخّص / الجهاز الصحّي",
  "Körpertemperatur": "حرارة الجسم",
  "Puls": "النبض",
  "Wert": "القيمة",
  "hohen Wert an.) heben": "يرفع القيمة",
  "App": "التطبيق",
  "checken die Hosentasche": "يتفقّد / جيب البنطال",
  "Digitalisierung": "الرقمنة",
  "Fieberthermometer": "ميزان الحرارة",
  "Geschäftsmodell": "نموذج الأعمال",
  "hinterherhinken": "يتخلّف",
  "hinken der Digitalisierung hinterher.) leeren": "يتخلّف عن الرقمنة / يفرّغ",
  "Körpergröße": "طول الجسم",
  "optimieren lindern": "يحسّن / يخفّف",
  "untertreiben": "يقلّل من شأن",
  "vermessen": "يقيس",
  "Ärztemangel": "نقص الأطباء",
  "aufkommen": "يظهر",
  "auswerten der Sauerstoff": "يحلّل / الأكسجين",
  "Branchenverband": "اتحاد القطاع",
  "Brustkorb": "القفص الصدري",
  "bündeln simpel": "يجمع / بسيط",
  "Chip": "الرقاقة",
  "Daumen": "الإبهام",
  "Durchmesser": "القطر",
  "einatmen umstritten": "يستنشق / مثير للجدل",
  "einpflanzen das Verfahren": "يزرع / الإجراء",
  "einstellen) die Windel": "يضبط / الحفّاضة",
  "Erfindungsreichtum": "الابتكار",
  "Berater": "المستشار",
  "Berufswunsch": "الوظيفة المرغوبة",
  "IT-Bereich": "قطاع تقنية المعلومات",
  "Moderator": "المقدّم",
  "Programmankündigung": "إعلان البرنامج",
  "weiterhin infolge": "لا يزال / بسبب",
  "Wissensmanager": "مدير المعرفة",
  "Arbeitsgebiet": "مجال العمل",
  "Berufsausbildung": "التدريب المهني",
  "Berufsbereich": "المجال المهني",
  "Informationsbeschaffung": "جمع المعلومات",
  "abbrechen": "يقطع",
  "rosig attackieren": "وردي / يهاجم",
  "vorhersagen auslöschen": "يتنبّأ / يمحو",
  "werfen": "يرمي",
  "Zukunft werfen) begeben": "المستقبل / يتوجّه",
  "kursiv sich begeben": "مائل / يتوجّه",
  "zukommen": "يتوجّه إلى",
  "zugekommen": "توجّه إلى",
  "lassen) ganze Nation.)": "يدع / الأمّة كلّها",
  "Zukunftsvision": "رؤية مستقبلية",
  "Anonymität": "إخفاء الهوية",
  "beschränken": "يحدّ",
  "energiesparend das Forschungsteam": "موفّر للطاقة / فريق البحث",
  "entfliehen": "يهرب من",
  "Anonymität der Großstadt geflohen.) geraten)": "هرب من المدينة الكبيرة",
  "Forumsbeitrag": "مشاركة في المنتدى",
  "Generationenwohnprojekt": "مشروع سكني للأجيال",
  "Klick": "النقرة",
  "kostengünstig kentern": "اقتصادي / ينقلب",
  "Privatauto": "سيارة خاصّة",
  "Raumtemperatur": "درجة حرارة الغرفة",
  "Sonnencreme": "واقي الشمس",
  "sperren": "يحجب",
  "Wohnform": "شكل السكن",
  "Ankunftsabend": "مساء الوصول",
  "Aussteller": "العارض",
  "Dienstleistung": "الخدمة",
  "Messegelände": "أرض المعرض",
  "Messehalle": "قاعة المعرض",
  "sagenhaft der / Schwimmer": "أسطوري / السبّاح",
  "Snack": "الوجبة الخفيفة",
  "Werbeanzeige": "إعلان تجاري",
  "Zugang": "الوصول",
  "etw./jmd. haben) das Verbrechen": "الجريمة",
  "andernfalls vorsprechen": "وإلاّ / يتقدّم لأداء دور",
  "Beschwerdebrief": "رسالة شكوى",
  "Eindruck": "الانطباع",
  "schildern wiedergetroffen": "يصف / التقى مجدّداً",
  "unangebracht zustande kommen": "غير لائق / ينجح",
  "Veranstalter": "المنظّم",
  "Theaterstück": "مسرحية",
  "Akademie": "الأكاديمية",
  "anmelden": "يسجّل",
  "Astronom": "عالم الفلك",
  "Bedürfnis": "الحاجة",
  "Begabung": "الموهبة",
  "benennen": "يسمّي",
  "Glaserlehre": "تدريب صناعة الزجاج",
  "Innovation": "الابتكار",
  "Lungenkrankheit": "مرض الرئة",
  "mechanisch zukunftsweisend": "آلي / مستقبلي",
  "angesichts": "بالنظر إلى",
  "anlässlich": "بمناسبة",
  "Ausbildungsmöglichkeit": "فرصة تدريب",
  "ausprobieren": "يجرّب",
  "Arbeitgeber/-in": "صاحب العمل",
  "Architekt/-in": "المهندس المعماري",
  "Automechaniker/-in": "ميكانيكي السيارات",
  "Autoproduzent": "صانع السيارات",
  "Beratung": "الاستشارة",
  "Betrieb": "المنشأة",
  "Familienbetrieb": "شركة عائلية",
  "internationale": "الدولي",
  "Lebensmittelbranche": "قطاع الأغذية",
  "Malerbetrieb": "شركة دهان",
  "soziale": "الاجتماعي",
  "produzieren": "ينتج",
  "geistig": "ذهني",
  "handwerklich": "حرفي",
  "sozial": "اجتماعي",
  "Grundschule": "المدرسة الابتدائية",
  "weiterführende": "المتقدّمة",
  "Hauptschule": "المدرسة الرئيسية",
  "Mittelschule": "المدرسة المتوسّطة",
  "Realschule": "المدرسة الحقيقية",
  "Gesamtschule": "المدرسة الشاملة",
  "Gymnasium": "المدرسة الثانوية",
  "Haupt-/Realschulabschluss": "شهادة المدرسة الرئيسية/الحقيقية",
  "Abitur": "الثانوية العامّة",
  "Mittlere": "المتوسّطة",
  "Berufsabschluss": "المؤهّل المهني",
  "Master": "الماجستير",
  "Zertifikat": "الشهادة",
  "mehr": "أكثر",
  "weniger": "أقلّ",
  "Hälfte": "النصف",
  "ein": "واحد",
  "jeder": "كلّ",
  "Ansprechpartner/-in": "الشخص المسؤول",
  "Beratungsstelle": "مركز الاستشارات",
  "Berufspraktikum": "تدريب مهني",
  "duale": "الثنائي",
  "Fachschule": "المدرسة المتخصّصة",
  "Fortbildung": "التعليم المستمرّ",
  "Meisterprüfung": "امتحان الحرفة",
  "Schichtdienst": "العمل بنظام المناوبة",
  "staatliche": "الحكومية",
  "Weiterbildung": "التعليم الإضافي",
  "Wunschberuf": "المهنة المرغوبة",
  "Zugangsvoraussetzungen": "شروط القبول",
  "einen": "يوحّد",
  "den": "الـ",
  "jobben": "يعمل مؤقّتاً",
  "sich": "نفسه",
  "zuständig": "مسؤول",
  "Stärke": "القوّة",
  "belastbar": "قادر على التحمّل",
  "flexibel": "مرن",
  "hilfsbereit": "مستعدّ للمساعدة",
  "kreativ": "مبدع",
  "lernbereit": "مستعدّ للتعلّم",
  "selbstbewusst": "واثق بنفسه",
  "teamfähig": "قادر على العمل الجماعي",
  "tolerant": "متسامح",
  "verantwortungsbewusst": "مسؤول",
  "Anerkennung": "الاعتراف",
  "Antrag": "الطلب",
  "Lebenslauf": "السيرة الذاتية",
  "Unterlagen": "الوثائق",
  "Zeugnis": "الشهادة",
  "Zulassung": "القبول",
  "Arbeitsablauf": "سير العمل",
  "Berufsfeld": "المجال المهني",
  "Fachdeutsch": "الألمانية التخصّصية",
  "Fachwortschatz": "المصطلحات التخصّصية",
  "Handwerker/-in": "الحرفي",
  "MINT-Beruf": "مهنة في العلوم والتقنية",
  "Teilzeit": "دوام جزئي",
  "Vollzeit": "دوام كامل",
  "gefragte": "المطلوب",
  "Umgang": "التعامل",
  "Berechtigung": "الصلاحية",
  "Förderung": "الدعم",
  "Lehrgang": "الدورة التدريبية",
  "Nachweis": "الإثبات",
  "Vorkenntnisse": "المعرفة المسبقة",
  "Vermittler/-in": "الوسيط",
  "Zugangsvoraussetzung": "شرط القبول",
  "persönlich": "شخصي",
  "beglaubigte": "المصدَّقة",
  "berufliche": "المهنية",
  "Qualifikation": "المؤهّل",
  "Übersetzungsbüro": "مكتب الترجمة",
  "Einzelunternehmer/-in": "صاحب عمل فردي",
  "Geschäftspartner/-in": "شريك تجاري",
  "gut": "جيّد",
  "freiberufliche": "المستقلّة",
  "Bewerbungstraining": "تدريب على التقديم",
  "Spezialisierung": "التخصّص",
  "Stellengesuch": "طلب وظيفة",
  "Anforderung": "المتطلّب",
  "Arbeitssuchende": "الباحث عن عمل",
  "mittelständische": "المتوسّطة الحجم",
  "Ehrenamt": "العمل التطوّعي",
  "Schulbildung": "التعليم المدرسي",
  "besonderen": "الخاصّة",
  "persönlichen": "الشخصية",
  "ausgeschriebene": "المعلَن عنها",
  "Gehaltsvorstellung": "توقّعات الراتب",
  "Herausforderung": "التحدّي",
  "eine": "واحدة",
  "Arbeitsverhältnis": "علاقة العمل",
  "Betriebsgeheimnis": "سرّ العمل",
  "Gehalt": "الراتب",
  "Krankmeldung": "إبلاغ بالمرض",
  "Kündigungsfrist": "مهلة الفسخ",
  "Lohnfortzahlung": "استمرار دفع الأجر",
  "Probezeit": "فترة التجربة",
  "Überstunde": "ساعة إضافية",
  "Verdienst": "الدخل",
  "Vergütung": "المكافأة",
  "Verschwiegenheitspflicht": "واجب السرّية",
  "Anweisung": "التعليمات",
  "Gefahrenstelle": "نقطة خطر",
  "Schild": "اللافتة",
  "Verbesserungsvorschlag": "اقتراح التحسين",
  "Zeichen": "العلامة",
  "Alarmanlage": "نظام الإنذار",
  "ätzende": "المادّة الكاوية",
  "Berichtsheft": "دفتر التقارير",
  "brennende": "المادّة القابلة للاشتعال",
  "elektrische": "الكهربائية",
  "explosive": "المادّة المتفجّرة",
  "giftige": "المادّة السامّة",
  "auf": "على",
  "keine": "لا شيء",
  "Papiere": "الأوراق",
  "rechtzeitig": "في الوقت المناسب",
  "Krankenschein": "شهادة مرضية",
  "Schwindel": "الدوار",
  "Stromschlag": "الصعقة الكهربائية",
  "Übelkeit": "الغثيان",
  "Haut": "الجلد",
  "Stromquelle": "مصدر التيّار",
  "Vertretung": "النيابة",
  "antibakterielle": "المضادّ للبكتيريا",
  "Ordnung": "النظام",
  "Putzlappen": "خرقة التنظيف",
  "Staubsauger": "المكنسة الكهربائية",
  "Waschbecken": "المغسلة",
  "Mengenrabatt": "خصم الكمّية",
  "Preisangabe": "بيان السعر",
  "Preisnachlass": "التخفيض",
  "Buchung": "الحجز",
  "vereinbarte": "المتّفق عليه",
  "nachfragen": "يستفسر",
  "vorbeikommen": "يمرّ",
  "außerhalb": "خارج",
  "ohne": "بدون",
  "Missverständnis": "سوء الفهم",
  "Abdruck": "البصمة",
  "Betäubungsspritze": "حقنة التخدير",
  "provisorische": "المؤقّتة",
  "Haltbarkeit": "الصلاحية",
  "Inlay": "الحشوة",
  "Karies": "التسوّس",
  "Keramik": "السيراميك",
  "Labor": "المختبر",
  "Notdienst": "خدمة الطوارئ",
  "Gastronomie": "قطاع المطاعم",
  "Großhandel": "تجارة الجملة",
  "Einzelhandel": "تجارة التجزئة",
  "Immobilienbranche": "قطاع العقارات",
  "IT-Branche": "قطاع تقنية المعلومات",
  "Maschinenbau": "الهندسة الميكانيكية",
  "Medien": "الإعلام",
  "Metallindustrie": "صناعة المعادن",
  "Öffentliche": "القطاع العامّ",
  "Pharmaindustrie": "صناعة الأدوية",
  "Einkauf": "المشتريات",
  "Finanzabteilung": "القسم المالي",
  "Kundenbetreuung": "خدمة العملاء",
  "Lager": "المستودع",
  "Marketingabteilung": "قسم التسويق",
  "Personalabteilung": "قسم الموارد البشرية",
  "Produktion": "الإنتاج",
  "Berufschancen": "الفرص المهنية",
  "Einsatzplan": "جدول العمل",
  "Vorgesetzte": "الرئيس المباشر",
  "Ware": "البضاعة",
  "Anredeform": "صيغة المخاطبة",
  "Firmenphilosophie": "فلسفة الشركة",
  "Image": "الصورة",
  "duzen": "يخاطب بـ du",
  "siezen": "يخاطب بـ Sie",
  "angemessen": "مناسب",
  "förmlich": "رسمي",
  "konservativ": "محافظ",
  "locker": "مسترخٍ",
  "respektlos": "غير محترم",
  "traditionsreich": "عريق",
  "Du": "الـ du",
  "per": "بواسطة",
  "tabu": "محرَّم",
  "Ausbildung": "التدريب المهني",
  "Ausbildungsberuf": "مهنة التدريب",
  "Berufsfachschule": "المدرسة المهنية المتخصّصة",
  "Berufsinformationszentrum": "مركز المعلومات المهنية",
  "Berufskolleg": "الكلّية المهنية",
  "Berufsvorbereitungsjahr": "السنة التحضيرية المهنية",
  "Fortbildungsakademie": "أكاديمية التعليم المستمرّ",
  "Handelssprache": "لغة التجارة",
  "absolvieren": "يتمّ",
  "erlernte": "المُكتسَب",
  "fundierte": "المتينة",
  "Altersbegrenzung": "الحدّ العمري",
  "Anliegen": "المطلب",
  "Aushilfsjob": "عمل مؤقّت",
  "Ausschreibung": "الإعلان الوظيفي",
  "Bewerbungsunterlagen": "وثائق التقديم",
  "Jobbörse": "بورصة الوظائف",
  "Personalchef/-in": "مدير الموارد البشرية",
  "beeindrucken": "يبهر",
  "derzeitig": "حالي",
  "gelegentlich": "أحياناً",
  "gewissenhaft": "دقيق",
  "reibungslos": "بسلاسة",
  "zuverlässig": "موثوق",
  "beruflich": "مهني",
  "feste": "ثابتة",
  "rund": "حوالي",
  "Anlagenmechaniker/-in": "ميكانيكي التمديدات",
  "Bilanzbuchhalter/-in": "محاسب الميزانية",
  "Bürokaufmann/-frau": "موظّف إداري",
  "Gärtner/-in": "البستاني",
  "Gesundheits-": "الصحّي",
  "Näher/-in": "الخيّاط",
  "Servicekraft": "موظّف الخدمة",
  "Zimmerservice": "خدمة الغرف",
  "Aufstiegschancen": "فرص الترقّي",
  "Außentermin": "موعد خارجي",
  "Kantine": "المقصف",
  "Sozialleistungen": "المزايا الاجتماعية",
  "sachlich": "موضوعي",
  "Chemie": "الكيمياء",
  "fix": "سريع",
  "Geduld": "الصبر",
  "monotone": "الرتيبة",
  "nichts": "لا شيء",
  "schlecht": "سيّئ",
  "40-Stunden-Woche": "أسبوع الأربعين ساعة",
  "Entgegenkommen": "التساهل",
  "Gleitzeit": "ساعات العمل المرنة",
  "Kernzeit": "ساعات العمل الأساسية",
  "Wechselschicht": "المناوبة المتبادلة",
  "flexible": "مرنة",
  "vertraglich": "تعاقدي",
  "Betreuungsangebot": "عرض الرعاية",
  "Tagesmutter": "حاضنة الأطفال",
  "alleinerziehend": "أب/أمّ عازب/ة",
  "familienfreundlich": "صديق للعائلة",
  "angewiesen": "معتمد على",
  "An-/Abreise": "الوصول/المغادرة",
  "Besprechungsraum": "غرفة الاجتماعات",
  "Buchungsbestätigung": "تأكيد الحجز",
  "Doppelzimmer": "غرفة مزدوجة",
  "Einzelzimmer": "غرفة مفردة",
  "Fahrgemeinschaft": "مشاركة السيارة",
  "Flugverbindung": "رحلة جوّية",
  "Gewerbegebiet": "المنطقة الصناعية",
  "Meeting": "الاجتماع",
  "Mietauto": "سيارة مستأجرة",
  "Parkmöglichkeit": "إمكانية ركن السيارة",
  "Tagungshotel": "فندق المؤتمرات",
  "Tiefgarage": "مرآب تحت الأرض",
  "Zimmer-/Hotelkategorie": "تصنيف الفندق",
  "Arbeitsplatzbeschreibung": "وصف مكان العمل",
  "Qualitätssicherung": "ضمان الجودة",
  "Richtlinien": "الإرشادات",
  "Vorarbeiter/-in": "رئيس العمّال",
  "Vorgehen": "الإجراء",
  "zustimmen": "يوافق",
  "einverstanden": "موافق",
  "Aufkleber": "الملصق",
  "Broschüre": "الكتيّب",
  "Datenblatt": "صحيفة البيانات",
  "Detail": "التفصيل",
  "Give-away": "الهدية الترويجية",
  "Großhändler": "تاجر الجملة",
  "Katalog": "الكتالوج",
  "Leistungsschau": "معرض الإنجازات",
  "Logo": "الشعار",
  "Muster": "النموذج",
  "Poster": "الملصق الإعلاني",
  "Prospektständer": "حامل النشرات",
  "Start-up-Unternehmen": "شركة ناشئة",
  "To-do-Liste": "قائمة المهامّ",
  "Visitenkarte": "بطاقة العمل",
  "Werbegeschenk": "هدية دعائية",
  "Wettbewerber": "المنافس",
  "innovativ": "مبتكر",
  "einzigartig": "فريد",
  "wettbewerbsfähig": "قادر على المنافسة",
  "aktuelle": "الحالية",
  "Ab-/Zusage": "القبول/الرفض",
  "Filiale": "الفرع",
  "Qualität": "الجودة",
  "Saison": "الموسم",
  "Wartung": "الصيانة",
  "Liefer-": "التوصيل",
  "Anfrage": "الاستفسار",
  "Eilzuschlag": "رسوم الاستعجال",
  "Gesamtpreis": "السعر الإجمالي",
  "Mailing": "المراسلة",
  "Nettopreis": "السعر الصافي",
  "Bruttopreis": "السعر الإجمالي شامل الضريبة",
  "Sonderwunsch": "طلب خاصّ",
  "Angebot": "العرض",
  "unverbindliche": "غير الملزم",
  "zuzüglich": "بالإضافة إلى",
  "inklusive": "شامل",
  "Lieferkosten": "تكاليف التوصيل",
  "Rabatt": "الخصم",
  "Ratenzahlung": "الدفع بالأقساط",
  "Skonto": "خصم الدفع النقدي",
  "Vorauszahlung": "الدفع المسبق",
  "Werktag": "يوم العمل",
  "bei": "عند",
  "frei": "حرّ",
  "Versand": "الشحن",
  "höchstens": "على الأكثر",
  "mindestens": "على الأقلّ",
  "spätestens": "في أقصى تقدير",
  "bankrott": "مفلس",
  "Bürokommunikation": "الاتصالات المكتبية",
  "Vertriebskenntnisse": "معرفة التوزيع",
  "zukunftsorientiert": "موجَّه نحو المستقبل",
  "Artikelnummer": "رقم المنتج",
  "Bestellnummer": "رقم الطلب",
  "Artikelbezeichnung": "تسمية المنتج",
  "Bestandskunde": "عميل دائم",
  "Kundennummer": "رقم العميل",
  "Neukunde": "عميل جديد",
  "Onlineshop": "متجر إلكتروني",
  "Versandhandel": "البيع عبر البريد",
  "erhältlich": "متوفّر",
  "verfügbar": "متاح",
  "Barzahlung": "الدفع نقداً",
  "Mahnung": "التذكير بالدفع",
  "Online-Bezahldienst": "خدمة الدفع الإلكتروني",
  "Sicherheitsbedenken": "مخاوف أمنية",
  "Zahlungsempfänger": "المستفيد من الدفع",
  "Betrag": "المبلغ",
  "Zahlung": "الدفع",
  "Zahlungserinnerung": "تذكير بالدفع",
  "Budget": "الميزانية",
  "Drittel": "الثلث",
  "Achtel": "الثمن",
  "Viertel": "الربع",
  "gleich": "متساوٍ",
  "mal": "مرّة",
  "übrig": "متبقٍّ",
  "Enttäuschung": "خيبة الأمل",
  "Konsequenzen": "العواقب",
  "Streitgespräch": "نقاش حادّ",
  "Vorfall": "الحادثة",
  "fehlerhaft": "معيب",
  "konstruktive": "البنّاء",
  "etwas": "شيء",
  "Norm": "المعيار",
  "Qualitätsmanagementsystem": "نظام إدارة الجودة",
  "Arbeitsweisen": "أساليب العمل",
  "Motivation": "الحافز",
  "Produkte": "المنتجات",
  "einzelnen": "الفردية",
  "wirtschaftliche": "الاقتصادية",
  "Agenda": "جدول الأعمال",
  "Ankündigung": "الإعلان",
  "Bericht": "التقرير",
  "Besprechungsprotokoll": "محضر الاجتماع",
  "Ergebnisprotokoll": "محضر النتائج",
  "Mitarbeiterbesprechung": "اجتماع الموظّفين",
  "Projektvorstellung": "تقديم المشروع",
  "Rückblick": "المراجعة",
  "Sitzung": "الجلسة",
  "Tagesordnungspunkt": "بند جدول الأعمال",
  "Teambesprechung": "اجتماع الفريق",
  "Verlaufsprotokoll": "محضر تفصيلي",
  "Vorbesprechung": "اجتماع تحضيري",
  "mailen": "يرسل بريداً إلكترونياً",
  "nachvollziehen": "يفهم",
  "protokollieren": "يدوّن المحضر",
  "Ansicht": "وجهة النظر",
  "Beamer": "جهاز العرض",
  "Besprechungsunterlagen": "وثائق الاجتماع",
  "Flipchart": "اللوح القلّاب",
  "Internetzugang": "الاتصال بالإنترنت",
  "Moderationskarten": "بطاقات الإدارة",
  "Moderationskoffer": "حقيبة الإدارة",
  "Netzwerkanschluss": "منفذ الشبكة",
  "Pinnwand": "لوحة الدبابيس",
  "Tagungsraum": "قاعة المؤتمرات",
  "Whiteboard": "اللوح الأبيض",
  "Ausblick": "التوقّعات",
  "Controlling": "الرقابة المالية",
  "Jahresbilanz": "الميزانية السنوية",
  "Prognose": "التوقّع",
  "Quartalsaufstellung": "كشف ربع سنوي",
  "Quote": "النسبة",
  "knapp": "شحيح",
  "Abdeckung": "الغطاء",
  "Anschlusskontakt": "جهة اتصال لاحقة",
  "Display": "الشاشة",
  "QR-Code": "رمز الاستجابة السريعة",
  "Standort": "الموقع",
  "Touchscreen": "الشاشة اللمسية",
  "USB-Anschluss": "منفذ USB",
  "aktualisieren": "يحدّث",
  "einrasten": "ينقر في مكانه",
  "einrichten": "يجهّز",
  "herunterladen": "يحمّل",
  "navigieren": "يتنقّل",
  "zoomen": "يكبّر",
  "Arbeitsunfähigkeit": "العجز عن العمل",
  "Bestimmungen": "الأحكام",
  "Freistellung": "الإعفاء",
  "Freizeitausgleich": "تعويض وقت الفراغ",
  "Kalenderjahr": "السنة الميلادية",
  "betriebliche": "الخاصّة بالشركة",
  "Arbeitsschutzschuhe": "أحذية السلامة",
  "Berufsgruppe": "المجموعة المهنية",
  "Blutung": "النزيف",
  "Ersthelfer/-in": "مسعف أوّلي",
  "Evakuierung": "الإخلاء",
  "Flucht-/Rettungsweg": "طريق الهروب/الإنقاذ",
  "Gehörschutz": "حماية السمع",
  "Notausgang": "مخرج الطوارئ",
  "Platzwunde": "جرح مفتوح",
  "Rettungswagen": "سيارة الإسعاف",
  "Rutschgefahr": "خطر الانزلاق",
  "Sammelstelle": "نقطة التجمّع",
  "Sanitäter/-in": "المسعف",
  "Schutzausrüstung": "معدّات الحماية",
  "Schutzbrille": "نظّارة الحماية",
  "Schutzhelm": "خوذة الحماية",
  "Stolper-/Sturzgefahr": "خطر التعثّر/السقوط",
  "Gleichgewicht": "التوازن",
  "Abmahnung": "الإنذار",
  "Ausnahmegenehmigung": "تصريح استثنائي",
  "Beförderung": "الترقية",
  "Führungsqualitäten": "صفات قيادية",
  "Honorartätigkeit": "عمل بأجر حرّ",
  "Minijob": "عمل بأجر زهيد",
  "Nebentätigkeit": "نشاط جانبي",
  "Sperrzeit": "فترة الحظر",
  "Werkvertrag": "عقد عمل بالمهمّة",
  "Zeitarbeit": "العمل المؤقّت",
  "befristet": "محدّد المدّة",
  "beiderseits": "من الطرفين",
  "Ablauf": "المسار",
  "Anrechnung": "الاحتساب",
  "ärztliche": "الطبّية",
  "betriebsbedingte": "المتعلّقة بالعمل",
  "Fortzahlung": "استمرار الدفع",
  "interne": "الداخلية",
  "regelmäßige": "المنتظمة",
  "Arbeitslosenversicherung": "تأمين البطالة",
  "Bruttovergütung": "الراتب الإجمالي",
  "Kirchensteuer": "ضريبة الكنيسة",
  "Konfession": "المذهب",
  "Lohnsteuer": "ضريبة الدخل",
  "Nettoverdienst": "الراتب الصافي",
  "Pflegeversicherung": "تأمين الرعاية",
  "Rentenversicherung": "تأمين التقاعد",
  "Solidaritätszuschlag": "رسم التضامن",
  "Steuerklasse": "الفئة الضريبية",
  "abziehen": "يخصم",
  "einbehalten": "يستقطع",
  "Belegschaft": "الموظّفون",
  "Gleichberechtigung": "المساواة",
  "Integration": "الاندماج",
  "Nachfolger/-in": "الخلف",
  "Schwerbehinderte": "ذو إعاقة شديدة",
};

// Read the file
let content = fs.readFileSync(filePath, 'utf8');
const lines = content.split('\n');

let count = 0;
let modified = [];

for (let i = 0; i < lines.length; i++) {
  const line = lines[i];

  // Check if this is a B2 entry without trAr
  if (line.includes('l:"B2"') && !line.includes('trAr:')) {
    // Extract the w field value
    const wMatch = line.match(/w:"([^"]+)"/);
    if (wMatch) {
      const wValue = wMatch[1];
      const translation = TRANSLATIONS[wValue];

      if (translation) {
        // Add trAr before the closing },
        const newLine = line.replace(/,l:"B2"\}/, `,l:"B2",trAr:"${translation}"}`);
        if (newLine !== line) {
          lines[i] = newLine;
          count++;
        } else {
          // Try alternative pattern: l:"B2"} at end
          const newLine2 = line.replace(/l:"B2"\}/, `l:"B2",trAr:"${translation}"}`);
          if (newLine2 !== line) {
            lines[i] = newLine2;
            count++;
          }
        }
      } else {
        modified.push(`MISSING: line ${i+1}: ${wValue}`);
      }
    }
  }
}

// Write back
fs.writeFileSync(filePath, lines.join('\n'), 'utf8');

console.log(`Total B2 entries translated: ${count}`);
console.log(`Missing translations: ${modified.length}`);
if (modified.length > 0) {
  console.log('\nMissing entries (first 50):');
  modified.slice(0, 50).forEach(m => console.log(m));
}
