#!/usr/bin/env python3
"""Append grammar, idioms, particles, functions to German CEFR reference file."""
import os

filepath = os.path.join(
    r"C:\Users\Jason\OneDrive\Documents\GitHub\Lingoverse\.claude\worktrees\thirsty-kirch",
    "src", "data", "cefr-reference", "german.js"
)

appendix = """
  // B2 VOCABULARY (No official Goethe B2 Wortliste exists)
  // Compiled from: Aspekte Neu B2, telc B2, Fluent in Deutsch, Olesen Tuition
  b2Vocabulary: [
    {w:"Gesellschaft",a:"die",g:"f",tr:"society",cat:"abstract"},
    {w:"Verantwortung",a:"die",g:"f",tr:"responsibility",cat:"abstract"},
    {w:"Herausforderung",a:"die",g:"f",tr:"challenge",cat:"abstract"},
    {w:"Entwicklung",a:"die",g:"f",tr:"development",cat:"abstract"},
    {w:"Fortschritt",a:"der",g:"m",tr:"progress",cat:"abstract"},
    {w:"Einfluss",a:"der",g:"m",tr:"influence",cat:"abstract"},
    {w:"Entscheidung",a:"die",g:"f",tr:"decision",cat:"abstract"},
    {w:"Voraussetzung",a:"die",g:"f",tr:"requirement",cat:"abstract"},
    {w:"Unterst\\u00fctzung",a:"die",g:"f",tr:"support",cat:"abstract"},
    {w:"Verhalten",a:"das",g:"n",tr:"behavior",cat:"abstract"},
    {w:"F\\u00e4higkeit",a:"die",g:"f",tr:"ability",cat:"abstract"},
    {w:"L\\u00f6sung",a:"die",g:"f",tr:"solution",cat:"abstract"},
    {w:"Ergebnis",a:"das",g:"n",tr:"result",cat:"abstract"},
    {w:"Konsequenz",a:"die",g:"f",tr:"consequence",cat:"abstract"},
    {w:"Ma\\u00dfnahme",a:"die",g:"f",tr:"measure/action",cat:"abstract"},
    {w:"Zusammenhang",a:"der",g:"m",tr:"context/connection",cat:"abstract"},
    {w:"Bedeutung",a:"die",g:"f",tr:"meaning/significance",cat:"abstract"},
    {w:"Gerechtigkeit",a:"die",g:"f",tr:"justice",cat:"abstract"},
    {w:"Vorstellungsgespr\\u00e4ch",a:"das",g:"n",tr:"job interview",cat:"work"},
    {w:"Bewerbung",a:"die",g:"f",tr:"application",cat:"work"},
    {w:"Weiterbildung",a:"die",g:"f",tr:"further education",cat:"work"},
    {w:"Lebenslauf",a:"der",g:"m",tr:"resume/CV",cat:"work"},
    {w:"Vertrag",a:"der",g:"m",tr:"contract",cat:"work"},
    {w:"Fachgebiet",a:"das",g:"n",tr:"area of expertise",cat:"work"},
    {w:"Karriere",a:"die",g:"f",tr:"career",cat:"work"},
    {w:"Gehalt",a:"das",g:"n",tr:"salary",cat:"work"},
    {w:"Umwelt",a:"die",g:"f",tr:"environment",cat:"society"},
    {w:"Klimawandel",a:"der",g:"m",tr:"climate change",cat:"society"},
    {w:"Gleichberechtigung",a:"die",g:"f",tr:"equality",cat:"society"},
    {w:"Integration",a:"die",g:"f",tr:"integration",cat:"society"},
    {w:"Nachrichten",a:"die",g:"f",tr:"news",cat:"society"},
    {w:"Werbung",a:"die",g:"f",tr:"advertisement",cat:"society"},
    {w:"Globalisierung",a:"die",g:"f",tr:"globalization",cat:"society"},
    {w:"Demokratie",a:"die",g:"f",tr:"democracy",cat:"society"},
    {w:"Gesundheit",a:"die",g:"f",tr:"health",cat:"health"},
    {w:"Ern\\u00e4hrung",a:"die",g:"f",tr:"nutrition",cat:"health"},
    {w:"Sucht",a:"die",g:"f",tr:"addiction",cat:"health"},
    {w:"Depression",a:"die",g:"f",tr:"depression",cat:"health"},
    {w:"Behandlung",a:"die",g:"f",tr:"treatment",cat:"health"},
    {w:"behaupten",a:"",g:"",tr:"to claim",cat:"verb"},
    {w:"vermuten",a:"",g:"",tr:"to assume",cat:"verb"},
    {w:"begr\\u00fcnden",a:"",g:"",tr:"to justify",cat:"verb"},
    {w:"\\u00fcberzeugen",a:"",g:"",tr:"to convince",cat:"verb"},
    {w:"darstellen",a:"",g:"",tr:"to present/portray",cat:"verb"},
    {w:"feststellen",a:"",g:"",tr:"to determine",cat:"verb"},
    {w:"zustimmen",a:"",g:"",tr:"to agree",cat:"verb"},
    {w:"widersprechen",a:"",g:"",tr:"to contradict",cat:"verb"},
    {w:"verursachen",a:"",g:"",tr:"to cause",cat:"verb"},
    {w:"k\\u00fcndigen",a:"",g:"",tr:"to quit/terminate",cat:"verb"},
    {w:"ver\\u00f6ffentlichen",a:"",g:"",tr:"to publish",cat:"verb"},
    {w:"beeinflussen",a:"",g:"",tr:"to influence",cat:"verb"},
    {w:"bew\\u00e4ltigen",a:"",g:"",tr:"to cope with",cat:"verb"},
    {w:"notwendig",a:"",g:"",tr:"necessary",cat:"adjective"},
    {w:"entscheidend",a:"",g:"",tr:"decisive",cat:"adjective"},
    {w:"zuverl\\u00e4ssig",a:"",g:"",tr:"reliable",cat:"adjective"},
    {w:"ausf\\u00fchrlich",a:"",g:"",tr:"detailed",cat:"adjective"},
    {w:"angemessen",a:"",g:"",tr:"appropriate",cat:"adjective"},
    {w:"umfassend",a:"",g:"",tr:"comprehensive",cat:"adjective"},
    {w:"wesentlich",a:"",g:"",tr:"essential",cat:"adjective"},
    {w:"zun\\u00e4chst",a:"",g:"",tr:"firstly",cat:"discourse"},
    {w:"dennoch",a:"",g:"",tr:"nevertheless",cat:"discourse"},
    {w:"allerdings",a:"",g:"",tr:"however",cat:"discourse"},
    {w:"inzwischen",a:"",g:"",tr:"meanwhile",cat:"discourse"},
    {w:"folglich",a:"",g:"",tr:"consequently",cat:"discourse"},
    {w:"hingegen",a:"",g:"",tr:"on the other hand",cat:"discourse"},
    {w:"insbesondere",a:"",g:"",tr:"in particular",cat:"discourse"},
    {w:"schlie\\u00dflich",a:"",g:"",tr:"finally/after all",cat:"discourse"},
  ],

  // GRAMMAR CONSTRUCTS BY CEFR LEVEL
  grammar: {
    A1: [
      {id:"g-a1-01",topic:"Present tense (Pr\\u00e4sens)",desc:"Regular verb conjugation: -e, -st, -t, -en, -t, -en",cat:"tense"},
      {id:"g-a1-02",topic:"Sein, haben, werden",desc:"Irregular core verbs in present tense",cat:"tense"},
      {id:"g-a1-03",topic:"Stem-changing verbs",desc:"e->i/ie (sprechen/spricht), a->\\u00e4 (fahren/f\\u00e4hrt)",cat:"verb"},
      {id:"g-a1-04",topic:"Separable verbs",desc:"aufstehen, einkaufen, anfangen",cat:"verb"},
      {id:"g-a1-05",topic:"Inseparable verbs",desc:"verstehen, bekommen, erkl\\u00e4ren",cat:"verb"},
      {id:"g-a1-06",topic:"Modal verbs",desc:"k\\u00f6nnen, m\\u00fcssen, wollen, d\\u00fcrfen, sollen, m\\u00f6gen/m\\u00f6chten",cat:"verb"},
      {id:"g-a1-07",topic:"Imperative (basic)",desc:"Sie-form, du-form, ihr-form commands",cat:"verb"},
      {id:"g-a1-08",topic:"Perfekt (introduction)",desc:"haben/sein + Partizip II",cat:"tense"},
      {id:"g-a1-09",topic:"Noun gender system",desc:"der (masculine), die (feminine), das (neuter)",cat:"noun"},
      {id:"g-a1-10",topic:"Definite articles (nom/akk)",desc:"der/die/das, den/die/das",cat:"noun"},
      {id:"g-a1-11",topic:"Indefinite articles (nom/akk)",desc:"ein/eine/ein, einen/eine/ein",cat:"noun"},
      {id:"g-a1-12",topic:"Negative article kein",desc:"kein/keine/kein and accusative forms",cat:"noun"},
      {id:"g-a1-13",topic:"Plural formation",desc:"Common patterns: -e, -en, -er, -s, umlaut + -e",cat:"noun"},
      {id:"g-a1-14",topic:"Compound nouns",desc:"das Schlafzimmer, der Geburtstag",cat:"noun"},
      {id:"g-a1-15",topic:"Nominative case",desc:"Subject: Der Mann liest",cat:"case"},
      {id:"g-a1-16",topic:"Accusative case",desc:"Direct object: Ich sehe den Mann",cat:"case"},
      {id:"g-a1-17",topic:"Personal pronouns (nom)",desc:"ich, du, er, sie, es, wir, ihr, sie, Sie",cat:"pronoun"},
      {id:"g-a1-18",topic:"Possessive pronouns (nom)",desc:"mein, dein, sein, ihr, unser, euer",cat:"pronoun"},
      {id:"g-a1-19",topic:"Formal vs informal",desc:"du/ihr vs Sie",cat:"pronoun"},
      {id:"g-a1-20",topic:"V2 word order",desc:"Verb always in second position",cat:"syntax"},
      {id:"g-a1-21",topic:"W-questions",desc:"wer, was, wo, wann, warum, wie, woher, wohin",cat:"syntax"},
      {id:"g-a1-22",topic:"Yes/No questions",desc:"Verb-first: Kommst du?",cat:"syntax"},
      {id:"g-a1-23",topic:"Negation: nicht/kein",desc:"Position rules",cat:"syntax"},
      {id:"g-a1-24",topic:"Coordinating conjunctions",desc:"und, oder, aber, denn",cat:"conjunction"},
      {id:"g-a1-25",topic:"Accusative prepositions",desc:"durch, f\\u00fcr, gegen, ohne, um",cat:"preposition"},
      {id:"g-a1-26",topic:"Dative prepositions",desc:"aus, bei, mit, nach, seit, von, zu",cat:"preposition"},
      {id:"g-a1-27",topic:"Temporal prepositions",desc:"am, um, im, von...bis",cat:"preposition"},
      {id:"g-a1-28",topic:"Predicate adjectives",desc:"Uninflected: Das Haus ist gro\\u00df",cat:"adjective"},
      {id:"g-a1-29",topic:"Cardinal numbers",desc:"0-1000+ and telling time",cat:"vocabulary"},
      {id:"g-a1-30",topic:"es gibt + accusative",desc:"There is/are",cat:"syntax"},
    ],
    A2: [
      {id:"g-a2-01",topic:"Dative case",desc:"dem/der/dem, einem/einer/einem",cat:"case"},
      {id:"g-a2-02",topic:"Articles in all 3 cases",desc:"Nominative, accusative, dative",cat:"case"},
      {id:"g-a2-03",topic:"Genitive case (intro)",desc:"Possession with -s, des/der/des",cat:"case"},
      {id:"g-a2-04",topic:"Personal pronouns (akk/dat)",desc:"mich/mir, dich/dir, ihn/ihm",cat:"pronoun"},
      {id:"g-a2-05",topic:"Possessive articles (all cases)",desc:"mein/meinen/meinem",cat:"pronoun"},
      {id:"g-a2-06",topic:"Adjective declension (definite)",desc:"Endings with der/die/das",cat:"adjective"},
      {id:"g-a2-07",topic:"Adjective declension (indefinite)",desc:"ein guter Mann, eine gute Frau",cat:"adjective"},
      {id:"g-a2-08",topic:"Comparatives",desc:"-er + als: gr\\u00f6\\u00dfer als",cat:"adjective"},
      {id:"g-a2-09",topic:"Superlatives",desc:"am + -sten / der + -ste",cat:"adjective"},
      {id:"g-a2-10",topic:"Irregular comparatives",desc:"gut/besser, viel/mehr, gern/lieber",cat:"adjective"},
      {id:"g-a2-11",topic:"Perfekt (full use)",desc:"haben vs sein, regular + irregular PP",cat:"tense"},
      {id:"g-a2-12",topic:"Pr\\u00e4teritum (introduction)",desc:"war, hatte, konnte, musste",cat:"tense"},
      {id:"g-a2-13",topic:"Futur I (introduction)",desc:"werden + infinitive",cat:"tense"},
      {id:"g-a2-14",topic:"Reflexive verbs",desc:"sich freuen, sich waschen, sich f\\u00fchlen",cat:"verb"},
      {id:"g-a2-15",topic:"Reflexive pronouns",desc:"Akk: mich/dich/sich. Dat: mir/dir/sich",cat:"pronoun"},
      {id:"g-a2-16",topic:"dass-clause",desc:"Verb to end: Ich wei\\u00df, dass er kommt",cat:"clause"},
      {id:"g-a2-17",topic:"weil-clause",desc:"Causal: Ich bleibe, weil es regnet",cat:"clause"},
      {id:"g-a2-18",topic:"wenn-clause",desc:"Conditional/temporal",cat:"clause"},
      {id:"g-a2-19",topic:"ob-clause",desc:"Whether: Ich wei\\u00df nicht, ob er kommt",cat:"clause"},
      {id:"g-a2-20",topic:"Wechselpr\\u00e4positionen",desc:"an, auf, hinter, in, neben, \\u00fcber, unter, vor, zwischen",cat:"preposition"},
      {id:"g-a2-21",topic:"Two-way preposition rule",desc:"Akk (motion) vs Dat (location)",cat:"preposition"},
      {id:"g-a2-22",topic:"Konjunktiv II (intro)",desc:"w\\u00fcrde + infinitive for polite requests",cat:"verb"},
      {id:"g-a2-23",topic:"Konjunktiv II basic forms",desc:"w\\u00e4re, h\\u00e4tte, k\\u00f6nnte, m\\u00fcsste",cat:"verb"},
      {id:"g-a2-24",topic:"Prefix system (full)",desc:"Separable and inseparable prefixes",cat:"verb"},
      {id:"g-a2-25",topic:"sondern",desc:"Not...but rather: nicht...sondern",cat:"conjunction"},
    ],
    B1: [
      {id:"g-b1-01",topic:"Pr\\u00e4teritum (full use)",desc:"Simple past for all verbs",cat:"tense"},
      {id:"g-b1-02",topic:"Plusquamperfekt",desc:"hatte/war + Partizip II",cat:"tense"},
      {id:"g-b1-03",topic:"Futur I (full use)",desc:"Plans, predictions, assumptions",cat:"tense"},
      {id:"g-b1-04",topic:"Passive (Vorgangspassiv)",desc:"werden + Partizip II",cat:"verb"},
      {id:"g-b1-05",topic:"Passive in Pr\\u00e4teritum",desc:"wurde + Partizip II",cat:"verb"},
      {id:"g-b1-06",topic:"Passive with modals",desc:"kann/muss + PP + werden",cat:"verb"},
      {id:"g-b1-07",topic:"Konjunktiv II (expanded)",desc:"Hypothetical: Wenn ich reich w\\u00e4re...",cat:"verb"},
      {id:"g-b1-08",topic:"Konjunktiv II irregular forms",desc:"w\\u00e4re, h\\u00e4tte, ginge, k\\u00e4me, w\\u00fcsste",cat:"verb"},
      {id:"g-b1-09",topic:"Genitive case (full)",desc:"des/der/des, eines/einer/eines",cat:"case"},
      {id:"g-b1-10",topic:"Genitive prepositions",desc:"w\\u00e4hrend, wegen, trotz, (an)statt, aufgrund",cat:"preposition"},
      {id:"g-b1-11",topic:"N-Deklination",desc:"der Junge/den Jungen, der Name/den Namen",cat:"case"},
      {id:"g-b1-12",topic:"Strong adjective declension",desc:"No article: guter Wein, kaltes Wasser",cat:"adjective"},
      {id:"g-b1-13",topic:"Mixed adjective declension",desc:"ein guter Wein",cat:"adjective"},
      {id:"g-b1-14",topic:"Partizip II as adjective",desc:"das gelesene Buch",cat:"adjective"},
      {id:"g-b1-15",topic:"Relative clauses",desc:"der/die/das as relative pronouns",cat:"clause"},
      {id:"g-b1-16",topic:"Relative clauses + prepositions",desc:"in dem, mit der, f\\u00fcr den",cat:"clause"},
      {id:"g-b1-17",topic:"als vs wenn",desc:"als (single past), wenn (repeated/present/future)",cat:"conjunction"},
      {id:"g-b1-18",topic:"bevor, nachdem",desc:"Before/after with tense correlation",cat:"conjunction"},
      {id:"g-b1-19",topic:"w\\u00e4hrend, seit, bis, solange",desc:"During, since, until, as long as",cat:"conjunction"},
      {id:"g-b1-20",topic:"da, deshalb/deswegen",desc:"Since (sub), therefore (adverb)",cat:"conjunction"},
      {id:"g-b1-21",topic:"obwohl, trotzdem",desc:"Although/despite",cat:"conjunction"},
      {id:"g-b1-22",topic:"damit, um...zu",desc:"Purpose clauses",cat:"conjunction"},
      {id:"g-b1-23",topic:"falls",desc:"In case / if",cat:"conjunction"},
      {id:"g-b1-24",topic:"Infinitive clauses with zu",desc:"um...zu, ohne...zu, (an)statt...zu",cat:"clause"},
      {id:"g-b1-25",topic:"Da-/Wo-compounds",desc:"daf\\u00fcr, dar\\u00fcber, wof\\u00fcr, wor\\u00fcber",cat:"pronoun"},
      {id:"g-b1-26",topic:"Verbs with fixed prepositions",desc:"warten auf+Akk, denken an+Akk",cat:"verb"},
      {id:"g-b1-27",topic:"Noun-verb combinations",desc:"eine Frage stellen, eine Entscheidung treffen",cat:"vocabulary"},
      {id:"g-b1-28",topic:"Verb lassen",desc:"Causative/permission",cat:"verb"},
      {id:"g-b1-29",topic:"Adjectives as nouns",desc:"der Deutsche, das Gute, etwas Neues",cat:"noun"},
      {id:"g-b1-30",topic:"Passive alternatives",desc:"sich lassen + inf, man-constructions",cat:"verb"},
    ],
    B2: [
      {id:"g-b2-01",topic:"Konjunktiv I (indirect speech)",desc:"Er sagte, er sei krank",cat:"verb"},
      {id:"g-b2-02",topic:"Konjunktiv I tense alignment",desc:"Present->Konj I present, past->Konj I past",cat:"verb"},
      {id:"g-b2-03",topic:"Konjunktiv II (past)",desc:"h\\u00e4tte/w\\u00e4re + Partizip II",cat:"verb"},
      {id:"g-b2-04",topic:"Subjective modal verbs",desc:"Er muss krank sein, Er k\\u00f6nnte recht haben",cat:"verb"},
      {id:"g-b2-05",topic:"Zustandspassiv",desc:"sein + PP: Das Fenster ist ge\\u00f6ffnet",cat:"verb"},
      {id:"g-b2-06",topic:"Passive in all tenses",desc:"Perfekt, Plusquamperfekt, Futur I passive",cat:"verb"},
      {id:"g-b2-07",topic:"Partizip I as adjective",desc:"die schlafende Katze",cat:"adjective"},
      {id:"g-b2-08",topic:"Extended attributes",desc:"der im letzten Jahr ver\\u00f6ffentlichte Bericht",cat:"adjective"},
      {id:"g-b2-09",topic:"Nominalization",desc:"Verb->noun -ung, infinitive as noun",cat:"noun"},
      {id:"g-b2-10",topic:"Nominalization suffixes",desc:"-heit, -keit, -nis, -schaft, -tum",cat:"noun"},
      {id:"g-b2-11",topic:"je...desto/umso",desc:"The more...the more",cat:"conjunction"},
      {id:"g-b2-12",topic:"sowohl...als auch",desc:"Both...and",cat:"conjunction"},
      {id:"g-b2-13",topic:"weder...noch",desc:"Neither...nor",cat:"conjunction"},
      {id:"g-b2-14",topic:"nicht nur...sondern auch",desc:"Not only...but also",cat:"conjunction"},
      {id:"g-b2-15",topic:"zwar...aber",desc:"Admittedly...but",cat:"conjunction"},
      {id:"g-b2-16",topic:"einerseits...andererseits",desc:"On one hand...on the other",cat:"conjunction"},
      {id:"g-b2-17",topic:"dessen, deren",desc:"Genitive relative pronouns",cat:"clause"},
      {id:"g-b2-18",topic:"obgleich, wenngleich",desc:"Literary concessive alternatives",cat:"conjunction"},
      {id:"g-b2-19",topic:"zumal, umso mehr als",desc:"Especially since",cat:"conjunction"},
      {id:"g-b2-20",topic:"Futur II",desc:"werden + PP + haben/sein",cat:"tense"},
      {id:"g-b2-21",topic:"Funktionsverbgef\\u00fcge",desc:"in Betracht ziehen, zur Verf\\u00fcgung stehen",cat:"verb"},
      {id:"g-b2-22",topic:"Adjective-preposition combos",desc:"stolz auf, zufrieden mit",cat:"adjective"},
      {id:"g-b2-23",topic:"Clause-to-noun transformation",desc:"Weil er krank war -> Wegen seiner Krankheit",cat:"syntax"},
      {id:"g-b2-24",topic:"Nested subordinate clauses",desc:"Nebensatz im Nebensatz",cat:"syntax"},
    ],
  },

  // IDIOMS & PROVERBS
  idioms: {
    A1: [{de:"Hallo / Guten Tag",en:"Hello / Good day",cat:"greeting"},{de:"Bitte / Danke",en:"Please / Thanks",cat:"polite"},{de:"Wie geht es Ihnen?",en:"How are you?",cat:"greeting"},{de:"Wie viel kostet das?",en:"How much?",cat:"survival"},{de:"Kein Problem",en:"No problem",cat:"casual"},{de:"Alles klar",en:"All clear",cat:"casual"}],
    A2: [{de:"Es kommt darauf an",en:"It depends",cat:"expression"},{de:"Das macht nichts",en:"It doesn't matter",cat:"expression"},{de:"\\u00dcbung macht den Meister",en:"Practice makes perfect",cat:"proverb"},{de:"Ende gut, alles gut",en:"All's well that ends well",cat:"proverb"},{de:"Auf jeden Fall",en:"Definitely",cat:"expression"}],
    B1: [{de:"Die Nase voll haben",en:"To be fed up",cat:"idiom"},{de:"Die Daumen dr\\u00fccken",en:"To wish luck",cat:"idiom"},{de:"Schwein haben",en:"To be lucky",cat:"idiom"},{de:"Aller Anfang ist schwer",en:"All beginnings are hard",cat:"proverb"},{de:"Wer rastet, der rostet",en:"Who rests, rusts",cat:"proverb"},{de:"Besser sp\\u00e4t als nie",en:"Better late than never",cat:"proverb"},{de:"Eile mit Weile",en:"More haste, less speed",cat:"proverb"}],
    B2: [{de:"Den Nagel auf den Kopf treffen",en:"Hit the nail on the head",cat:"idiom"},{de:"Tomaten auf den Augen haben",en:"To be oblivious",cat:"idiom"},{de:"Auf Wolke sieben schweben",en:"On cloud nine",cat:"idiom"},{de:"Aus einer M\\u00fccke einen Elefanten machen",en:"Mountain out of molehill",cat:"idiom"},{de:"Stille Wasser sind tief",en:"Still waters run deep",cat:"proverb"},{de:"Zusammenfassend l\\u00e4sst sich sagen...",en:"In summary...",cat:"redemittel"},{de:"Einerseits...andererseits...",en:"On one hand...on the other",cat:"redemittel"}],
  },

  // MODAL PARTICLES
  particles: {
    A2: [{de:"mal",desc:"Softens requests"},{de:"doch",desc:"Affirmative reply to negative"}],
    B1: [{de:"doch",desc:"Emphasis/reminder"},{de:"ja",desc:"Shared knowledge"},{de:"denn",desc:"Interest in questions"},{de:"eigentlich",desc:"Actually/by the way"}],
    B2: [{de:"eben/halt",desc:"Resignation"},{de:"wohl",desc:"Assumption"},{de:"schon",desc:"Reassurance"},{de:"blo\\u00df/nur",desc:"Urgency"},{de:"ruhig",desc:"Permission"}],
  },

  // PREPOSITIONS BY LEVEL
  prepositions: {
    A1: {accusative:["durch","f\\u00fcr","gegen","ohne","um"],dative:["aus","bei","mit","nach","seit","von","zu"],temporal:["am","um","im","von...bis"]},
    A2: {twoWay:["an","auf","hinter","in","neben","\\u00fcber","unter","vor","zwischen"]},
    B1: {genitive:["w\\u00e4hrend","wegen","trotz","(an)statt","aufgrund"]},
    B2: {genitive:["innerhalb","au\\u00dferhalb","oberhalb","unterhalb","bez\\u00fcglich","hinsichtlich","angesichts"]},
  },

  // CONJUNCTIONS BY LEVEL
  conjunctions: {
    A1: {coordinating:["und","oder","aber","denn"]},
    A2: {subordinating:["dass","weil","wenn","ob"],coordinating:["sondern"]},
    B1: {temporal:["als","bevor","nachdem","w\\u00e4hrend","seit","bis","solange"],causal:["da","deshalb"],concessive:["obwohl","trotzdem"],purpose:["damit","um...zu"],conditional:["falls"],infinitive:["ohne...zu","statt...zu"]},
    B2: {double:["je...desto","sowohl...als auch","weder...noch","nicht nur...sondern auch","zwar...aber","einerseits...andererseits"],advanced:["zumal","obgleich","wenngleich","je nachdem","geschweige denn"]},
  },

  // COMMUNICATIVE FUNCTIONS
  communicativeFunctions: {
    A1: ["Introduce yourself and others","Greet and say goodbye","Ask/answer personal questions","Order food and drinks","Make purchases","Ask for/give directions","Tell time","Describe daily routine","Talk about hobbies","Talk about family","Describe people/objects","Fill in forms","Write simple messages","Make appointments","Describe the weather","Express simple needs"],
    A2: ["Describe past events","Express future plans","Make comparisons","Express agreement/disagreement","Describe health issues","Handle basic travel","Give/follow instructions","Discuss work/education","Write personal letters","Express emotions","Handle shopping","Express preferences","Handle phone calls"],
    B1: ["Express/justify opinions","Narrate stories","Handle travel complaints","Write semi-formal emails","Summarize information","Express hypotheses","Give advice","Make/respond to suggestions","Discuss current events","Present a topic (3-5 min)","Plan collaboratively","Describe processes","Basic negotiation"],
    B2: ["Present detailed arguments","Negotiate and persuade","Speculate about causes","Discuss abstract topics","Write reports/essays","Write formal correspondence","Adapt register","Handle professional interactions","Lead discussions","Give presentations","Express uncertainty","Paraphrase/reformulate","Academic writing"],
  },
};
"""

with open(filepath, 'a', encoding='utf-8') as f:
    f.write(appendix)

size = os.path.getsize(filepath)
print(f"File complete. Size: {size:,} bytes ({size/1024:.1f} KB)")
