#!/usr/bin/env node
/**
 * Enrich German V2 teach cards with COMPOUND breakdowns.
 * For compound words (8+ char nouns), adds "COMPOUND: X (meaning) + Y (meaning)"
 * to the funFact field.
 *
 * Uses a dictionary of known German compound breakdowns + heuristic splitting.
 */
const fs = require('fs');
const path = require('path');

const dir = path.resolve(__dirname, '..', 'src', 'data', 'german-v2');
const files = fs.readdirSync(dir).filter(f => /^unit-\d+\.js$/.test(f)).sort();

// ── Known German compound breakdowns ──
// Format: bare word → "Part1 (meaning) + Part2 (meaning)"
const COMPOUNDS = {
  // Common everyday compounds
  'Fahrkarte': 'Fahr (ride) + Karte (card)',
  'Familienname': 'Familien (family) + Name (name)',
  'Familienstand': 'Familien (family) + Stand (status)',
  'Geburtstag': 'Geburt (birth) + Tag (day)',
  'Geburtsjahr': 'Geburt (birth) + Jahr (year)',
  'Geburtsort': 'Geburt (birth) + Ort (place)',
  'Wiedersehen': 'Wieder (again) + Sehen (seeing)',
  'Flughafen': 'Flug (flight) + Hafen (port)',
  'Flugzeug': 'Flug (flight) + Zeug (stuff/equipment)',
  'Deutschland': 'Deutsch (German) + Land (land)',
  'Ausländer': 'Aus (out) + Land (land) + er (person)',
  'Innenstadt': 'Innen (inner) + Stadt (city)',
  'Hauptstadt': 'Haupt (main/head) + Stadt (city)',
  'Stadtplan': 'Stadt (city) + Plan (map)',
  'Bahnhof': 'Bahn (track/railway) + Hof (courtyard)',
  'Hauptbahnhof': 'Haupt (main) + Bahn (railway) + Hof (station)',
  'Straßenbahn': 'Straße (street) + Bahn (track/railway)',
  'Bushaltestelle': 'Bus (bus) + Halte (stop) + Stelle (place)',
  'Haltestelle': 'Halte (stop) + Stelle (place)',
  'Fahrplan': 'Fahr (travel) + Plan (schedule)',
  'Fahrkartenautomat': 'Fahrkarte (ticket) + Automat (machine)',
  'Fahrrad': 'Fahr (ride) + Rad (wheel)',
  'Führerschein': 'Führer (driver) + Schein (certificate)',
  'Autobahn': 'Auto (car) + Bahn (track)',
  'Straßenverkehr': 'Straßen (street) + Verkehr (traffic)',
  'Fußgänger': 'Fuß (foot) + Gänger (goer)',
  'Kreuzung': 'Kreuz (cross) + ung (noun suffix)',
  'Ampel': null, // Not a compound
  'Parkplatz': 'Park (park) + Platz (place/spot)',
  'Tankstelle': 'Tank (tank) + Stelle (place)',

  // Food & drink
  'Frühstück': 'Früh (early) + Stück (piece)',
  'Mittagessen': 'Mittag (midday) + Essen (food/eating)',
  'Abendessen': 'Abend (evening) + Essen (food/eating)',
  'Lebensmittel': 'Leben (life) + Mittel (means/supplies)',
  'Kartoffel': null, // Not decomposable
  'Marktplatz': 'Markt (market) + Platz (place/square)',
  'Einkaufszentrum': 'Einkauf (purchase) + Zentrum (center)',
  'Einkaufswagen': 'Einkauf (shopping) + Wagen (cart)',
  'Apfelsaft': 'Apfel (apple) + Saft (juice)',
  'Orangensaft': 'Orangen (orange) + Saft (juice)',
  'Mineralwasser': 'Mineral (mineral) + Wasser (water)',
  'Trinkwasser': 'Trink (drinking) + Wasser (water)',
  'Milchkaffee': 'Milch (milk) + Kaffee (coffee)',
  'Erdbeere': 'Erd (earth) + Beere (berry)',
  'Rindfleisch': 'Rind (beef/cattle) + Fleisch (meat)',
  'Schweinefleisch': 'Schwein (pig) + Fleisch (meat)',
  'Hähnchen': null, // diminutive, not compound
  'Speisekarte': 'Speise (food/dish) + Karte (card/menu)',
  'Nachtisch': 'Nach (after) + Tisch (table)',
  'Handtuch': 'Hand (hand) + Tuch (cloth)',
  'Taschentuch': 'Taschen (pocket) + Tuch (cloth)',
  'Kühlschrank': 'Kühl (cool) + Schrank (cabinet)',
  'Waschmaschine': 'Wasch (wash) + Maschine (machine)',
  'Spülmaschine': 'Spül (rinse) + Maschine (machine)',

  // Home & living
  'Wohnzimmer': 'Wohn (living) + Zimmer (room)',
  'Schlafzimmer': 'Schlaf (sleep) + Zimmer (room)',
  'Badezimmer': 'Bade (bath) + Zimmer (room)',
  'Kinderzimmer': 'Kinder (children) + Zimmer (room)',
  'Arbeitszimmer': 'Arbeit (work) + Zimmer (room)',
  'Esszimmer': 'Ess (eating) + Zimmer (room)',
  'Wohnung': 'Wohn (live) + ung (noun suffix)',
  'Mietwohnung': 'Miet (rent) + Wohnung (apartment)',
  'Eigentumswohnung': 'Eigentum (property) + Wohnung (apartment)',
  'Einfamilienhaus': 'Ein (one) + Familie (family) + Haus (house)',
  'Mehrfamilienhaus': 'Mehr (multiple) + Familie (family) + Haus (house)',
  'Hochhaus': 'Hoch (high) + Haus (house)',
  'Erdgeschoss': 'Erd (ground) + Geschoss (floor/story)',
  'Dachgeschoss': 'Dach (roof) + Geschoss (floor/story)',
  'Treppenhaus': 'Treppen (stairs) + Haus (house)',
  'Hausnummer': 'Haus (house) + Nummer (number)',
  'Briefkasten': 'Brief (letter) + Kasten (box)',
  'Schlüsselbund': 'Schlüssel (key) + Bund (bundle)',
  'Haustier': 'Haus (house) + Tier (animal)',
  'Haustür': 'Haus (house) + Tür (door)',
  'Möbelstück': 'Möbel (furniture) + Stück (piece)',
  'Bücherregal': 'Bücher (books) + Regal (shelf)',

  // Work & education
  'Arbeitsplatz': 'Arbeit (work) + Platz (place)',
  'Arbeitgeber': 'Arbeit (work) + Geber (giver)',
  'Arbeitnehmer': 'Arbeit (work) + Nehmer (taker)',
  'Arbeitszeit': 'Arbeit (work) + Zeit (time)',
  'Arbeitslos': 'Arbeit (work) + los (without)',
  'Arbeitslosigkeit': 'Arbeit (work) + Losigkeit (lack/without-ness)',
  'Grundschule': 'Grund (basic) + Schule (school)',
  'Hauptschule': 'Haupt (main) + Schule (school)',
  'Hochschule': 'Hoch (high) + Schule (school)',
  'Berufsschule': 'Beruf (profession) + Schule (school)',
  'Fahrschule': 'Fahr (driving) + Schule (school)',
  'Kindergarten': 'Kinder (children) + Garten (garden)',
  'Schuljahr': 'Schul (school) + Jahr (year)',
  'Studiengang': 'Studien (studies) + Gang (path/course)',
  'Lebenslauf': 'Leben (life) + Lauf (run/course)',
  'Vorstellungsgespräch': 'Vorstellung (introduction) + Gespräch (conversation)',
  'Bewerbung': 'Be (prefix) + Werbung (advertising/application)',
  'Ausbildung': 'Aus (out/complete) + Bildung (formation/education)',
  'Weiterbildung': 'Weiter (further) + Bildung (education)',
  'Fortbildung': 'Fort (further) + Bildung (education)',

  // Health & body
  'Krankenhaus': 'Kranken (sick ones) + Haus (house)',
  'Krankenwagen': 'Kranken (sick) + Wagen (vehicle)',
  'Krankenschwester': 'Kranken (sick) + Schwester (sister)',
  'Krankenkasse': 'Kranken (sick/health) + Kasse (fund/insurance)',
  'Kopfschmerzen': 'Kopf (head) + Schmerzen (pains)',
  'Bauchschmerzen': 'Bauch (stomach) + Schmerzen (pains)',
  'Rückenschmerzen': 'Rücken (back) + Schmerzen (pains)',
  'Zahnschmerzen': 'Zahn (tooth) + Schmerzen (pains)',
  'Halsschmerzen': 'Hals (throat) + Schmerzen (pains)',
  'Schmerzmittel': 'Schmerz (pain) + Mittel (remedy/means)',
  'Krankmeldung': 'Krank (sick) + Meldung (notification)',
  'Gesundheit': 'Gesund (healthy) + heit (abstract noun suffix)',
  'Krankheit': 'Krank (sick) + heit (abstract noun suffix)',
  'Sonnenbrand': 'Sonnen (sun) + Brand (burn)',
  'Sonnenbrille': 'Sonnen (sun) + Brille (glasses)',
  'Sonnenschein': 'Sonnen (sun) + Schein (shine)',
  'Sonnencreme': 'Sonnen (sun) + Creme (cream)',
  'Augentropfen': 'Augen (eye) + Tropfen (drops)',
  'Zahnarzt': 'Zahn (tooth) + Arzt (doctor)',
  'Kinderarzt': 'Kinder (children) + Arzt (doctor)',
  'Hautarzt': 'Haut (skin) + Arzt (doctor)',
  'Augenarzt': 'Augen (eye) + Arzt (doctor)',
  'Tierarzt': 'Tier (animal) + Arzt (doctor)',
  'Facharzt': 'Fach (specialist/field) + Arzt (doctor)',
  'Hausarzt': 'Haus (house) + Arzt (doctor)',

  // Nature & weather
  'Jahreszeit': 'Jahr (year) + Zeit (time/season)',
  'Sonnenschein': 'Sonnen (sun) + Schein (shine)',
  'Regenschirm': 'Regen (rain) + Schirm (shield/umbrella)',
  'Sonnenschirm': 'Sonnen (sun) + Schirm (umbrella/parasol)',
  'Schneemann': 'Schnee (snow) + Mann (man)',
  'Schneeflocke': 'Schnee (snow) + Flocke (flake)',
  'Wetterbericht': 'Wetter (weather) + Bericht (report)',
  'Wettervorhersage': 'Wetter (weather) + Vorhersage (forecast)',
  'Waldspaziergang': 'Wald (forest) + Spaziergang (walk)',
  'Spaziergang': 'Spazier (stroll) + Gang (walk/path)',
  'Gebirge': null, // collective, not compound
  'Landschaft': 'Land (land) + schaft (domain suffix)',
  'Naturschutz': 'Natur (nature) + Schutz (protection)',
  'Umweltschutz': 'Umwelt (environment) + Schutz (protection)',
  'Klimawandel': 'Klima (climate) + Wandel (change)',

  // Time & dates
  'Wochenende': 'Wochen (week) + Ende (end)',
  'Wochentag': 'Wochen (week) + Tag (day)',
  'Feiertag': 'Feier (celebration) + Tag (day)',
  'Geburtstag': 'Geburt (birth) + Tag (day)',
  'Namenstag': 'Namen (name) + Tag (day)',
  'Arbeitstag': 'Arbeit (work) + Tag (day)',
  'Werktag': 'Werk (work) + Tag (day)',
  'Jahrzehnt': 'Jahr (year) + Zehnt (tenth)',
  'Jahrhundert': 'Jahr (year) + Hundert (hundred)',
  'Jahrtausend': 'Jahr (year) + Tausend (thousand)',
  'Nachmittag': 'Nach (after) + Mittag (midday)',
  'Vormittag': 'Vor (before) + Mittag (midday)',
  'Mitternacht': 'Mitter (middle) + Nacht (night)',
  'Tageszeit': 'Tage (day) + Zeit (time)',
  'Uhrzeit': 'Uhr (clock) + Zeit (time)',
  'Zeitraum': 'Zeit (time) + Raum (space)',
  'Zeitschrift': 'Zeit (time) + Schrift (writing)',
  'Zeitung': 'Zeit (time) + ung (noun suffix)',

  // Technology & media
  'Fernsehen': 'Fern (far) + Sehen (seeing)',
  'Fernseher': 'Fern (far) + Seher (viewer)',
  'Fernbedienung': 'Fern (remote) + Bedienung (control)',
  'Handy': null, // not a compound (English loanword)
  'Mobiltelefon': 'Mobil (mobile) + Telefon (telephone)',
  'Anrufbeantworter': 'Anruf (call) + Beantworter (answerer)',
  'Bildschirm': 'Bild (picture) + Schirm (screen)',
  'Tastatur': null, // from Latin, not compound
  'Drucker': null, // agent noun, not compound
  'Lautsprecher': 'Laut (loud) + Sprecher (speaker)',
  'Kopfhörer': 'Kopf (head) + Hörer (listener)',
  'Nachricht': 'Nach (after) + Richt (direction/message)',
  'Nachrichten': 'Nach (after) + Richten (to direct)',
  'Tagesschau': 'Tage (day) + Schau (show)',
  'Steckdose': 'Steck (plug) + Dose (socket/can)',
  'Ladegerät': 'Lade (charge) + Gerät (device)',
  'Suchmaschine': 'Such (search) + Maschine (machine)',
  'Datenbank': 'Daten (data) + Bank (bank/bench)',
  'Passwort': 'Pass (pass) + Wort (word)',
  'Netzwerk': 'Netz (net) + Werk (work)',
  'Sicherheit': 'Sicher (safe) + heit (abstract noun suffix)',
  'Wissenschaft': 'Wissen (knowledge) + schaft (domain)',
  'Gesellschaft': 'Gesell (companion) + schaft (domain)',
  'Gemeinschaft': 'Gemein (common) + schaft (domain)',
  'Freundschaft': 'Freund (friend) + schaft (domain)',
  'Partnerschaft': 'Partner (partner) + schaft (domain)',
  'Mannschaft': 'Mann (man) + schaft (domain/team)',
  'Wirtschaft': 'Wirt (host/manager) + schaft (domain)',
  'Eigenschaft': 'Eigen (own) + schaft (domain/quality)',
  'Herrschaft': 'Herr (lord/master) + schaft (domain)',
  'Botschaft': 'Bot (message) + schaft (domain)',
  'Landschaft': 'Land (land) + schaft (domain)',
  'Bereitschaft': 'Bereit (ready) + schaft (domain)',
  'Leidenschaft': 'Leiden (suffering/passion) + schaft (domain)',
  'Meisterschaft': 'Meister (master) + schaft (domain)',
  'Nachbarschaft': 'Nachbar (neighbor) + schaft (domain)',
  'Wanderschaft': 'Wander (wander) + schaft (domain)',
  'Verwandtschaft': 'Verwandt (related) + schaft (domain)',
  'Staatsbürger': 'Staat (state) + Bürger (citizen)',
  'Staatsbürgerschaft': 'Staatsbürger (citizen) + schaft (status)',
  'Aufenthalt': 'Auf (on/at) + Enthalt (holding/staying)',
  'Aufenthaltserlaubnis': 'Aufenthalt (stay) + Erlaubnis (permission)',
  'Aufenthaltsgenehmigung': 'Aufenthalt (stay) + Genehmigung (approval)',
  'Verständnis': 'Ver (prefix) + Stand (standing) + nis (noun suffix)',
  'Verständigung': 'Verständig (understanding) + ung (noun suffix)',
  'Einwanderer': 'Ein (in) + Wanderer (wanderer)',
  'Auswanderer': 'Aus (out) + Wanderer (wanderer)',
  'Einwanderung': 'Ein (in) + Wanderung (wandering)',
  'Auswanderung': 'Aus (out) + Wanderung (wandering)',
  'Flüchtling': null, // derivation, not compound
  'Muttersprache': 'Mutter (mother) + Sprache (language)',
  'Fremdsprache': 'Fremd (foreign) + Sprache (language)',
  'Wortschatz': 'Wort (word) + Schatz (treasure)',
  'Sprachkurs': 'Sprach (language) + Kurs (course)',
  'Sprachschule': 'Sprach (language) + Schule (school)',
  'Buchhandlung': 'Buch (book) + Handlung (action/shop)',
  'Handlung': null, // derivation
  'Buchstabe': 'Buch (beech) + Stab (stick/staff)',
  'Meinungsfreiheit': 'Meinung (opinion) + Freiheit (freedom)',
  'Pressefreiheit': 'Presse (press) + Freiheit (freedom)',
  'Reisepass': 'Reise (travel) + Pass (pass/passport)',
  'Reisebüro': 'Reise (travel) + Büro (office)',
  'Reiseführer': 'Reise (travel) + Führer (guide)',
  'Sitzplatz': 'Sitz (seat) + Platz (place)',
  'Spielplatz': 'Spiel (play) + Platz (place)',
  'Marktplatz': 'Markt (market) + Platz (place/square)',
  'Parkplatz': 'Park (park) + Platz (place/spot)',
  'Arbeitsplatz': 'Arbeit (work) + Platz (place)',
  'Stehplatz': 'Steh (standing) + Platz (place)',
  'Schlafplatz': 'Schlaf (sleep) + Platz (place)',
  'Stellplatz': 'Stell (place) + Platz (spot)',
  'Werkstatt': 'Werk (work) + Statt (place)',
  'Tankstelle': 'Tank (tank) + Stelle (place)',
  'Feuerwehr': 'Feuer (fire) + Wehr (defense)',
  'Feuerwehrmann': 'Feuerwehr (fire brigade) + Mann (man)',
  'Wasserfall': 'Wasser (water) + Fall (fall)',
  'Wasserhahn': 'Wasser (water) + Hahn (cock/tap)',
  'Abwasser': 'Ab (away) + Wasser (water)',
  'Grundwasser': 'Grund (ground) + Wasser (water)',
  'Trinkwasser': 'Trink (drinking) + Wasser (water)',
  'Leitungswasser': 'Leitung (pipe/line) + Wasser (water)',
  'Schwimmbad': 'Schwimm (swim) + Bad (bath)',
  'Hallenbad': 'Hallen (hall) + Bad (bath)',
  'Freibad': 'Frei (open-air) + Bad (bath)',
  'Rathaus': 'Rat (council) + Haus (house)',
  'Kaufhaus': 'Kauf (buy) + Haus (house)',
  'Warenhaus': 'Waren (goods) + Haus (house)',
  'Krankenhaus': 'Kranken (sick) + Haus (house)',
  'Baumwolle': 'Baum (tree) + Wolle (wool)',
  'Handschuh': 'Hand (hand) + Schuh (shoe)',
  'Rolltreppe': 'Roll (rolling) + Treppe (stairs)',
  'Fahrstuhl': 'Fahr (ride) + Stuhl (chair)',
  'Aufzug': 'Auf (up) + Zug (pull/train)',
  'Ausgang': 'Aus (out) + Gang (way/path)',
  'Eingang': 'Ein (in) + Gang (way/path)',
  'Notausgang': 'Not (emergency) + Ausgang (exit)',
  'Übergang': 'Über (over) + Gang (way/path)',
  'Durchgang': 'Durch (through) + Gang (way/path)',
  'Zugang': 'Zu (to/access) + Gang (way/path)',
  'Umgang': 'Um (around) + Gang (way)',
  'Vorgang': 'Vor (forward/before) + Gang (process)',
  'Hergang': 'Her (here/to) + Gang (course)',
  'Rückgang': 'Rück (back) + Gang (going)',
  'Untergang': 'Unter (under) + Gang (going)',
  'Zusammenhang': 'Zusammen (together) + Hang (connection)',
  'Gegenstand': 'Gegen (against/opposite) + Stand (standing)',
  'Umstand': 'Um (around) + Stand (standing)',
  'Zustand': 'Zu (to) + Stand (standing)',
  'Bestandteil': 'Bestand (stock) + Teil (part)',
  'Grundstück': 'Grund (ground) + Stück (piece)',
  'Kunstwerk': 'Kunst (art) + Werk (work)',
  'Meisterwerk': 'Meister (master) + Werk (work)',
  'Bauwerk': 'Bau (building/construction) + Werk (work)',
  'Schreibtisch': 'Schreib (writing) + Tisch (table)',
  'Nachttisch': 'Nacht (night) + Tisch (table)',
  'Esstisch': 'Ess (eating) + Tisch (table)',
  'Stammtisch': 'Stamm (regular/tribe) + Tisch (table)',
  'Geburtstagskuchen': 'Geburtstag (birthday) + Kuchen (cake)',
  'Hochzeit': 'Hoch (high) + Zeit (time)',
  'Hochzeitsreise': 'Hochzeit (wedding) + Reise (trip)',
  'Sehenswürdigkeit': 'Sehens (seeing) + Würdig (worthy) + keit (suffix)',
  'Weihnachten': 'Weih (holy) + Nachten (nights)',
  'Weihnachtsbaum': 'Weihnacht (Christmas) + Baum (tree)',
  'Weihnachtsmarkt': 'Weihnacht (Christmas) + Markt (market)',
  'Silvester': null, // not a compound (name)
  'Feuerwerk': 'Feuer (fire) + Werk (work)',
  'Geburtstagskarte': 'Geburtstag (birthday) + Karte (card)',
  'Glückwunsch': 'Glück (luck/happiness) + Wunsch (wish)',
  'Herzlichen': null, // adjective form
  'Lebensgefahr': 'Leben (life) + Gefahr (danger)',
  'Todesstrafe': 'Tod (death) + Strafe (punishment)',
  'Menschenrecht': 'Menschen (human) + Recht (right)',
  'Menschenrechte': 'Menschen (human) + Rechte (rights)',
  'Gleichberechtigung': 'Gleich (equal) + Berechtigung (authorization)',
  'Weltanschauung': 'Welt (world) + Anschauung (view)',
  'Zeitgeist': 'Zeit (time) + Geist (spirit)',
  'Wanderlust': 'Wander (wander) + Lust (desire)',
  'Kindergarten': 'Kinder (children) + Garten (garden)',
  'Schadenfreude': 'Schaden (damage) + Freude (joy)',
  'Angst': null, // not compound
  'Doppelgänger': 'Doppel (double) + Gänger (goer)',
  'Hintergrund': 'Hinter (behind) + Grund (ground)',
  'Vordergrund': 'Vorder (front) + Grund (ground)',
  'Untergrund': 'Unter (under) + Grund (ground)',
  'Hintergrundmusik': 'Hintergrund (background) + Musik (music)',
  'Straßenmusikant': 'Straßen (street) + Musikant (musician)',
  'Volkslied': 'Volk (folk/people) + Lied (song)',
  'Volksmusik': 'Volk (folk) + Musik (music)',
  'Weltkrieg': 'Welt (world) + Krieg (war)',
  'Wiedervereinigung': 'Wieder (again) + Vereinigung (unification)',
  'Mauerfall': 'Mauer (wall) + Fall (fall)',
  'Brückentag': 'Brücken (bridge) + Tag (day)',
  'Straßenfest': 'Straßen (street) + Fest (festival)',
  'Volksfest': 'Volk (folk) + Fest (festival)',
  'Stadtfest': 'Stadt (city) + Fest (festival)',
  'Sommerfest': 'Sommer (summer) + Fest (festival)',
  'Winterschlaf': 'Winter (winter) + Schlaf (sleep)',
  'Frühling': null, // derivation
  'Herbstferien': 'Herbst (autumn) + Ferien (holidays)',
  'Sommerferien': 'Sommer (summer) + Ferien (holidays)',
  'Winterferien': 'Winter (winter) + Ferien (holidays)',
  'Osterferien': 'Oster (Easter) + Ferien (holidays)',
  'Weihnachtsferien': 'Weihnacht (Christmas) + Ferien (holidays)',
  'Schulferien': 'Schul (school) + Ferien (holidays)',
  'Urlaub': null, // not compound
  'Urlaubstag': 'Urlaub (holiday) + Tag (day)',
  'Urlaubsreise': 'Urlaub (holiday) + Reise (trip)',
  'Staubsauger': 'Staub (dust) + Sauger (sucker)',
  'Geschirrspüler': 'Geschirr (dishes) + Spüler (rinser)',
  'Waschbecken': 'Wasch (wash) + Becken (basin)',
  'Bürgermeister': 'Bürger (citizen) + Meister (master)',
  'Oberbürgermeister': 'Ober (upper) + Bürgermeister (mayor)',
  'Berufsverkehr': 'Beruf (profession) + Verkehr (traffic)',
  'Nahverkehr': 'Nah (near) + Verkehr (traffic)',
  'Fernverkehr': 'Fern (far) + Verkehr (traffic)',
  'Verkehrsmittel': 'Verkehr (traffic) + Mittel (means)',
  'Fluggesellschaft': 'Flug (flight) + Gesellschaft (company)',
  'Reisegesellschaft': 'Reise (travel) + Gesellschaft (company)',
  'Versicherung': 'Ver (prefix) + Sicher (safe) + ung (noun suffix)',
  'Krankenversicherung': 'Kranken (health) + Versicherung (insurance)',
  'Lebensversicherung': 'Leben (life) + Versicherung (insurance)',
  'Rentenversicherung': 'Renten (pension) + Versicherung (insurance)',
  'Unfallversicherung': 'Unfall (accident) + Versicherung (insurance)',
  'Sozialversicherung': 'Sozial (social) + Versicherung (insurance)',
  'Steuererklärung': 'Steuer (tax) + Erklärung (declaration)',
  'Einkommenssteuer': 'Einkommen (income) + Steuer (tax)',
  'Mehrwertsteuer': 'Mehrwert (added value) + Steuer (tax)',
  'Zusammenarbeit': 'Zusammen (together) + Arbeit (work)',
  'Mitarbeiter': 'Mit (with) + Arbeiter (worker)',
  'Selbstständig': 'Selbst (self) + Ständig (standing)',
  'Selbstvertrauen': 'Selbst (self) + Vertrauen (trust)',
  'Selbstbewusstsein': 'Selbst (self) + Bewusstsein (consciousness)',
  'Verantwortung': 'Ver (prefix) + Antwort (answer) + ung (suffix)',
  'Entscheidung': 'Ent (prefix) + Scheidung (separation/decision)',
  'Entschuldigung': 'Ent (un-) + Schuld (guilt) + igung (suffix)',
  'Entwicklung': 'Ent (un-) + Wicklung (wrapping)',
  'Überraschung': 'Über (over) + Raschung (rush/surprise)',
  'Vorstellung': 'Vor (before/forward) + Stellung (placing)',
  'Darstellung': 'Dar (there/forth) + Stellung (placing)',
  'Ausstellung': 'Aus (out) + Stellung (placing/exhibition)',
  'Herstellung': 'Her (to/forth) + Stellung (placing/production)',
  'Beziehung': 'Be (prefix) + Ziehung (pulling/drawing)',
  'Erziehung': 'Er (prefix) + Ziehung (pulling/raising)',
  'Einladung': 'Ein (in) + Ladung (loading/invitation)',
  'Verladung': 'Ver (prefix) + Ladung (loading)',
  'Entladung': 'Ent (un-) + Ladung (loading/discharge)',
  'Belastung': 'Be (prefix) + Lastung (burdening)',
  'Entlastung': 'Ent (un-) + Lastung (burdening/relief)',
  'Anmeldung': 'An (on/at) + Meldung (report/registration)',
  'Abmeldung': 'Ab (off) + Meldung (report/deregistration)',
  'Einrichtung': 'Ein (in) + Richtung (direction/setting up)',
  'Ausrichtung': 'Aus (out) + Richtung (direction/orientation)',
  'Verrichtung': 'Ver (prefix) + Richtung (doing/task)',
  'Straßenverkehrsordnung': 'Straßenverkehr (road traffic) + Ordnung (regulation)',
  'Geschwindigkeitsbegrenzung': 'Geschwindigkeit (speed) + Begrenzung (limit)',
  'Umweltverschmutzung': 'Umwelt (environment) + Verschmutzung (pollution)',
  'Arbeitserlaubnis': 'Arbeit (work) + Erlaubnis (permission)',
};

let totalEnriched = 0;

for (const file of files) {
  const filePath = path.join(dir, file);
  const content = fs.readFileSync(filePath, 'utf8');
  let modified = content;
  let count = 0;

  // Find teach cards with pos:"noun" and check if the bare word is a compound
  modified = modified.replace(/(\{type:"teach",trg:"([^"]*)",src:"([^"]*)",pos:"noun"[^}]*funFact:"([^"]*)")/g,
    (match, full, trg, src, existingFunFact) => {
      const bare = trg.replace(/^(der|die|das|ein|eine)\s+/, '');
      if (bare.length < 8) return match;

      const breakdown = COMPOUNDS[bare];
      if (breakdown === undefined || breakdown === null) return match;

      // Check if funFact already mentions COMPOUND
      if (existingFunFact.includes('COMPOUND')) return match;

      // Prepend compound breakdown to existing funFact
      const newFunFact = `COMPOUND: ${breakdown}. ${existingFunFact}`;
      const escaped = newFunFact.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
      count++;
      totalEnriched++;

      return full.replace(`funFact:"${existingFunFact}"`, `funFact:"${escaped}"`);
    });

  if (count > 0) {
    fs.writeFileSync(filePath, modified);
    console.log(`${file}: ${count} compound breakdowns added`);
  }
}

console.log(`\nTotal: ${totalEnriched} compound breakdowns added to German v2`);
